// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: adequacy_assessments.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAdequacyAssessment = `-- name: CreateAdequacyAssessment :one
INSERT INTO adequacy_assessments (
    hospital_id, patient_id, session_id, assessed_by, assessment_date,
    kt_v, kt_v_method, urr_percent, pre_bun_mg_dl, post_bun_mg_dl,
    pre_creatinine_mg_dl, post_creatinine_mg_dl, dialysis_duration_mins,
    blood_flow_rate, dialyzer_clearance, body_water_volume_liters,
    is_adequate, recommendations, next_assessment_date, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20)
RETURNING id, hospital_id, patient_id, session_id, assessed_by, assessment_date, kt_v, kt_v_method, urr_percent, pre_bun_mg_dl, post_bun_mg_dl, pre_creatinine_mg_dl, post_creatinine_mg_dl, dialysis_duration_mins, blood_flow_rate, dialyzer_clearance, body_water_volume_liters, is_adequate, recommendations, next_assessment_date, notes, created_at, updated_at, deleted_at
`

type CreateAdequacyAssessmentParams struct {
	HospitalID            uuid.UUID      `json:"hospital_id"`
	PatientID             uuid.UUID      `json:"patient_id"`
	SessionID             pgtype.UUID    `json:"session_id"`
	AssessedBy            uuid.UUID      `json:"assessed_by"`
	AssessmentDate        pgtype.Date    `json:"assessment_date"`
	KtV                   pgtype.Numeric `json:"kt_v"`
	KtVMethod             pgtype.Text    `json:"kt_v_method"`
	UrrPercent            pgtype.Numeric `json:"urr_percent"`
	PreBunMgDl            pgtype.Numeric `json:"pre_bun_mg_dl"`
	PostBunMgDl           pgtype.Numeric `json:"post_bun_mg_dl"`
	PreCreatinineMgDl     pgtype.Numeric `json:"pre_creatinine_mg_dl"`
	PostCreatinineMgDl    pgtype.Numeric `json:"post_creatinine_mg_dl"`
	DialysisDurationMins  pgtype.Int4    `json:"dialysis_duration_mins"`
	BloodFlowRate         pgtype.Int4    `json:"blood_flow_rate"`
	DialyzerClearance     pgtype.Int4    `json:"dialyzer_clearance"`
	BodyWaterVolumeLiters pgtype.Numeric `json:"body_water_volume_liters"`
	IsAdequate            bool           `json:"is_adequate"`
	Recommendations       pgtype.Text    `json:"recommendations"`
	NextAssessmentDate    pgtype.Date    `json:"next_assessment_date"`
	Notes                 pgtype.Text    `json:"notes"`
}

func (q *Queries) CreateAdequacyAssessment(ctx context.Context, arg CreateAdequacyAssessmentParams) (AdequacyAssessment, error) {
	row := q.db.QueryRow(ctx, createAdequacyAssessment,
		arg.HospitalID,
		arg.PatientID,
		arg.SessionID,
		arg.AssessedBy,
		arg.AssessmentDate,
		arg.KtV,
		arg.KtVMethod,
		arg.UrrPercent,
		arg.PreBunMgDl,
		arg.PostBunMgDl,
		arg.PreCreatinineMgDl,
		arg.PostCreatinineMgDl,
		arg.DialysisDurationMins,
		arg.BloodFlowRate,
		arg.DialyzerClearance,
		arg.BodyWaterVolumeLiters,
		arg.IsAdequate,
		arg.Recommendations,
		arg.NextAssessmentDate,
		arg.Notes,
	)
	var i AdequacyAssessment
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.PatientID,
		&i.SessionID,
		&i.AssessedBy,
		&i.AssessmentDate,
		&i.KtV,
		&i.KtVMethod,
		&i.UrrPercent,
		&i.PreBunMgDl,
		&i.PostBunMgDl,
		&i.PreCreatinineMgDl,
		&i.PostCreatinineMgDl,
		&i.DialysisDurationMins,
		&i.BloodFlowRate,
		&i.DialyzerClearance,
		&i.BodyWaterVolumeLiters,
		&i.IsAdequate,
		&i.Recommendations,
		&i.NextAssessmentDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteAdequacyAssessment = `-- name: DeleteAdequacyAssessment :exec
UPDATE adequacy_assessments SET deleted_at = now() WHERE id = $1
`

func (q *Queries) DeleteAdequacyAssessment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAdequacyAssessment, id)
	return err
}

const getAdequacyAssessment = `-- name: GetAdequacyAssessment :one
SELECT id, hospital_id, patient_id, session_id, assessed_by, assessment_date, kt_v, kt_v_method, urr_percent, pre_bun_mg_dl, post_bun_mg_dl, pre_creatinine_mg_dl, post_creatinine_mg_dl, dialysis_duration_mins, blood_flow_rate, dialyzer_clearance, body_water_volume_liters, is_adequate, recommendations, next_assessment_date, notes, created_at, updated_at, deleted_at FROM adequacy_assessments WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAdequacyAssessment(ctx context.Context, id uuid.UUID) (AdequacyAssessment, error) {
	row := q.db.QueryRow(ctx, getAdequacyAssessment, id)
	var i AdequacyAssessment
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.PatientID,
		&i.SessionID,
		&i.AssessedBy,
		&i.AssessmentDate,
		&i.KtV,
		&i.KtVMethod,
		&i.UrrPercent,
		&i.PreBunMgDl,
		&i.PostBunMgDl,
		&i.PreCreatinineMgDl,
		&i.PostCreatinineMgDl,
		&i.DialysisDurationMins,
		&i.BloodFlowRate,
		&i.DialyzerClearance,
		&i.BodyWaterVolumeLiters,
		&i.IsAdequate,
		&i.Recommendations,
		&i.NextAssessmentDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAdequacyAssessmentsByPatient = `-- name: ListAdequacyAssessmentsByPatient :many
SELECT id, hospital_id, patient_id, session_id, assessed_by, assessment_date, kt_v, kt_v_method, urr_percent, pre_bun_mg_dl, post_bun_mg_dl, pre_creatinine_mg_dl, post_creatinine_mg_dl, dialysis_duration_mins, blood_flow_rate, dialyzer_clearance, body_water_volume_liters, is_adequate, recommendations, next_assessment_date, notes, created_at, updated_at, deleted_at FROM adequacy_assessments
WHERE patient_id = $1 AND deleted_at IS NULL
ORDER BY assessment_date DESC
`

func (q *Queries) ListAdequacyAssessmentsByPatient(ctx context.Context, patientID uuid.UUID) ([]AdequacyAssessment, error) {
	rows, err := q.db.Query(ctx, listAdequacyAssessmentsByPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdequacyAssessment
	for rows.Next() {
		var i AdequacyAssessment
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.PatientID,
			&i.SessionID,
			&i.AssessedBy,
			&i.AssessmentDate,
			&i.KtV,
			&i.KtVMethod,
			&i.UrrPercent,
			&i.PreBunMgDl,
			&i.PostBunMgDl,
			&i.PreCreatinineMgDl,
			&i.PostCreatinineMgDl,
			&i.DialysisDurationMins,
			&i.BloodFlowRate,
			&i.DialyzerClearance,
			&i.BodyWaterVolumeLiters,
			&i.IsAdequate,
			&i.Recommendations,
			&i.NextAssessmentDate,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInadequateAssessments = `-- name: ListInadequateAssessments :many
SELECT id, hospital_id, patient_id, session_id, assessed_by, assessment_date, kt_v, kt_v_method, urr_percent, pre_bun_mg_dl, post_bun_mg_dl, pre_creatinine_mg_dl, post_creatinine_mg_dl, dialysis_duration_mins, blood_flow_rate, dialyzer_clearance, body_water_volume_liters, is_adequate, recommendations, next_assessment_date, notes, created_at, updated_at, deleted_at FROM adequacy_assessments
WHERE hospital_id = $1
  AND is_adequate = FALSE
  AND deleted_at IS NULL
ORDER BY assessment_date DESC
`

func (q *Queries) ListInadequateAssessments(ctx context.Context, hospitalID uuid.UUID) ([]AdequacyAssessment, error) {
	rows, err := q.db.Query(ctx, listInadequateAssessments, hospitalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdequacyAssessment
	for rows.Next() {
		var i AdequacyAssessment
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.PatientID,
			&i.SessionID,
			&i.AssessedBy,
			&i.AssessmentDate,
			&i.KtV,
			&i.KtVMethod,
			&i.UrrPercent,
			&i.PreBunMgDl,
			&i.PostBunMgDl,
			&i.PreCreatinineMgDl,
			&i.PostCreatinineMgDl,
			&i.DialysisDurationMins,
			&i.BloodFlowRate,
			&i.DialyzerClearance,
			&i.BodyWaterVolumeLiters,
			&i.IsAdequate,
			&i.Recommendations,
			&i.NextAssessmentDate,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdequacyAssessment = `-- name: UpdateAdequacyAssessment :one
UPDATE adequacy_assessments
SET kt_v = $2, kt_v_method = $3, urr_percent = $4, pre_bun_mg_dl = $5,
    post_bun_mg_dl = $6, pre_creatinine_mg_dl = $7, post_creatinine_mg_dl = $8,
    dialysis_duration_mins = $9, blood_flow_rate = $10, dialyzer_clearance = $11,
    body_water_volume_liters = $12, is_adequate = $13, recommendations = $14,
    next_assessment_date = $15, notes = $16
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, hospital_id, patient_id, session_id, assessed_by, assessment_date, kt_v, kt_v_method, urr_percent, pre_bun_mg_dl, post_bun_mg_dl, pre_creatinine_mg_dl, post_creatinine_mg_dl, dialysis_duration_mins, blood_flow_rate, dialyzer_clearance, body_water_volume_liters, is_adequate, recommendations, next_assessment_date, notes, created_at, updated_at, deleted_at
`

type UpdateAdequacyAssessmentParams struct {
	ID                    uuid.UUID      `json:"id"`
	KtV                   pgtype.Numeric `json:"kt_v"`
	KtVMethod             pgtype.Text    `json:"kt_v_method"`
	UrrPercent            pgtype.Numeric `json:"urr_percent"`
	PreBunMgDl            pgtype.Numeric `json:"pre_bun_mg_dl"`
	PostBunMgDl           pgtype.Numeric `json:"post_bun_mg_dl"`
	PreCreatinineMgDl     pgtype.Numeric `json:"pre_creatinine_mg_dl"`
	PostCreatinineMgDl    pgtype.Numeric `json:"post_creatinine_mg_dl"`
	DialysisDurationMins  pgtype.Int4    `json:"dialysis_duration_mins"`
	BloodFlowRate         pgtype.Int4    `json:"blood_flow_rate"`
	DialyzerClearance     pgtype.Int4    `json:"dialyzer_clearance"`
	BodyWaterVolumeLiters pgtype.Numeric `json:"body_water_volume_liters"`
	IsAdequate            bool           `json:"is_adequate"`
	Recommendations       pgtype.Text    `json:"recommendations"`
	NextAssessmentDate    pgtype.Date    `json:"next_assessment_date"`
	Notes                 pgtype.Text    `json:"notes"`
}

func (q *Queries) UpdateAdequacyAssessment(ctx context.Context, arg UpdateAdequacyAssessmentParams) (AdequacyAssessment, error) {
	row := q.db.QueryRow(ctx, updateAdequacyAssessment,
		arg.ID,
		arg.KtV,
		arg.KtVMethod,
		arg.UrrPercent,
		arg.PreBunMgDl,
		arg.PostBunMgDl,
		arg.PreCreatinineMgDl,
		arg.PostCreatinineMgDl,
		arg.DialysisDurationMins,
		arg.BloodFlowRate,
		arg.DialyzerClearance,
		arg.BodyWaterVolumeLiters,
		arg.IsAdequate,
		arg.Recommendations,
		arg.NextAssessmentDate,
		arg.Notes,
	)
	var i AdequacyAssessment
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.PatientID,
		&i.SessionID,
		&i.AssessedBy,
		&i.AssessmentDate,
		&i.KtV,
		&i.KtVMethod,
		&i.UrrPercent,
		&i.PreBunMgDl,
		&i.PostBunMgDl,
		&i.PreCreatinineMgDl,
		&i.PostCreatinineMgDl,
		&i.DialysisDurationMins,
		&i.BloodFlowRate,
		&i.DialyzerClearance,
		&i.BodyWaterVolumeLiters,
		&i.IsAdequate,
		&i.Recommendations,
		&i.NextAssessmentDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
