// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admissions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAdmission = `-- name: CreateAdmission :one
INSERT INTO admissions (
    hospital_id, patient_id, admission_type, admitted_by, ward, bed_number,
    primary_diagnosis, admitting_doctor_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, hospital_id, patient_id, admission_type, admitted_at, admitted_by, ward, bed_number, primary_diagnosis, admitting_doctor_id, discharged_at, discharge_type, discharge_summary, discharged_by, created_at, updated_at, deleted_at
`

type CreateAdmissionParams struct {
	HospitalID        uuid.UUID     `json:"hospital_id"`
	PatientID         uuid.UUID     `json:"patient_id"`
	AdmissionType     AdmissionType `json:"admission_type"`
	AdmittedBy        uuid.UUID     `json:"admitted_by"`
	Ward              pgtype.Text   `json:"ward"`
	BedNumber         pgtype.Text   `json:"bed_number"`
	PrimaryDiagnosis  pgtype.Text   `json:"primary_diagnosis"`
	AdmittingDoctorID pgtype.UUID   `json:"admitting_doctor_id"`
}

func (q *Queries) CreateAdmission(ctx context.Context, arg CreateAdmissionParams) (Admission, error) {
	row := q.db.QueryRow(ctx, createAdmission,
		arg.HospitalID,
		arg.PatientID,
		arg.AdmissionType,
		arg.AdmittedBy,
		arg.Ward,
		arg.BedNumber,
		arg.PrimaryDiagnosis,
		arg.AdmittingDoctorID,
	)
	var i Admission
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.PatientID,
		&i.AdmissionType,
		&i.AdmittedAt,
		&i.AdmittedBy,
		&i.Ward,
		&i.BedNumber,
		&i.PrimaryDiagnosis,
		&i.AdmittingDoctorID,
		&i.DischargedAt,
		&i.DischargeType,
		&i.DischargeSummary,
		&i.DischargedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const dischargePatient = `-- name: DischargePatient :one
UPDATE admissions
SET discharged_at = now(), discharge_type = $2, discharge_summary = $3, discharged_by = $4
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, hospital_id, patient_id, admission_type, admitted_at, admitted_by, ward, bed_number, primary_diagnosis, admitting_doctor_id, discharged_at, discharge_type, discharge_summary, discharged_by, created_at, updated_at, deleted_at
`

type DischargePatientParams struct {
	ID               uuid.UUID         `json:"id"`
	DischargeType    NullDischargeType `json:"discharge_type"`
	DischargeSummary pgtype.Text       `json:"discharge_summary"`
	DischargedBy     pgtype.UUID       `json:"discharged_by"`
}

func (q *Queries) DischargePatient(ctx context.Context, arg DischargePatientParams) (Admission, error) {
	row := q.db.QueryRow(ctx, dischargePatient,
		arg.ID,
		arg.DischargeType,
		arg.DischargeSummary,
		arg.DischargedBy,
	)
	var i Admission
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.PatientID,
		&i.AdmissionType,
		&i.AdmittedAt,
		&i.AdmittedBy,
		&i.Ward,
		&i.BedNumber,
		&i.PrimaryDiagnosis,
		&i.AdmittingDoctorID,
		&i.DischargedAt,
		&i.DischargeType,
		&i.DischargeSummary,
		&i.DischargedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCurrentAdmission = `-- name: GetCurrentAdmission :one
SELECT id, hospital_id, patient_id, admission_type, admitted_at, admitted_by, ward, bed_number, primary_diagnosis, admitting_doctor_id, discharged_at, discharge_type, discharge_summary, discharged_by, created_at, updated_at, deleted_at FROM admissions
WHERE patient_id = $1 AND discharged_at IS NULL AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetCurrentAdmission(ctx context.Context, patientID uuid.UUID) (Admission, error) {
	row := q.db.QueryRow(ctx, getCurrentAdmission, patientID)
	var i Admission
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.PatientID,
		&i.AdmissionType,
		&i.AdmittedAt,
		&i.AdmittedBy,
		&i.Ward,
		&i.BedNumber,
		&i.PrimaryDiagnosis,
		&i.AdmittingDoctorID,
		&i.DischargedAt,
		&i.DischargeType,
		&i.DischargeSummary,
		&i.DischargedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listActiveAdmissions = `-- name: ListActiveAdmissions :many
SELECT id, hospital_id, patient_id, admission_type, admitted_at, admitted_by, ward, bed_number, primary_diagnosis, admitting_doctor_id, discharged_at, discharge_type, discharge_summary, discharged_by, created_at, updated_at, deleted_at FROM admissions
WHERE hospital_id = $1 AND discharged_at IS NULL AND deleted_at IS NULL
ORDER BY admitted_at DESC
`

func (q *Queries) ListActiveAdmissions(ctx context.Context, hospitalID uuid.UUID) ([]Admission, error) {
	rows, err := q.db.Query(ctx, listActiveAdmissions, hospitalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Admission
	for rows.Next() {
		var i Admission
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.PatientID,
			&i.AdmissionType,
			&i.AdmittedAt,
			&i.AdmittedBy,
			&i.Ward,
			&i.BedNumber,
			&i.PrimaryDiagnosis,
			&i.AdmittingDoctorID,
			&i.DischargedAt,
			&i.DischargeType,
			&i.DischargeSummary,
			&i.DischargedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
