// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: allergies.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkDrugAllergy = `-- name: CheckDrugAllergy :one
SELECT id, hospital_id, patient_id, allergen, category, reaction, severity, onset_date, notes, recorded_by, is_active, created_at, updated_at, deleted_at FROM allergies
WHERE patient_id = $1 AND category = 'drug' AND allergen ILIKE $2 AND is_active = TRUE AND deleted_at IS NULL
LIMIT 1
`

type CheckDrugAllergyParams struct {
	PatientID uuid.UUID `json:"patient_id"`
	Allergen  string    `json:"allergen"`
}

func (q *Queries) CheckDrugAllergy(ctx context.Context, arg CheckDrugAllergyParams) (Allergy, error) {
	row := q.db.QueryRow(ctx, checkDrugAllergy, arg.PatientID, arg.Allergen)
	var i Allergy
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.PatientID,
		&i.Allergen,
		&i.Category,
		&i.Reaction,
		&i.Severity,
		&i.OnsetDate,
		&i.Notes,
		&i.RecordedBy,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createAllergy = `-- name: CreateAllergy :one
INSERT INTO allergies (
    hospital_id, patient_id, allergen, category, reaction, severity, onset_date, notes, recorded_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, hospital_id, patient_id, allergen, category, reaction, severity, onset_date, notes, recorded_by, is_active, created_at, updated_at, deleted_at
`

type CreateAllergyParams struct {
	HospitalID uuid.UUID       `json:"hospital_id"`
	PatientID  uuid.UUID       `json:"patient_id"`
	Allergen   string          `json:"allergen"`
	Category   AllergyCategory `json:"category"`
	Reaction   AllergyReaction `json:"reaction"`
	Severity   SeverityLevel   `json:"severity"`
	OnsetDate  pgtype.Date     `json:"onset_date"`
	Notes      pgtype.Text     `json:"notes"`
	RecordedBy uuid.UUID       `json:"recorded_by"`
}

func (q *Queries) CreateAllergy(ctx context.Context, arg CreateAllergyParams) (Allergy, error) {
	row := q.db.QueryRow(ctx, createAllergy,
		arg.HospitalID,
		arg.PatientID,
		arg.Allergen,
		arg.Category,
		arg.Reaction,
		arg.Severity,
		arg.OnsetDate,
		arg.Notes,
		arg.RecordedBy,
	)
	var i Allergy
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.PatientID,
		&i.Allergen,
		&i.Category,
		&i.Reaction,
		&i.Severity,
		&i.OnsetDate,
		&i.Notes,
		&i.RecordedBy,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getActiveAllergies = `-- name: GetActiveAllergies :many
SELECT id, hospital_id, patient_id, allergen, category, reaction, severity, onset_date, notes, recorded_by, is_active, created_at, updated_at, deleted_at FROM allergies
WHERE patient_id = $1 AND is_active = TRUE AND deleted_at IS NULL
ORDER BY severity DESC, created_at
`

func (q *Queries) GetActiveAllergies(ctx context.Context, patientID uuid.UUID) ([]Allergy, error) {
	rows, err := q.db.Query(ctx, getActiveAllergies, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Allergy
	for rows.Next() {
		var i Allergy
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.PatientID,
			&i.Allergen,
			&i.Category,
			&i.Reaction,
			&i.Severity,
			&i.OnsetDate,
			&i.Notes,
			&i.RecordedBy,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
