// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: anticoagulation_records.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAnticoagulationRecord = `-- name: CreateAnticoagulationRecord :one
INSERT INTO anticoagulation_records (
    hospital_id, session_id, patient_id, administered_by, anticoagulant,
    route, loading_dose_units, loading_dose_time, maintenance_dose_units,
    maintenance_rate, total_dose_units, reversal_agent_given, reversal_agent,
    reversal_dose_units, reversal_time, bleeding_complications, clotting_observed,
    clotting_location, aptt_pre, aptt_post, act_pre, act_post, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23)
RETURNING id, hospital_id, session_id, patient_id, administered_by, anticoagulant, route, loading_dose_units, loading_dose_time, maintenance_dose_units, maintenance_rate, total_dose_units, reversal_agent_given, reversal_agent, reversal_dose_units, reversal_time, bleeding_complications, clotting_observed, clotting_location, aptt_pre, aptt_post, act_pre, act_post, notes, created_at, updated_at, deleted_at
`

type CreateAnticoagulationRecordParams struct {
	HospitalID            uuid.UUID          `json:"hospital_id"`
	SessionID             uuid.UUID          `json:"session_id"`
	PatientID             uuid.UUID          `json:"patient_id"`
	AdministeredBy        uuid.UUID          `json:"administered_by"`
	Anticoagulant         string             `json:"anticoagulant"`
	Route                 AnticoagRoute      `json:"route"`
	LoadingDoseUnits      pgtype.Numeric     `json:"loading_dose_units"`
	LoadingDoseTime       pgtype.Timestamptz `json:"loading_dose_time"`
	MaintenanceDoseUnits  pgtype.Numeric     `json:"maintenance_dose_units"`
	MaintenanceRate       pgtype.Text        `json:"maintenance_rate"`
	TotalDoseUnits        pgtype.Numeric     `json:"total_dose_units"`
	ReversalAgentGiven    bool               `json:"reversal_agent_given"`
	ReversalAgent         pgtype.Text        `json:"reversal_agent"`
	ReversalDoseUnits     pgtype.Numeric     `json:"reversal_dose_units"`
	ReversalTime          pgtype.Timestamptz `json:"reversal_time"`
	BleedingComplications bool               `json:"bleeding_complications"`
	ClottingObserved      bool               `json:"clotting_observed"`
	ClottingLocation      pgtype.Text        `json:"clotting_location"`
	ApttPre               pgtype.Numeric     `json:"aptt_pre"`
	ApttPost              pgtype.Numeric     `json:"aptt_post"`
	ActPre                pgtype.Int4        `json:"act_pre"`
	ActPost               pgtype.Int4        `json:"act_post"`
	Notes                 pgtype.Text        `json:"notes"`
}

func (q *Queries) CreateAnticoagulationRecord(ctx context.Context, arg CreateAnticoagulationRecordParams) (AnticoagulationRecord, error) {
	row := q.db.QueryRow(ctx, createAnticoagulationRecord,
		arg.HospitalID,
		arg.SessionID,
		arg.PatientID,
		arg.AdministeredBy,
		arg.Anticoagulant,
		arg.Route,
		arg.LoadingDoseUnits,
		arg.LoadingDoseTime,
		arg.MaintenanceDoseUnits,
		arg.MaintenanceRate,
		arg.TotalDoseUnits,
		arg.ReversalAgentGiven,
		arg.ReversalAgent,
		arg.ReversalDoseUnits,
		arg.ReversalTime,
		arg.BleedingComplications,
		arg.ClottingObserved,
		arg.ClottingLocation,
		arg.ApttPre,
		arg.ApttPost,
		arg.ActPre,
		arg.ActPost,
		arg.Notes,
	)
	var i AnticoagulationRecord
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.SessionID,
		&i.PatientID,
		&i.AdministeredBy,
		&i.Anticoagulant,
		&i.Route,
		&i.LoadingDoseUnits,
		&i.LoadingDoseTime,
		&i.MaintenanceDoseUnits,
		&i.MaintenanceRate,
		&i.TotalDoseUnits,
		&i.ReversalAgentGiven,
		&i.ReversalAgent,
		&i.ReversalDoseUnits,
		&i.ReversalTime,
		&i.BleedingComplications,
		&i.ClottingObserved,
		&i.ClottingLocation,
		&i.ApttPre,
		&i.ApttPost,
		&i.ActPre,
		&i.ActPost,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteAnticoagulationRecord = `-- name: DeleteAnticoagulationRecord :exec
UPDATE anticoagulation_records SET deleted_at = now() WHERE id = $1
`

func (q *Queries) DeleteAnticoagulationRecord(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAnticoagulationRecord, id)
	return err
}

const getAnticoagulationBySession = `-- name: GetAnticoagulationBySession :one
SELECT id, hospital_id, session_id, patient_id, administered_by, anticoagulant, route, loading_dose_units, loading_dose_time, maintenance_dose_units, maintenance_rate, total_dose_units, reversal_agent_given, reversal_agent, reversal_dose_units, reversal_time, bleeding_complications, clotting_observed, clotting_location, aptt_pre, aptt_post, act_pre, act_post, notes, created_at, updated_at, deleted_at FROM anticoagulation_records WHERE session_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAnticoagulationBySession(ctx context.Context, sessionID uuid.UUID) (AnticoagulationRecord, error) {
	row := q.db.QueryRow(ctx, getAnticoagulationBySession, sessionID)
	var i AnticoagulationRecord
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.SessionID,
		&i.PatientID,
		&i.AdministeredBy,
		&i.Anticoagulant,
		&i.Route,
		&i.LoadingDoseUnits,
		&i.LoadingDoseTime,
		&i.MaintenanceDoseUnits,
		&i.MaintenanceRate,
		&i.TotalDoseUnits,
		&i.ReversalAgentGiven,
		&i.ReversalAgent,
		&i.ReversalDoseUnits,
		&i.ReversalTime,
		&i.BleedingComplications,
		&i.ClottingObserved,
		&i.ClottingLocation,
		&i.ApttPre,
		&i.ApttPost,
		&i.ActPre,
		&i.ActPost,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAnticoagulationRecord = `-- name: GetAnticoagulationRecord :one
SELECT id, hospital_id, session_id, patient_id, administered_by, anticoagulant, route, loading_dose_units, loading_dose_time, maintenance_dose_units, maintenance_rate, total_dose_units, reversal_agent_given, reversal_agent, reversal_dose_units, reversal_time, bleeding_complications, clotting_observed, clotting_location, aptt_pre, aptt_post, act_pre, act_post, notes, created_at, updated_at, deleted_at FROM anticoagulation_records WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAnticoagulationRecord(ctx context.Context, id uuid.UUID) (AnticoagulationRecord, error) {
	row := q.db.QueryRow(ctx, getAnticoagulationRecord, id)
	var i AnticoagulationRecord
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.SessionID,
		&i.PatientID,
		&i.AdministeredBy,
		&i.Anticoagulant,
		&i.Route,
		&i.LoadingDoseUnits,
		&i.LoadingDoseTime,
		&i.MaintenanceDoseUnits,
		&i.MaintenanceRate,
		&i.TotalDoseUnits,
		&i.ReversalAgentGiven,
		&i.ReversalAgent,
		&i.ReversalDoseUnits,
		&i.ReversalTime,
		&i.BleedingComplications,
		&i.ClottingObserved,
		&i.ClottingLocation,
		&i.ApttPre,
		&i.ApttPost,
		&i.ActPre,
		&i.ActPost,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAnticoagulationRecordsByPatient = `-- name: ListAnticoagulationRecordsByPatient :many
SELECT id, hospital_id, session_id, patient_id, administered_by, anticoagulant, route, loading_dose_units, loading_dose_time, maintenance_dose_units, maintenance_rate, total_dose_units, reversal_agent_given, reversal_agent, reversal_dose_units, reversal_time, bleeding_complications, clotting_observed, clotting_location, aptt_pre, aptt_post, act_pre, act_post, notes, created_at, updated_at, deleted_at FROM anticoagulation_records
WHERE patient_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListAnticoagulationRecordsByPatient(ctx context.Context, patientID uuid.UUID) ([]AnticoagulationRecord, error) {
	rows, err := q.db.Query(ctx, listAnticoagulationRecordsByPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnticoagulationRecord
	for rows.Next() {
		var i AnticoagulationRecord
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.SessionID,
			&i.PatientID,
			&i.AdministeredBy,
			&i.Anticoagulant,
			&i.Route,
			&i.LoadingDoseUnits,
			&i.LoadingDoseTime,
			&i.MaintenanceDoseUnits,
			&i.MaintenanceRate,
			&i.TotalDoseUnits,
			&i.ReversalAgentGiven,
			&i.ReversalAgent,
			&i.ReversalDoseUnits,
			&i.ReversalTime,
			&i.BleedingComplications,
			&i.ClottingObserved,
			&i.ClottingLocation,
			&i.ApttPre,
			&i.ApttPost,
			&i.ActPre,
			&i.ActPost,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordsWithComplications = `-- name: ListRecordsWithComplications :many
SELECT id, hospital_id, session_id, patient_id, administered_by, anticoagulant, route, loading_dose_units, loading_dose_time, maintenance_dose_units, maintenance_rate, total_dose_units, reversal_agent_given, reversal_agent, reversal_dose_units, reversal_time, bleeding_complications, clotting_observed, clotting_location, aptt_pre, aptt_post, act_pre, act_post, notes, created_at, updated_at, deleted_at FROM anticoagulation_records
WHERE hospital_id = $1
  AND (bleeding_complications = TRUE OR clotting_observed = TRUE)
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListRecordsWithComplications(ctx context.Context, hospitalID uuid.UUID) ([]AnticoagulationRecord, error) {
	rows, err := q.db.Query(ctx, listRecordsWithComplications, hospitalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnticoagulationRecord
	for rows.Next() {
		var i AnticoagulationRecord
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.SessionID,
			&i.PatientID,
			&i.AdministeredBy,
			&i.Anticoagulant,
			&i.Route,
			&i.LoadingDoseUnits,
			&i.LoadingDoseTime,
			&i.MaintenanceDoseUnits,
			&i.MaintenanceRate,
			&i.TotalDoseUnits,
			&i.ReversalAgentGiven,
			&i.ReversalAgent,
			&i.ReversalDoseUnits,
			&i.ReversalTime,
			&i.BleedingComplications,
			&i.ClottingObserved,
			&i.ClottingLocation,
			&i.ApttPre,
			&i.ApttPost,
			&i.ActPre,
			&i.ActPost,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnticoagulationRecord = `-- name: UpdateAnticoagulationRecord :one
UPDATE anticoagulation_records
SET loading_dose_units = $2, loading_dose_time = $3, maintenance_dose_units = $4,
    maintenance_rate = $5, total_dose_units = $6, reversal_agent_given = $7,
    reversal_agent = $8, reversal_dose_units = $9, reversal_time = $10,
    bleeding_complications = $11, clotting_observed = $12, clotting_location = $13,
    aptt_pre = $14, aptt_post = $15, act_pre = $16, act_post = $17, notes = $18
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, hospital_id, session_id, patient_id, administered_by, anticoagulant, route, loading_dose_units, loading_dose_time, maintenance_dose_units, maintenance_rate, total_dose_units, reversal_agent_given, reversal_agent, reversal_dose_units, reversal_time, bleeding_complications, clotting_observed, clotting_location, aptt_pre, aptt_post, act_pre, act_post, notes, created_at, updated_at, deleted_at
`

type UpdateAnticoagulationRecordParams struct {
	ID                    uuid.UUID          `json:"id"`
	LoadingDoseUnits      pgtype.Numeric     `json:"loading_dose_units"`
	LoadingDoseTime       pgtype.Timestamptz `json:"loading_dose_time"`
	MaintenanceDoseUnits  pgtype.Numeric     `json:"maintenance_dose_units"`
	MaintenanceRate       pgtype.Text        `json:"maintenance_rate"`
	TotalDoseUnits        pgtype.Numeric     `json:"total_dose_units"`
	ReversalAgentGiven    bool               `json:"reversal_agent_given"`
	ReversalAgent         pgtype.Text        `json:"reversal_agent"`
	ReversalDoseUnits     pgtype.Numeric     `json:"reversal_dose_units"`
	ReversalTime          pgtype.Timestamptz `json:"reversal_time"`
	BleedingComplications bool               `json:"bleeding_complications"`
	ClottingObserved      bool               `json:"clotting_observed"`
	ClottingLocation      pgtype.Text        `json:"clotting_location"`
	ApttPre               pgtype.Numeric     `json:"aptt_pre"`
	ApttPost              pgtype.Numeric     `json:"aptt_post"`
	ActPre                pgtype.Int4        `json:"act_pre"`
	ActPost               pgtype.Int4        `json:"act_post"`
	Notes                 pgtype.Text        `json:"notes"`
}

func (q *Queries) UpdateAnticoagulationRecord(ctx context.Context, arg UpdateAnticoagulationRecordParams) (AnticoagulationRecord, error) {
	row := q.db.QueryRow(ctx, updateAnticoagulationRecord,
		arg.ID,
		arg.LoadingDoseUnits,
		arg.LoadingDoseTime,
		arg.MaintenanceDoseUnits,
		arg.MaintenanceRate,
		arg.TotalDoseUnits,
		arg.ReversalAgentGiven,
		arg.ReversalAgent,
		arg.ReversalDoseUnits,
		arg.ReversalTime,
		arg.BleedingComplications,
		arg.ClottingObserved,
		arg.ClottingLocation,
		arg.ApttPre,
		arg.ApttPost,
		arg.ActPre,
		arg.ActPost,
		arg.Notes,
	)
	var i AnticoagulationRecord
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.SessionID,
		&i.PatientID,
		&i.AdministeredBy,
		&i.Anticoagulant,
		&i.Route,
		&i.LoadingDoseUnits,
		&i.LoadingDoseTime,
		&i.MaintenanceDoseUnits,
		&i.MaintenanceRate,
		&i.TotalDoseUnits,
		&i.ReversalAgentGiven,
		&i.ReversalAgent,
		&i.ReversalDoseUnits,
		&i.ReversalTime,
		&i.BleedingComplications,
		&i.ClottingObserved,
		&i.ClottingLocation,
		&i.ApttPre,
		&i.ApttPost,
		&i.ActPre,
		&i.ActPost,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
