// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_sessions.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupExpiredSessions = `-- name: CleanupExpiredSessions :exec
UPDATE auth_sessions
SET deleted_at = now()
WHERE expires_at < now() - INTERVAL '30 days' AND deleted_at IS NULL
`

func (q *Queries) CleanupExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredSessions)
	return err
}

const createAuthSession = `-- name: CreateAuthSession :one
INSERT INTO auth_sessions (
  hospital_id, user_id, token_hash, device_info, ip_address, expires_at
) VALUES (
  $1, $2, $3, $4, $5, $6
) RETURNING id, hospital_id, user_id, token_hash, device_info, ip_address, expires_at, revoked_at, created_at, updated_at, deleted_at
`

type CreateAuthSessionParams struct {
	HospitalID uuid.UUID          `json:"hospital_id"`
	UserID     uuid.UUID          `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	DeviceInfo []byte             `json:"device_info"`
	IpAddress  *netip.Addr        `json:"ip_address"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, createAuthSession,
		arg.HospitalID,
		arg.UserID,
		arg.TokenHash,
		arg.DeviceInfo,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.UserID,
		&i.TokenHash,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAuthSession = `-- name: GetAuthSession :one
SELECT id, hospital_id, user_id, token_hash, device_info, ip_address, expires_at, revoked_at, created_at, updated_at, deleted_at FROM auth_sessions
WHERE token_hash = $1 AND expires_at > now() AND revoked_at IS NULL AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetAuthSession(ctx context.Context, tokenHash string) (AuthSession, error) {
	row := q.db.QueryRow(ctx, getAuthSession, tokenHash)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.UserID,
		&i.TokenHash,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listUserSessions = `-- name: ListUserSessions :many
SELECT id, hospital_id, user_id, token_hash, device_info, ip_address, expires_at, revoked_at, created_at, updated_at, deleted_at FROM auth_sessions
WHERE user_id = $1 AND expires_at > now() AND revoked_at IS NULL AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListUserSessions(ctx context.Context, userID uuid.UUID) ([]AuthSession, error) {
	rows, err := q.db.Query(ctx, listUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthSession
	for rows.Next() {
		var i AuthSession
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.UserID,
			&i.TokenHash,
			&i.DeviceInfo,
			&i.IpAddress,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE auth_sessions
SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE auth_sessions
SET revoked_at = now()
WHERE token_hash = $1
`

func (q *Queries) RevokeSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeSession, tokenHash)
	return err
}
