// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: billing_accounts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBillingAccount = `-- name: CreateBillingAccount :one
INSERT INTO billing_accounts (
    hospital_id, patient_id, guarantor_id, account_number,
    account_status, credit_limit, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, hospital_id, patient_id, guarantor_id, account_number, account_status, credit_limit, current_balance, total_billed, total_paid, notes, created_at, updated_at, deleted_at
`

type CreateBillingAccountParams struct {
	HospitalID    uuid.UUID      `json:"hospital_id"`
	PatientID     uuid.UUID      `json:"patient_id"`
	GuarantorID   pgtype.UUID    `json:"guarantor_id"`
	AccountNumber string         `json:"account_number"`
	AccountStatus AccountStatus  `json:"account_status"`
	CreditLimit   pgtype.Numeric `json:"credit_limit"`
	Notes         pgtype.Text    `json:"notes"`
}

func (q *Queries) CreateBillingAccount(ctx context.Context, arg CreateBillingAccountParams) (BillingAccount, error) {
	row := q.db.QueryRow(ctx, createBillingAccount,
		arg.HospitalID,
		arg.PatientID,
		arg.GuarantorID,
		arg.AccountNumber,
		arg.AccountStatus,
		arg.CreditLimit,
		arg.Notes,
	)
	var i BillingAccount
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.PatientID,
		&i.GuarantorID,
		&i.AccountNumber,
		&i.AccountStatus,
		&i.CreditLimit,
		&i.CurrentBalance,
		&i.TotalBilled,
		&i.TotalPaid,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteBillingAccount = `-- name: DeleteBillingAccount :exec
UPDATE billing_accounts SET deleted_at = now() WHERE id = $1
`

func (q *Queries) DeleteBillingAccount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBillingAccount, id)
	return err
}

const getBillingAccount = `-- name: GetBillingAccount :one
SELECT id, hospital_id, patient_id, guarantor_id, account_number, account_status, credit_limit, current_balance, total_billed, total_paid, notes, created_at, updated_at, deleted_at FROM billing_accounts WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetBillingAccount(ctx context.Context, id uuid.UUID) (BillingAccount, error) {
	row := q.db.QueryRow(ctx, getBillingAccount, id)
	var i BillingAccount
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.PatientID,
		&i.GuarantorID,
		&i.AccountNumber,
		&i.AccountStatus,
		&i.CreditLimit,
		&i.CurrentBalance,
		&i.TotalBilled,
		&i.TotalPaid,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBillingAccountByPatient = `-- name: GetBillingAccountByPatient :one
SELECT id, hospital_id, patient_id, guarantor_id, account_number, account_status, credit_limit, current_balance, total_billed, total_paid, notes, created_at, updated_at, deleted_at FROM billing_accounts
WHERE hospital_id = $1 AND patient_id = $2 AND deleted_at IS NULL
LIMIT 1
`

type GetBillingAccountByPatientParams struct {
	HospitalID uuid.UUID `json:"hospital_id"`
	PatientID  uuid.UUID `json:"patient_id"`
}

func (q *Queries) GetBillingAccountByPatient(ctx context.Context, arg GetBillingAccountByPatientParams) (BillingAccount, error) {
	row := q.db.QueryRow(ctx, getBillingAccountByPatient, arg.HospitalID, arg.PatientID)
	var i BillingAccount
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.PatientID,
		&i.GuarantorID,
		&i.AccountNumber,
		&i.AccountStatus,
		&i.CreditLimit,
		&i.CurrentBalance,
		&i.TotalBilled,
		&i.TotalPaid,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAccountsByStatus = `-- name: ListAccountsByStatus :many
SELECT id, hospital_id, patient_id, guarantor_id, account_number, account_status, credit_limit, current_balance, total_billed, total_paid, notes, created_at, updated_at, deleted_at FROM billing_accounts
WHERE hospital_id = $1 AND account_status = $2 AND deleted_at IS NULL
ORDER BY current_balance DESC
`

type ListAccountsByStatusParams struct {
	HospitalID    uuid.UUID     `json:"hospital_id"`
	AccountStatus AccountStatus `json:"account_status"`
}

func (q *Queries) ListAccountsByStatus(ctx context.Context, arg ListAccountsByStatusParams) ([]BillingAccount, error) {
	rows, err := q.db.Query(ctx, listAccountsByStatus, arg.HospitalID, arg.AccountStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BillingAccount
	for rows.Next() {
		var i BillingAccount
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.PatientID,
			&i.GuarantorID,
			&i.AccountNumber,
			&i.AccountStatus,
			&i.CreditLimit,
			&i.CurrentBalance,
			&i.TotalBilled,
			&i.TotalPaid,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBillingAccountsByHospital = `-- name: ListBillingAccountsByHospital :many
SELECT id, hospital_id, patient_id, guarantor_id, account_number, account_status, credit_limit, current_balance, total_billed, total_paid, notes, created_at, updated_at, deleted_at FROM billing_accounts
WHERE hospital_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListBillingAccountsByHospital(ctx context.Context, hospitalID uuid.UUID) ([]BillingAccount, error) {
	rows, err := q.db.Query(ctx, listBillingAccountsByHospital, hospitalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BillingAccount
	for rows.Next() {
		var i BillingAccount
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.PatientID,
			&i.GuarantorID,
			&i.AccountNumber,
			&i.AccountStatus,
			&i.CreditLimit,
			&i.CurrentBalance,
			&i.TotalBilled,
			&i.TotalPaid,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountBalance = `-- name: UpdateAccountBalance :one
UPDATE billing_accounts
SET current_balance = $2, total_billed = $3, total_paid = $4
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, hospital_id, patient_id, guarantor_id, account_number, account_status, credit_limit, current_balance, total_billed, total_paid, notes, created_at, updated_at, deleted_at
`

type UpdateAccountBalanceParams struct {
	ID             uuid.UUID      `json:"id"`
	CurrentBalance pgtype.Numeric `json:"current_balance"`
	TotalBilled    pgtype.Numeric `json:"total_billed"`
	TotalPaid      pgtype.Numeric `json:"total_paid"`
}

func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (BillingAccount, error) {
	row := q.db.QueryRow(ctx, updateAccountBalance,
		arg.ID,
		arg.CurrentBalance,
		arg.TotalBilled,
		arg.TotalPaid,
	)
	var i BillingAccount
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.PatientID,
		&i.GuarantorID,
		&i.AccountNumber,
		&i.AccountStatus,
		&i.CreditLimit,
		&i.CurrentBalance,
		&i.TotalBilled,
		&i.TotalPaid,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateAccountStatus = `-- name: UpdateAccountStatus :one
UPDATE billing_accounts
SET account_status = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, hospital_id, patient_id, guarantor_id, account_number, account_status, credit_limit, current_balance, total_billed, total_paid, notes, created_at, updated_at, deleted_at
`

type UpdateAccountStatusParams struct {
	ID            uuid.UUID     `json:"id"`
	AccountStatus AccountStatus `json:"account_status"`
}

func (q *Queries) UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) (BillingAccount, error) {
	row := q.db.QueryRow(ctx, updateAccountStatus, arg.ID, arg.AccountStatus)
	var i BillingAccount
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.PatientID,
		&i.GuarantorID,
		&i.AccountNumber,
		&i.AccountStatus,
		&i.CreditLimit,
		&i.CurrentBalance,
		&i.TotalBilled,
		&i.TotalPaid,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
