// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clinical_outcomes.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createClinicalOutcome = `-- name: CreateClinicalOutcome :one
INSERT INTO clinical_outcomes (
    hospital_id, patient_id, assessment_date, period_start, period_end,
    hemoglobin, hemoglobin_target_min, hemoglobin_target_max, kt_v, kt_v_target,
    urr, systolic_bp_avg, diastolic_bp_avg, bp_controlled, weight_gain_percent,
    albumin, phosphate, calcium, pth, quality_of_life_score, functional_status,
    adverse_events_count, hospitalizations_count, missed_sessions_count,
    outcome_trend, assessed_by, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27)
RETURNING id, hospital_id, patient_id, assessment_date, period_start, period_end, hemoglobin, hemoglobin_target_min, hemoglobin_target_max, kt_v, kt_v_target, urr, systolic_bp_avg, diastolic_bp_avg, bp_controlled, weight_gain_percent, albumin, phosphate, calcium, pth, quality_of_life_score, functional_status, adverse_events_count, hospitalizations_count, missed_sessions_count, outcome_trend, assessed_by, notes, created_at, updated_at, deleted_at
`

type CreateClinicalOutcomeParams struct {
	HospitalID            uuid.UUID        `json:"hospital_id"`
	PatientID             uuid.UUID        `json:"patient_id"`
	AssessmentDate        pgtype.Date      `json:"assessment_date"`
	PeriodStart           pgtype.Date      `json:"period_start"`
	PeriodEnd             pgtype.Date      `json:"period_end"`
	Hemoglobin            pgtype.Numeric   `json:"hemoglobin"`
	HemoglobinTargetMin   pgtype.Numeric   `json:"hemoglobin_target_min"`
	HemoglobinTargetMax   pgtype.Numeric   `json:"hemoglobin_target_max"`
	KtV                   pgtype.Numeric   `json:"kt_v"`
	KtVTarget             pgtype.Numeric   `json:"kt_v_target"`
	Urr                   pgtype.Numeric   `json:"urr"`
	SystolicBpAvg         pgtype.Numeric   `json:"systolic_bp_avg"`
	DiastolicBpAvg        pgtype.Numeric   `json:"diastolic_bp_avg"`
	BpControlled          pgtype.Bool      `json:"bp_controlled"`
	WeightGainPercent     pgtype.Numeric   `json:"weight_gain_percent"`
	Albumin               pgtype.Numeric   `json:"albumin"`
	Phosphate             pgtype.Numeric   `json:"phosphate"`
	Calcium               pgtype.Numeric   `json:"calcium"`
	Pth                   pgtype.Numeric   `json:"pth"`
	QualityOfLifeScore    pgtype.Numeric   `json:"quality_of_life_score"`
	FunctionalStatus      pgtype.Text      `json:"functional_status"`
	AdverseEventsCount    int32            `json:"adverse_events_count"`
	HospitalizationsCount int32            `json:"hospitalizations_count"`
	MissedSessionsCount   int32            `json:"missed_sessions_count"`
	OutcomeTrend          NullOutcomeTrend `json:"outcome_trend"`
	AssessedBy            pgtype.UUID      `json:"assessed_by"`
	Notes                 pgtype.Text      `json:"notes"`
}

func (q *Queries) CreateClinicalOutcome(ctx context.Context, arg CreateClinicalOutcomeParams) (ClinicalOutcome, error) {
	row := q.db.QueryRow(ctx, createClinicalOutcome,
		arg.HospitalID,
		arg.PatientID,
		arg.AssessmentDate,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Hemoglobin,
		arg.HemoglobinTargetMin,
		arg.HemoglobinTargetMax,
		arg.KtV,
		arg.KtVTarget,
		arg.Urr,
		arg.SystolicBpAvg,
		arg.DiastolicBpAvg,
		arg.BpControlled,
		arg.WeightGainPercent,
		arg.Albumin,
		arg.Phosphate,
		arg.Calcium,
		arg.Pth,
		arg.QualityOfLifeScore,
		arg.FunctionalStatus,
		arg.AdverseEventsCount,
		arg.HospitalizationsCount,
		arg.MissedSessionsCount,
		arg.OutcomeTrend,
		arg.AssessedBy,
		arg.Notes,
	)
	var i ClinicalOutcome
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.PatientID,
		&i.AssessmentDate,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Hemoglobin,
		&i.HemoglobinTargetMin,
		&i.HemoglobinTargetMax,
		&i.KtV,
		&i.KtVTarget,
		&i.Urr,
		&i.SystolicBpAvg,
		&i.DiastolicBpAvg,
		&i.BpControlled,
		&i.WeightGainPercent,
		&i.Albumin,
		&i.Phosphate,
		&i.Calcium,
		&i.Pth,
		&i.QualityOfLifeScore,
		&i.FunctionalStatus,
		&i.AdverseEventsCount,
		&i.HospitalizationsCount,
		&i.MissedSessionsCount,
		&i.OutcomeTrend,
		&i.AssessedBy,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteClinicalOutcome = `-- name: DeleteClinicalOutcome :exec
UPDATE clinical_outcomes SET deleted_at = now() WHERE id = $1
`

func (q *Queries) DeleteClinicalOutcome(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteClinicalOutcome, id)
	return err
}

const getClinicalOutcome = `-- name: GetClinicalOutcome :one
SELECT id, hospital_id, patient_id, assessment_date, period_start, period_end, hemoglobin, hemoglobin_target_min, hemoglobin_target_max, kt_v, kt_v_target, urr, systolic_bp_avg, diastolic_bp_avg, bp_controlled, weight_gain_percent, albumin, phosphate, calcium, pth, quality_of_life_score, functional_status, adverse_events_count, hospitalizations_count, missed_sessions_count, outcome_trend, assessed_by, notes, created_at, updated_at, deleted_at FROM clinical_outcomes WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetClinicalOutcome(ctx context.Context, id uuid.UUID) (ClinicalOutcome, error) {
	row := q.db.QueryRow(ctx, getClinicalOutcome, id)
	var i ClinicalOutcome
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.PatientID,
		&i.AssessmentDate,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Hemoglobin,
		&i.HemoglobinTargetMin,
		&i.HemoglobinTargetMax,
		&i.KtV,
		&i.KtVTarget,
		&i.Urr,
		&i.SystolicBpAvg,
		&i.DiastolicBpAvg,
		&i.BpControlled,
		&i.WeightGainPercent,
		&i.Albumin,
		&i.Phosphate,
		&i.Calcium,
		&i.Pth,
		&i.QualityOfLifeScore,
		&i.FunctionalStatus,
		&i.AdverseEventsCount,
		&i.HospitalizationsCount,
		&i.MissedSessionsCount,
		&i.OutcomeTrend,
		&i.AssessedBy,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLatestOutcome = `-- name: GetLatestOutcome :one
SELECT id, hospital_id, patient_id, assessment_date, period_start, period_end, hemoglobin, hemoglobin_target_min, hemoglobin_target_max, kt_v, kt_v_target, urr, systolic_bp_avg, diastolic_bp_avg, bp_controlled, weight_gain_percent, albumin, phosphate, calcium, pth, quality_of_life_score, functional_status, adverse_events_count, hospitalizations_count, missed_sessions_count, outcome_trend, assessed_by, notes, created_at, updated_at, deleted_at FROM clinical_outcomes
WHERE patient_id = $1 AND deleted_at IS NULL
ORDER BY assessment_date DESC
LIMIT 1
`

func (q *Queries) GetLatestOutcome(ctx context.Context, patientID uuid.UUID) (ClinicalOutcome, error) {
	row := q.db.QueryRow(ctx, getLatestOutcome, patientID)
	var i ClinicalOutcome
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.PatientID,
		&i.AssessmentDate,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Hemoglobin,
		&i.HemoglobinTargetMin,
		&i.HemoglobinTargetMax,
		&i.KtV,
		&i.KtVTarget,
		&i.Urr,
		&i.SystolicBpAvg,
		&i.DiastolicBpAvg,
		&i.BpControlled,
		&i.WeightGainPercent,
		&i.Albumin,
		&i.Phosphate,
		&i.Calcium,
		&i.Pth,
		&i.QualityOfLifeScore,
		&i.FunctionalStatus,
		&i.AdverseEventsCount,
		&i.HospitalizationsCount,
		&i.MissedSessionsCount,
		&i.OutcomeTrend,
		&i.AssessedBy,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listDecliningPatients = `-- name: ListDecliningPatients :many
SELECT id, hospital_id, patient_id, assessment_date, period_start, period_end, hemoglobin, hemoglobin_target_min, hemoglobin_target_max, kt_v, kt_v_target, urr, systolic_bp_avg, diastolic_bp_avg, bp_controlled, weight_gain_percent, albumin, phosphate, calcium, pth, quality_of_life_score, functional_status, adverse_events_count, hospitalizations_count, missed_sessions_count, outcome_trend, assessed_by, notes, created_at, updated_at, deleted_at FROM clinical_outcomes
WHERE hospital_id = $1
  AND outcome_trend IN ('declining', 'critical')
  AND assessment_date >= $2
  AND deleted_at IS NULL
ORDER BY outcome_trend DESC, assessment_date DESC
`

type ListDecliningPatientsParams struct {
	HospitalID     uuid.UUID   `json:"hospital_id"`
	AssessmentDate pgtype.Date `json:"assessment_date"`
}

func (q *Queries) ListDecliningPatients(ctx context.Context, arg ListDecliningPatientsParams) ([]ClinicalOutcome, error) {
	rows, err := q.db.Query(ctx, listDecliningPatients, arg.HospitalID, arg.AssessmentDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClinicalOutcome
	for rows.Next() {
		var i ClinicalOutcome
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.PatientID,
			&i.AssessmentDate,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Hemoglobin,
			&i.HemoglobinTargetMin,
			&i.HemoglobinTargetMax,
			&i.KtV,
			&i.KtVTarget,
			&i.Urr,
			&i.SystolicBpAvg,
			&i.DiastolicBpAvg,
			&i.BpControlled,
			&i.WeightGainPercent,
			&i.Albumin,
			&i.Phosphate,
			&i.Calcium,
			&i.Pth,
			&i.QualityOfLifeScore,
			&i.FunctionalStatus,
			&i.AdverseEventsCount,
			&i.HospitalizationsCount,
			&i.MissedSessionsCount,
			&i.OutcomeTrend,
			&i.AssessedBy,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutcomesByPatient = `-- name: ListOutcomesByPatient :many
SELECT id, hospital_id, patient_id, assessment_date, period_start, period_end, hemoglobin, hemoglobin_target_min, hemoglobin_target_max, kt_v, kt_v_target, urr, systolic_bp_avg, diastolic_bp_avg, bp_controlled, weight_gain_percent, albumin, phosphate, calcium, pth, quality_of_life_score, functional_status, adverse_events_count, hospitalizations_count, missed_sessions_count, outcome_trend, assessed_by, notes, created_at, updated_at, deleted_at FROM clinical_outcomes
WHERE patient_id = $1 AND deleted_at IS NULL
ORDER BY assessment_date DESC
`

func (q *Queries) ListOutcomesByPatient(ctx context.Context, patientID uuid.UUID) ([]ClinicalOutcome, error) {
	rows, err := q.db.Query(ctx, listOutcomesByPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClinicalOutcome
	for rows.Next() {
		var i ClinicalOutcome
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.PatientID,
			&i.AssessmentDate,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Hemoglobin,
			&i.HemoglobinTargetMin,
			&i.HemoglobinTargetMax,
			&i.KtV,
			&i.KtVTarget,
			&i.Urr,
			&i.SystolicBpAvg,
			&i.DiastolicBpAvg,
			&i.BpControlled,
			&i.WeightGainPercent,
			&i.Albumin,
			&i.Phosphate,
			&i.Calcium,
			&i.Pth,
			&i.QualityOfLifeScore,
			&i.FunctionalStatus,
			&i.AdverseEventsCount,
			&i.HospitalizationsCount,
			&i.MissedSessionsCount,
			&i.OutcomeTrend,
			&i.AssessedBy,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutcomesByTrend = `-- name: ListOutcomesByTrend :many
SELECT id, hospital_id, patient_id, assessment_date, period_start, period_end, hemoglobin, hemoglobin_target_min, hemoglobin_target_max, kt_v, kt_v_target, urr, systolic_bp_avg, diastolic_bp_avg, bp_controlled, weight_gain_percent, albumin, phosphate, calcium, pth, quality_of_life_score, functional_status, adverse_events_count, hospitalizations_count, missed_sessions_count, outcome_trend, assessed_by, notes, created_at, updated_at, deleted_at FROM clinical_outcomes
WHERE hospital_id = $1 AND outcome_trend = $2 AND deleted_at IS NULL
ORDER BY assessment_date DESC
`

type ListOutcomesByTrendParams struct {
	HospitalID   uuid.UUID        `json:"hospital_id"`
	OutcomeTrend NullOutcomeTrend `json:"outcome_trend"`
}

func (q *Queries) ListOutcomesByTrend(ctx context.Context, arg ListOutcomesByTrendParams) ([]ClinicalOutcome, error) {
	rows, err := q.db.Query(ctx, listOutcomesByTrend, arg.HospitalID, arg.OutcomeTrend)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClinicalOutcome
	for rows.Next() {
		var i ClinicalOutcome
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.PatientID,
			&i.AssessmentDate,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Hemoglobin,
			&i.HemoglobinTargetMin,
			&i.HemoglobinTargetMax,
			&i.KtV,
			&i.KtVTarget,
			&i.Urr,
			&i.SystolicBpAvg,
			&i.DiastolicBpAvg,
			&i.BpControlled,
			&i.WeightGainPercent,
			&i.Albumin,
			&i.Phosphate,
			&i.Calcium,
			&i.Pth,
			&i.QualityOfLifeScore,
			&i.FunctionalStatus,
			&i.AdverseEventsCount,
			&i.HospitalizationsCount,
			&i.MissedSessionsCount,
			&i.OutcomeTrend,
			&i.AssessedBy,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
