// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: consumables_inventory.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createConsumablesInventory = `-- name: CreateConsumablesInventory :one
INSERT INTO consumables_inventory (
    hospital_id, consumable_id, batch_number, quantity_current,
    quantity_reserved, quantity_available, unit_cost, expiry_date,
    received_date, supplier_name, storage_location, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, hospital_id, consumable_id, batch_number, quantity_current, quantity_reserved, quantity_available, unit_cost, expiry_date, received_date, supplier_name, storage_location, is_low_stock, notes, created_at, updated_at, deleted_at
`

type CreateConsumablesInventoryParams struct {
	HospitalID        uuid.UUID      `json:"hospital_id"`
	ConsumableID      uuid.UUID      `json:"consumable_id"`
	BatchNumber       pgtype.Text    `json:"batch_number"`
	QuantityCurrent   int32          `json:"quantity_current"`
	QuantityReserved  int32          `json:"quantity_reserved"`
	QuantityAvailable int32          `json:"quantity_available"`
	UnitCost          pgtype.Numeric `json:"unit_cost"`
	ExpiryDate        pgtype.Date    `json:"expiry_date"`
	ReceivedDate      pgtype.Date    `json:"received_date"`
	SupplierName      pgtype.Text    `json:"supplier_name"`
	StorageLocation   pgtype.Text    `json:"storage_location"`
	Notes             pgtype.Text    `json:"notes"`
}

func (q *Queries) CreateConsumablesInventory(ctx context.Context, arg CreateConsumablesInventoryParams) (ConsumablesInventory, error) {
	row := q.db.QueryRow(ctx, createConsumablesInventory,
		arg.HospitalID,
		arg.ConsumableID,
		arg.BatchNumber,
		arg.QuantityCurrent,
		arg.QuantityReserved,
		arg.QuantityAvailable,
		arg.UnitCost,
		arg.ExpiryDate,
		arg.ReceivedDate,
		arg.SupplierName,
		arg.StorageLocation,
		arg.Notes,
	)
	var i ConsumablesInventory
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.ConsumableID,
		&i.BatchNumber,
		&i.QuantityCurrent,
		&i.QuantityReserved,
		&i.QuantityAvailable,
		&i.UnitCost,
		&i.ExpiryDate,
		&i.ReceivedDate,
		&i.SupplierName,
		&i.StorageLocation,
		&i.IsLowStock,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteConsumablesInventory = `-- name: DeleteConsumablesInventory :exec
UPDATE consumables_inventory SET deleted_at = now() WHERE id = $1
`

func (q *Queries) DeleteConsumablesInventory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteConsumablesInventory, id)
	return err
}

const getConsumablesInventory = `-- name: GetConsumablesInventory :one
SELECT id, hospital_id, consumable_id, batch_number, quantity_current, quantity_reserved, quantity_available, unit_cost, expiry_date, received_date, supplier_name, storage_location, is_low_stock, notes, created_at, updated_at, deleted_at FROM consumables_inventory WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetConsumablesInventory(ctx context.Context, id uuid.UUID) (ConsumablesInventory, error) {
	row := q.db.QueryRow(ctx, getConsumablesInventory, id)
	var i ConsumablesInventory
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.ConsumableID,
		&i.BatchNumber,
		&i.QuantityCurrent,
		&i.QuantityReserved,
		&i.QuantityAvailable,
		&i.UnitCost,
		&i.ExpiryDate,
		&i.ReceivedDate,
		&i.SupplierName,
		&i.StorageLocation,
		&i.IsLowStock,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listExpiringInventory = `-- name: ListExpiringInventory :many
SELECT i.id, i.hospital_id, i.consumable_id, i.batch_number, i.quantity_current, i.quantity_reserved, i.quantity_available, i.unit_cost, i.expiry_date, i.received_date, i.supplier_name, i.storage_location, i.is_low_stock, i.notes, i.created_at, i.updated_at, i.deleted_at, c.name AS consumable_name
FROM consumables_inventory i
JOIN consumables c ON i.consumable_id = c.id
WHERE i.hospital_id = $1
  AND i.expiry_date <= $2
  AND i.quantity_current > 0
  AND i.deleted_at IS NULL
ORDER BY i.expiry_date ASC
`

type ListExpiringInventoryParams struct {
	HospitalID uuid.UUID   `json:"hospital_id"`
	ExpiryDate pgtype.Date `json:"expiry_date"`
}

type ListExpiringInventoryRow struct {
	ID                uuid.UUID          `json:"id"`
	HospitalID        uuid.UUID          `json:"hospital_id"`
	ConsumableID      uuid.UUID          `json:"consumable_id"`
	BatchNumber       pgtype.Text        `json:"batch_number"`
	QuantityCurrent   int32              `json:"quantity_current"`
	QuantityReserved  int32              `json:"quantity_reserved"`
	QuantityAvailable int32              `json:"quantity_available"`
	UnitCost          pgtype.Numeric     `json:"unit_cost"`
	ExpiryDate        pgtype.Date        `json:"expiry_date"`
	ReceivedDate      pgtype.Date        `json:"received_date"`
	SupplierName      pgtype.Text        `json:"supplier_name"`
	StorageLocation   pgtype.Text        `json:"storage_location"`
	IsLowStock        bool               `json:"is_low_stock"`
	Notes             pgtype.Text        `json:"notes"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	ConsumableName    string             `json:"consumable_name"`
}

func (q *Queries) ListExpiringInventory(ctx context.Context, arg ListExpiringInventoryParams) ([]ListExpiringInventoryRow, error) {
	rows, err := q.db.Query(ctx, listExpiringInventory, arg.HospitalID, arg.ExpiryDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpiringInventoryRow
	for rows.Next() {
		var i ListExpiringInventoryRow
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.ConsumableID,
			&i.BatchNumber,
			&i.QuantityCurrent,
			&i.QuantityReserved,
			&i.QuantityAvailable,
			&i.UnitCost,
			&i.ExpiryDate,
			&i.ReceivedDate,
			&i.SupplierName,
			&i.StorageLocation,
			&i.IsLowStock,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ConsumableName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInventoryByConsumable = `-- name: ListInventoryByConsumable :many
SELECT id, hospital_id, consumable_id, batch_number, quantity_current, quantity_reserved, quantity_available, unit_cost, expiry_date, received_date, supplier_name, storage_location, is_low_stock, notes, created_at, updated_at, deleted_at FROM consumables_inventory
WHERE consumable_id = $1 AND deleted_at IS NULL
ORDER BY expiry_date ASC NULLS LAST
`

func (q *Queries) ListInventoryByConsumable(ctx context.Context, consumableID uuid.UUID) ([]ConsumablesInventory, error) {
	rows, err := q.db.Query(ctx, listInventoryByConsumable, consumableID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConsumablesInventory
	for rows.Next() {
		var i ConsumablesInventory
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.ConsumableID,
			&i.BatchNumber,
			&i.QuantityCurrent,
			&i.QuantityReserved,
			&i.QuantityAvailable,
			&i.UnitCost,
			&i.ExpiryDate,
			&i.ReceivedDate,
			&i.SupplierName,
			&i.StorageLocation,
			&i.IsLowStock,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLowStockInventory = `-- name: ListLowStockInventory :many
SELECT i.id, i.hospital_id, i.consumable_id, i.batch_number, i.quantity_current, i.quantity_reserved, i.quantity_available, i.unit_cost, i.expiry_date, i.received_date, i.supplier_name, i.storage_location, i.is_low_stock, i.notes, i.created_at, i.updated_at, i.deleted_at, c.name AS consumable_name, c.min_stock_level
FROM consumables_inventory i
JOIN consumables c ON i.consumable_id = c.id
WHERE i.hospital_id = $1 AND i.is_low_stock = TRUE AND i.deleted_at IS NULL
ORDER BY c.name
`

type ListLowStockInventoryRow struct {
	ID                uuid.UUID          `json:"id"`
	HospitalID        uuid.UUID          `json:"hospital_id"`
	ConsumableID      uuid.UUID          `json:"consumable_id"`
	BatchNumber       pgtype.Text        `json:"batch_number"`
	QuantityCurrent   int32              `json:"quantity_current"`
	QuantityReserved  int32              `json:"quantity_reserved"`
	QuantityAvailable int32              `json:"quantity_available"`
	UnitCost          pgtype.Numeric     `json:"unit_cost"`
	ExpiryDate        pgtype.Date        `json:"expiry_date"`
	ReceivedDate      pgtype.Date        `json:"received_date"`
	SupplierName      pgtype.Text        `json:"supplier_name"`
	StorageLocation   pgtype.Text        `json:"storage_location"`
	IsLowStock        bool               `json:"is_low_stock"`
	Notes             pgtype.Text        `json:"notes"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	ConsumableName    string             `json:"consumable_name"`
	MinStockLevel     pgtype.Int4        `json:"min_stock_level"`
}

func (q *Queries) ListLowStockInventory(ctx context.Context, hospitalID uuid.UUID) ([]ListLowStockInventoryRow, error) {
	rows, err := q.db.Query(ctx, listLowStockInventory, hospitalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLowStockInventoryRow
	for rows.Next() {
		var i ListLowStockInventoryRow
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.ConsumableID,
			&i.BatchNumber,
			&i.QuantityCurrent,
			&i.QuantityReserved,
			&i.QuantityAvailable,
			&i.UnitCost,
			&i.ExpiryDate,
			&i.ReceivedDate,
			&i.SupplierName,
			&i.StorageLocation,
			&i.IsLowStock,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ConsumableName,
			&i.MinStockLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInventoryQuantity = `-- name: UpdateInventoryQuantity :one
UPDATE consumables_inventory
SET quantity_current = $2, quantity_available = $2 - quantity_reserved
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, hospital_id, consumable_id, batch_number, quantity_current, quantity_reserved, quantity_available, unit_cost, expiry_date, received_date, supplier_name, storage_location, is_low_stock, notes, created_at, updated_at, deleted_at
`

type UpdateInventoryQuantityParams struct {
	ID              uuid.UUID `json:"id"`
	QuantityCurrent int32     `json:"quantity_current"`
}

func (q *Queries) UpdateInventoryQuantity(ctx context.Context, arg UpdateInventoryQuantityParams) (ConsumablesInventory, error) {
	row := q.db.QueryRow(ctx, updateInventoryQuantity, arg.ID, arg.QuantityCurrent)
	var i ConsumablesInventory
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.ConsumableID,
		&i.BatchNumber,
		&i.QuantityCurrent,
		&i.QuantityReserved,
		&i.QuantityAvailable,
		&i.UnitCost,
		&i.ExpiryDate,
		&i.ReceivedDate,
		&i.SupplierName,
		&i.StorageLocation,
		&i.IsLowStock,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
