// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: departments.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDepartment = `-- name: CreateDepartment :one
INSERT INTO departments (
  hospital_id, name, code, description, head_user_id, is_active
) VALUES (
  $1, $2, $3, $4, $5, $6
) RETURNING id, hospital_id, name, code, description, head_user_id, is_active, created_at, updated_at, deleted_at
`

type CreateDepartmentParams struct {
	HospitalID  uuid.UUID   `json:"hospital_id"`
	Name        string      `json:"name"`
	Code        pgtype.Text `json:"code"`
	Description pgtype.Text `json:"description"`
	HeadUserID  pgtype.UUID `json:"head_user_id"`
	IsActive    bool        `json:"is_active"`
}

func (q *Queries) CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, createDepartment,
		arg.HospitalID,
		arg.Name,
		arg.Code,
		arg.Description,
		arg.HeadUserID,
		arg.IsActive,
	)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.HeadUserID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDepartment = `-- name: GetDepartment :one
SELECT id, hospital_id, name, code, description, head_user_id, is_active, created_at, updated_at, deleted_at FROM departments
WHERE id = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetDepartment(ctx context.Context, id uuid.UUID) (Department, error) {
	row := q.db.QueryRow(ctx, getDepartment, id)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.HeadUserID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listDepartments = `-- name: ListDepartments :many
SELECT id, hospital_id, name, code, description, head_user_id, is_active, created_at, updated_at, deleted_at FROM departments
WHERE hospital_id = $1 AND deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListDepartments(ctx context.Context, hospitalID uuid.UUID) ([]Department, error) {
	rows, err := q.db.Query(ctx, listDepartments, hospitalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Department
	for rows.Next() {
		var i Department
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.HeadUserID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDepartment = `-- name: SoftDeleteDepartment :exec
UPDATE departments
SET deleted_at = now()
WHERE id = $1
`

func (q *Queries) SoftDeleteDepartment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteDepartment, id)
	return err
}

const updateDepartment = `-- name: UpdateDepartment :one
UPDATE departments
SET name = $2, code = $3, description = $4, head_user_id = $5, is_active = $6
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, hospital_id, name, code, description, head_user_id, is_active, created_at, updated_at, deleted_at
`

type UpdateDepartmentParams struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Code        pgtype.Text `json:"code"`
	Description pgtype.Text `json:"description"`
	HeadUserID  pgtype.UUID `json:"head_user_id"`
	IsActive    bool        `json:"is_active"`
}

func (q *Queries) UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, updateDepartment,
		arg.ID,
		arg.Name,
		arg.Code,
		arg.Description,
		arg.HeadUserID,
		arg.IsActive,
	)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.HeadUserID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
