// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: diagnoses.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDiagnosis = `-- name: CreateDiagnosis :one
INSERT INTO diagnoses (
    hospital_id, patient_id, icd10_code, description, diagnosis_type, diagnosed_by, admission_id, notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, hospital_id, patient_id, icd10_code, description, diagnosis_type, diagnosed_by, diagnosed_at, admission_id, notes, created_at, updated_at, deleted_at
`

type CreateDiagnosisParams struct {
	HospitalID    uuid.UUID     `json:"hospital_id"`
	PatientID     uuid.UUID     `json:"patient_id"`
	Icd10Code     string        `json:"icd10_code"`
	Description   string        `json:"description"`
	DiagnosisType DiagnosisType `json:"diagnosis_type"`
	DiagnosedBy   uuid.UUID     `json:"diagnosed_by"`
	AdmissionID   pgtype.UUID   `json:"admission_id"`
	Notes         pgtype.Text   `json:"notes"`
}

func (q *Queries) CreateDiagnosis(ctx context.Context, arg CreateDiagnosisParams) (Diagnosis, error) {
	row := q.db.QueryRow(ctx, createDiagnosis,
		arg.HospitalID,
		arg.PatientID,
		arg.Icd10Code,
		arg.Description,
		arg.DiagnosisType,
		arg.DiagnosedBy,
		arg.AdmissionID,
		arg.Notes,
	)
	var i Diagnosis
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.PatientID,
		&i.Icd10Code,
		&i.Description,
		&i.DiagnosisType,
		&i.DiagnosedBy,
		&i.DiagnosedAt,
		&i.AdmissionID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPrimaryDiagnosis = `-- name: GetPrimaryDiagnosis :one
SELECT id, hospital_id, patient_id, icd10_code, description, diagnosis_type, diagnosed_by, diagnosed_at, admission_id, notes, created_at, updated_at, deleted_at FROM diagnoses
WHERE patient_id = $1 AND diagnosis_type = 'primary' AND deleted_at IS NULL
ORDER BY diagnosed_at DESC
LIMIT 1
`

func (q *Queries) GetPrimaryDiagnosis(ctx context.Context, patientID uuid.UUID) (Diagnosis, error) {
	row := q.db.QueryRow(ctx, getPrimaryDiagnosis, patientID)
	var i Diagnosis
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.PatientID,
		&i.Icd10Code,
		&i.Description,
		&i.DiagnosisType,
		&i.DiagnosedBy,
		&i.DiagnosedAt,
		&i.AdmissionID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listDiagnosesByPatient = `-- name: ListDiagnosesByPatient :many
SELECT id, hospital_id, patient_id, icd10_code, description, diagnosis_type, diagnosed_by, diagnosed_at, admission_id, notes, created_at, updated_at, deleted_at FROM diagnoses
WHERE patient_id = $1 AND deleted_at IS NULL
ORDER BY diagnosed_at DESC
`

func (q *Queries) ListDiagnosesByPatient(ctx context.Context, patientID uuid.UUID) ([]Diagnosis, error) {
	rows, err := q.db.Query(ctx, listDiagnosesByPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Diagnosis
	for rows.Next() {
		var i Diagnosis
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.PatientID,
			&i.Icd10Code,
			&i.Description,
			&i.DiagnosisType,
			&i.DiagnosedBy,
			&i.DiagnosedAt,
			&i.AdmissionID,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
