// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dialysis_prescriptions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDialysisPrescription = `-- name: CreateDialysisPrescription :one
INSERT INTO dialysis_prescriptions (
    hospital_id, session_id, patient_id, prescribed_by, modality, duration_mins,
    target_uf_ml, blood_flow_rate, dialysate_flow_rate, membrane_type,
    membrane_surface_area, dialysate_temp, conductivity_target, pd_params,
    anticoagulant, anticoag_route, loading_dose_units, maintenance_dose_units,
    maintenance_rate, sodium_target, potassium_target, bicarbonate_target,
    calcium_target, glucose_target, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25)
RETURNING id, hospital_id, session_id, patient_id, prescribed_by, modality, duration_mins, target_uf_ml, blood_flow_rate, dialysate_flow_rate, membrane_type, membrane_surface_area, dialysate_temp, conductivity_target, pd_params, anticoagulant, anticoag_route, loading_dose_units, maintenance_dose_units, maintenance_rate, sodium_target, potassium_target, bicarbonate_target, calcium_target, glucose_target, notes, created_at, updated_at, deleted_at
`

type CreateDialysisPrescriptionParams struct {
	HospitalID           uuid.UUID         `json:"hospital_id"`
	SessionID            uuid.UUID         `json:"session_id"`
	PatientID            uuid.UUID         `json:"patient_id"`
	PrescribedBy         uuid.UUID         `json:"prescribed_by"`
	Modality             DialysisModality  `json:"modality"`
	DurationMins         int32             `json:"duration_mins"`
	TargetUfMl           pgtype.Numeric    `json:"target_uf_ml"`
	BloodFlowRate        pgtype.Int4       `json:"blood_flow_rate"`
	DialysateFlowRate    pgtype.Int4       `json:"dialysate_flow_rate"`
	MembraneType         pgtype.Text       `json:"membrane_type"`
	MembraneSurfaceArea  pgtype.Numeric    `json:"membrane_surface_area"`
	DialysateTemp        pgtype.Numeric    `json:"dialysate_temp"`
	ConductivityTarget   pgtype.Numeric    `json:"conductivity_target"`
	PdParams             []byte            `json:"pd_params"`
	Anticoagulant        pgtype.Text       `json:"anticoagulant"`
	AnticoagRoute        NullAnticoagRoute `json:"anticoag_route"`
	LoadingDoseUnits     pgtype.Numeric    `json:"loading_dose_units"`
	MaintenanceDoseUnits pgtype.Numeric    `json:"maintenance_dose_units"`
	MaintenanceRate      pgtype.Text       `json:"maintenance_rate"`
	SodiumTarget         pgtype.Numeric    `json:"sodium_target"`
	PotassiumTarget      pgtype.Numeric    `json:"potassium_target"`
	BicarbonateTarget    pgtype.Numeric    `json:"bicarbonate_target"`
	CalciumTarget        pgtype.Numeric    `json:"calcium_target"`
	GlucoseTarget        pgtype.Numeric    `json:"glucose_target"`
	Notes                pgtype.Text       `json:"notes"`
}

func (q *Queries) CreateDialysisPrescription(ctx context.Context, arg CreateDialysisPrescriptionParams) (DialysisPrescription, error) {
	row := q.db.QueryRow(ctx, createDialysisPrescription,
		arg.HospitalID,
		arg.SessionID,
		arg.PatientID,
		arg.PrescribedBy,
		arg.Modality,
		arg.DurationMins,
		arg.TargetUfMl,
		arg.BloodFlowRate,
		arg.DialysateFlowRate,
		arg.MembraneType,
		arg.MembraneSurfaceArea,
		arg.DialysateTemp,
		arg.ConductivityTarget,
		arg.PdParams,
		arg.Anticoagulant,
		arg.AnticoagRoute,
		arg.LoadingDoseUnits,
		arg.MaintenanceDoseUnits,
		arg.MaintenanceRate,
		arg.SodiumTarget,
		arg.PotassiumTarget,
		arg.BicarbonateTarget,
		arg.CalciumTarget,
		arg.GlucoseTarget,
		arg.Notes,
	)
	var i DialysisPrescription
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.SessionID,
		&i.PatientID,
		&i.PrescribedBy,
		&i.Modality,
		&i.DurationMins,
		&i.TargetUfMl,
		&i.BloodFlowRate,
		&i.DialysateFlowRate,
		&i.MembraneType,
		&i.MembraneSurfaceArea,
		&i.DialysateTemp,
		&i.ConductivityTarget,
		&i.PdParams,
		&i.Anticoagulant,
		&i.AnticoagRoute,
		&i.LoadingDoseUnits,
		&i.MaintenanceDoseUnits,
		&i.MaintenanceRate,
		&i.SodiumTarget,
		&i.PotassiumTarget,
		&i.BicarbonateTarget,
		&i.CalciumTarget,
		&i.GlucoseTarget,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteDialysisPrescription = `-- name: DeleteDialysisPrescription :exec
UPDATE dialysis_prescriptions SET deleted_at = now() WHERE id = $1
`

func (q *Queries) DeleteDialysisPrescription(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDialysisPrescription, id)
	return err
}

const getDialysisPrescription = `-- name: GetDialysisPrescription :one
SELECT id, hospital_id, session_id, patient_id, prescribed_by, modality, duration_mins, target_uf_ml, blood_flow_rate, dialysate_flow_rate, membrane_type, membrane_surface_area, dialysate_temp, conductivity_target, pd_params, anticoagulant, anticoag_route, loading_dose_units, maintenance_dose_units, maintenance_rate, sodium_target, potassium_target, bicarbonate_target, calcium_target, glucose_target, notes, created_at, updated_at, deleted_at FROM dialysis_prescriptions WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDialysisPrescription(ctx context.Context, id uuid.UUID) (DialysisPrescription, error) {
	row := q.db.QueryRow(ctx, getDialysisPrescription, id)
	var i DialysisPrescription
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.SessionID,
		&i.PatientID,
		&i.PrescribedBy,
		&i.Modality,
		&i.DurationMins,
		&i.TargetUfMl,
		&i.BloodFlowRate,
		&i.DialysateFlowRate,
		&i.MembraneType,
		&i.MembraneSurfaceArea,
		&i.DialysateTemp,
		&i.ConductivityTarget,
		&i.PdParams,
		&i.Anticoagulant,
		&i.AnticoagRoute,
		&i.LoadingDoseUnits,
		&i.MaintenanceDoseUnits,
		&i.MaintenanceRate,
		&i.SodiumTarget,
		&i.PotassiumTarget,
		&i.BicarbonateTarget,
		&i.CalciumTarget,
		&i.GlucoseTarget,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPrescriptionBySession = `-- name: GetPrescriptionBySession :one
SELECT id, hospital_id, session_id, patient_id, prescribed_by, modality, duration_mins, target_uf_ml, blood_flow_rate, dialysate_flow_rate, membrane_type, membrane_surface_area, dialysate_temp, conductivity_target, pd_params, anticoagulant, anticoag_route, loading_dose_units, maintenance_dose_units, maintenance_rate, sodium_target, potassium_target, bicarbonate_target, calcium_target, glucose_target, notes, created_at, updated_at, deleted_at FROM dialysis_prescriptions WHERE session_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPrescriptionBySession(ctx context.Context, sessionID uuid.UUID) (DialysisPrescription, error) {
	row := q.db.QueryRow(ctx, getPrescriptionBySession, sessionID)
	var i DialysisPrescription
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.SessionID,
		&i.PatientID,
		&i.PrescribedBy,
		&i.Modality,
		&i.DurationMins,
		&i.TargetUfMl,
		&i.BloodFlowRate,
		&i.DialysateFlowRate,
		&i.MembraneType,
		&i.MembraneSurfaceArea,
		&i.DialysateTemp,
		&i.ConductivityTarget,
		&i.PdParams,
		&i.Anticoagulant,
		&i.AnticoagRoute,
		&i.LoadingDoseUnits,
		&i.MaintenanceDoseUnits,
		&i.MaintenanceRate,
		&i.SodiumTarget,
		&i.PotassiumTarget,
		&i.BicarbonateTarget,
		&i.CalciumTarget,
		&i.GlucoseTarget,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPrescriptionsByPatient = `-- name: ListPrescriptionsByPatient :many
SELECT id, hospital_id, session_id, patient_id, prescribed_by, modality, duration_mins, target_uf_ml, blood_flow_rate, dialysate_flow_rate, membrane_type, membrane_surface_area, dialysate_temp, conductivity_target, pd_params, anticoagulant, anticoag_route, loading_dose_units, maintenance_dose_units, maintenance_rate, sodium_target, potassium_target, bicarbonate_target, calcium_target, glucose_target, notes, created_at, updated_at, deleted_at FROM dialysis_prescriptions
WHERE patient_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListPrescriptionsByPatient(ctx context.Context, patientID uuid.UUID) ([]DialysisPrescription, error) {
	rows, err := q.db.Query(ctx, listPrescriptionsByPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DialysisPrescription
	for rows.Next() {
		var i DialysisPrescription
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.SessionID,
			&i.PatientID,
			&i.PrescribedBy,
			&i.Modality,
			&i.DurationMins,
			&i.TargetUfMl,
			&i.BloodFlowRate,
			&i.DialysateFlowRate,
			&i.MembraneType,
			&i.MembraneSurfaceArea,
			&i.DialysateTemp,
			&i.ConductivityTarget,
			&i.PdParams,
			&i.Anticoagulant,
			&i.AnticoagRoute,
			&i.LoadingDoseUnits,
			&i.MaintenanceDoseUnits,
			&i.MaintenanceRate,
			&i.SodiumTarget,
			&i.PotassiumTarget,
			&i.BicarbonateTarget,
			&i.CalciumTarget,
			&i.GlucoseTarget,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDialysisPrescription = `-- name: UpdateDialysisPrescription :one
UPDATE dialysis_prescriptions
SET modality = $2, duration_mins = $3, target_uf_ml = $4, blood_flow_rate = $5,
    dialysate_flow_rate = $6, membrane_type = $7, membrane_surface_area = $8,
    dialysate_temp = $9, conductivity_target = $10, pd_params = $11,
    anticoagulant = $12, anticoag_route = $13, loading_dose_units = $14,
    maintenance_dose_units = $15, maintenance_rate = $16, sodium_target = $17,
    potassium_target = $18, bicarbonate_target = $19, calcium_target = $20,
    glucose_target = $21, notes = $22
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, hospital_id, session_id, patient_id, prescribed_by, modality, duration_mins, target_uf_ml, blood_flow_rate, dialysate_flow_rate, membrane_type, membrane_surface_area, dialysate_temp, conductivity_target, pd_params, anticoagulant, anticoag_route, loading_dose_units, maintenance_dose_units, maintenance_rate, sodium_target, potassium_target, bicarbonate_target, calcium_target, glucose_target, notes, created_at, updated_at, deleted_at
`

type UpdateDialysisPrescriptionParams struct {
	ID                   uuid.UUID         `json:"id"`
	Modality             DialysisModality  `json:"modality"`
	DurationMins         int32             `json:"duration_mins"`
	TargetUfMl           pgtype.Numeric    `json:"target_uf_ml"`
	BloodFlowRate        pgtype.Int4       `json:"blood_flow_rate"`
	DialysateFlowRate    pgtype.Int4       `json:"dialysate_flow_rate"`
	MembraneType         pgtype.Text       `json:"membrane_type"`
	MembraneSurfaceArea  pgtype.Numeric    `json:"membrane_surface_area"`
	DialysateTemp        pgtype.Numeric    `json:"dialysate_temp"`
	ConductivityTarget   pgtype.Numeric    `json:"conductivity_target"`
	PdParams             []byte            `json:"pd_params"`
	Anticoagulant        pgtype.Text       `json:"anticoagulant"`
	AnticoagRoute        NullAnticoagRoute `json:"anticoag_route"`
	LoadingDoseUnits     pgtype.Numeric    `json:"loading_dose_units"`
	MaintenanceDoseUnits pgtype.Numeric    `json:"maintenance_dose_units"`
	MaintenanceRate      pgtype.Text       `json:"maintenance_rate"`
	SodiumTarget         pgtype.Numeric    `json:"sodium_target"`
	PotassiumTarget      pgtype.Numeric    `json:"potassium_target"`
	BicarbonateTarget    pgtype.Numeric    `json:"bicarbonate_target"`
	CalciumTarget        pgtype.Numeric    `json:"calcium_target"`
	GlucoseTarget        pgtype.Numeric    `json:"glucose_target"`
	Notes                pgtype.Text       `json:"notes"`
}

func (q *Queries) UpdateDialysisPrescription(ctx context.Context, arg UpdateDialysisPrescriptionParams) (DialysisPrescription, error) {
	row := q.db.QueryRow(ctx, updateDialysisPrescription,
		arg.ID,
		arg.Modality,
		arg.DurationMins,
		arg.TargetUfMl,
		arg.BloodFlowRate,
		arg.DialysateFlowRate,
		arg.MembraneType,
		arg.MembraneSurfaceArea,
		arg.DialysateTemp,
		arg.ConductivityTarget,
		arg.PdParams,
		arg.Anticoagulant,
		arg.AnticoagRoute,
		arg.LoadingDoseUnits,
		arg.MaintenanceDoseUnits,
		arg.MaintenanceRate,
		arg.SodiumTarget,
		arg.PotassiumTarget,
		arg.BicarbonateTarget,
		arg.CalciumTarget,
		arg.GlucoseTarget,
		arg.Notes,
	)
	var i DialysisPrescription
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.SessionID,
		&i.PatientID,
		&i.PrescribedBy,
		&i.Modality,
		&i.DurationMins,
		&i.TargetUfMl,
		&i.BloodFlowRate,
		&i.DialysateFlowRate,
		&i.MembraneType,
		&i.MembraneSurfaceArea,
		&i.DialysateTemp,
		&i.ConductivityTarget,
		&i.PdParams,
		&i.Anticoagulant,
		&i.AnticoagRoute,
		&i.LoadingDoseUnits,
		&i.MaintenanceDoseUnits,
		&i.MaintenanceRate,
		&i.SodiumTarget,
		&i.PotassiumTarget,
		&i.BicarbonateTarget,
		&i.CalciumTarget,
		&i.GlucoseTarget,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
