// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dialysis_machines.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDialysisMachine = `-- name: CreateDialysisMachine :one
INSERT INTO dialysis_machines (
    hospital_id, machine_code, serial_number, model, manufacturer,
    manufacture_year, installation_date, location, status, is_hbv_dedicated,
    last_service_date, next_service_date, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, hospital_id, machine_code, serial_number, model, manufacturer, manufacture_year, installation_date, location, status, is_hbv_dedicated, last_service_date, next_service_date, notes, created_at, updated_at, deleted_at
`

type CreateDialysisMachineParams struct {
	HospitalID       uuid.UUID     `json:"hospital_id"`
	MachineCode      string        `json:"machine_code"`
	SerialNumber     string        `json:"serial_number"`
	Model            string        `json:"model"`
	Manufacturer     string        `json:"manufacturer"`
	ManufactureYear  pgtype.Int4   `json:"manufacture_year"`
	InstallationDate pgtype.Date   `json:"installation_date"`
	Location         pgtype.Text   `json:"location"`
	Status           MachineStatus `json:"status"`
	IsHbvDedicated   bool          `json:"is_hbv_dedicated"`
	LastServiceDate  pgtype.Date   `json:"last_service_date"`
	NextServiceDate  pgtype.Date   `json:"next_service_date"`
	Notes            pgtype.Text   `json:"notes"`
}

func (q *Queries) CreateDialysisMachine(ctx context.Context, arg CreateDialysisMachineParams) (DialysisMachine, error) {
	row := q.db.QueryRow(ctx, createDialysisMachine,
		arg.HospitalID,
		arg.MachineCode,
		arg.SerialNumber,
		arg.Model,
		arg.Manufacturer,
		arg.ManufactureYear,
		arg.InstallationDate,
		arg.Location,
		arg.Status,
		arg.IsHbvDedicated,
		arg.LastServiceDate,
		arg.NextServiceDate,
		arg.Notes,
	)
	var i DialysisMachine
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.MachineCode,
		&i.SerialNumber,
		&i.Model,
		&i.Manufacturer,
		&i.ManufactureYear,
		&i.InstallationDate,
		&i.Location,
		&i.Status,
		&i.IsHbvDedicated,
		&i.LastServiceDate,
		&i.NextServiceDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteDialysisMachine = `-- name: DeleteDialysisMachine :exec
UPDATE dialysis_machines SET deleted_at = now() WHERE id = $1
`

func (q *Queries) DeleteDialysisMachine(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDialysisMachine, id)
	return err
}

const getDialysisMachine = `-- name: GetDialysisMachine :one
SELECT id, hospital_id, machine_code, serial_number, model, manufacturer, manufacture_year, installation_date, location, status, is_hbv_dedicated, last_service_date, next_service_date, notes, created_at, updated_at, deleted_at FROM dialysis_machines WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDialysisMachine(ctx context.Context, id uuid.UUID) (DialysisMachine, error) {
	row := q.db.QueryRow(ctx, getDialysisMachine, id)
	var i DialysisMachine
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.MachineCode,
		&i.SerialNumber,
		&i.Model,
		&i.Manufacturer,
		&i.ManufactureYear,
		&i.InstallationDate,
		&i.Location,
		&i.Status,
		&i.IsHbvDedicated,
		&i.LastServiceDate,
		&i.NextServiceDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAvailableMachines = `-- name: ListAvailableMachines :many
SELECT id, hospital_id, machine_code, serial_number, model, manufacturer, manufacture_year, installation_date, location, status, is_hbv_dedicated, last_service_date, next_service_date, notes, created_at, updated_at, deleted_at FROM dialysis_machines
WHERE hospital_id = $1 AND status = 'available' AND deleted_at IS NULL
ORDER BY machine_code
`

func (q *Queries) ListAvailableMachines(ctx context.Context, hospitalID uuid.UUID) ([]DialysisMachine, error) {
	rows, err := q.db.Query(ctx, listAvailableMachines, hospitalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DialysisMachine
	for rows.Next() {
		var i DialysisMachine
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.MachineCode,
			&i.SerialNumber,
			&i.Model,
			&i.Manufacturer,
			&i.ManufactureYear,
			&i.InstallationDate,
			&i.Location,
			&i.Status,
			&i.IsHbvDedicated,
			&i.LastServiceDate,
			&i.NextServiceDate,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDialysisMachinesByHospital = `-- name: ListDialysisMachinesByHospital :many
SELECT id, hospital_id, machine_code, serial_number, model, manufacturer, manufacture_year, installation_date, location, status, is_hbv_dedicated, last_service_date, next_service_date, notes, created_at, updated_at, deleted_at FROM dialysis_machines
WHERE hospital_id = $1 AND deleted_at IS NULL
ORDER BY machine_code
`

func (q *Queries) ListDialysisMachinesByHospital(ctx context.Context, hospitalID uuid.UUID) ([]DialysisMachine, error) {
	rows, err := q.db.Query(ctx, listDialysisMachinesByHospital, hospitalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DialysisMachine
	for rows.Next() {
		var i DialysisMachine
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.MachineCode,
			&i.SerialNumber,
			&i.Model,
			&i.Manufacturer,
			&i.ManufactureYear,
			&i.InstallationDate,
			&i.Location,
			&i.Status,
			&i.IsHbvDedicated,
			&i.LastServiceDate,
			&i.NextServiceDate,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHBVDedicatedMachines = `-- name: ListHBVDedicatedMachines :many
SELECT id, hospital_id, machine_code, serial_number, model, manufacturer, manufacture_year, installation_date, location, status, is_hbv_dedicated, last_service_date, next_service_date, notes, created_at, updated_at, deleted_at FROM dialysis_machines
WHERE hospital_id = $1 AND is_hbv_dedicated = TRUE AND deleted_at IS NULL
ORDER BY machine_code
`

func (q *Queries) ListHBVDedicatedMachines(ctx context.Context, hospitalID uuid.UUID) ([]DialysisMachine, error) {
	rows, err := q.db.Query(ctx, listHBVDedicatedMachines, hospitalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DialysisMachine
	for rows.Next() {
		var i DialysisMachine
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.MachineCode,
			&i.SerialNumber,
			&i.Model,
			&i.Manufacturer,
			&i.ManufactureYear,
			&i.InstallationDate,
			&i.Location,
			&i.Status,
			&i.IsHbvDedicated,
			&i.LastServiceDate,
			&i.NextServiceDate,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDialysisMachine = `-- name: UpdateDialysisMachine :one
UPDATE dialysis_machines
SET machine_code = $2, serial_number = $3, model = $4, manufacturer = $5,
    manufacture_year = $6, installation_date = $7, location = $8, status = $9,
    is_hbv_dedicated = $10, last_service_date = $11, next_service_date = $12, notes = $13
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, hospital_id, machine_code, serial_number, model, manufacturer, manufacture_year, installation_date, location, status, is_hbv_dedicated, last_service_date, next_service_date, notes, created_at, updated_at, deleted_at
`

type UpdateDialysisMachineParams struct {
	ID               uuid.UUID     `json:"id"`
	MachineCode      string        `json:"machine_code"`
	SerialNumber     string        `json:"serial_number"`
	Model            string        `json:"model"`
	Manufacturer     string        `json:"manufacturer"`
	ManufactureYear  pgtype.Int4   `json:"manufacture_year"`
	InstallationDate pgtype.Date   `json:"installation_date"`
	Location         pgtype.Text   `json:"location"`
	Status           MachineStatus `json:"status"`
	IsHbvDedicated   bool          `json:"is_hbv_dedicated"`
	LastServiceDate  pgtype.Date   `json:"last_service_date"`
	NextServiceDate  pgtype.Date   `json:"next_service_date"`
	Notes            pgtype.Text   `json:"notes"`
}

func (q *Queries) UpdateDialysisMachine(ctx context.Context, arg UpdateDialysisMachineParams) (DialysisMachine, error) {
	row := q.db.QueryRow(ctx, updateDialysisMachine,
		arg.ID,
		arg.MachineCode,
		arg.SerialNumber,
		arg.Model,
		arg.Manufacturer,
		arg.ManufactureYear,
		arg.InstallationDate,
		arg.Location,
		arg.Status,
		arg.IsHbvDedicated,
		arg.LastServiceDate,
		arg.NextServiceDate,
		arg.Notes,
	)
	var i DialysisMachine
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.MachineCode,
		&i.SerialNumber,
		&i.Model,
		&i.Manufacturer,
		&i.ManufactureYear,
		&i.InstallationDate,
		&i.Location,
		&i.Status,
		&i.IsHbvDedicated,
		&i.LastServiceDate,
		&i.NextServiceDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateMachineStatus = `-- name: UpdateMachineStatus :one
UPDATE dialysis_machines
SET status = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, hospital_id, machine_code, serial_number, model, manufacturer, manufacture_year, installation_date, location, status, is_hbv_dedicated, last_service_date, next_service_date, notes, created_at, updated_at, deleted_at
`

type UpdateMachineStatusParams struct {
	ID     uuid.UUID     `json:"id"`
	Status MachineStatus `json:"status"`
}

func (q *Queries) UpdateMachineStatus(ctx context.Context, arg UpdateMachineStatusParams) (DialysisMachine, error) {
	row := q.db.QueryRow(ctx, updateMachineStatus, arg.ID, arg.Status)
	var i DialysisMachine
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.MachineCode,
		&i.SerialNumber,
		&i.Model,
		&i.Manufacturer,
		&i.ManufactureYear,
		&i.InstallationDate,
		&i.Location,
		&i.Status,
		&i.IsHbvDedicated,
		&i.LastServiceDate,
		&i.NextServiceDate,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
