// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: donor_reports.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approveReport = `-- name: ApproveReport :one
UPDATE donor_reports
SET approved_by = $2, approved_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, hospital_id, report_name, report_type, period_start, period_end, recipient_organization, data, generated_at, generated_by, submitted_at, submitted_by, submission_reference, approved_by, approved_at, notes, created_at, updated_at, deleted_at
`

type ApproveReportParams struct {
	ID         uuid.UUID   `json:"id"`
	ApprovedBy pgtype.UUID `json:"approved_by"`
}

func (q *Queries) ApproveReport(ctx context.Context, arg ApproveReportParams) (DonorReport, error) {
	row := q.db.QueryRow(ctx, approveReport, arg.ID, arg.ApprovedBy)
	var i DonorReport
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.ReportName,
		&i.ReportType,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.RecipientOrganization,
		&i.Data,
		&i.GeneratedAt,
		&i.GeneratedBy,
		&i.SubmittedAt,
		&i.SubmittedBy,
		&i.SubmissionReference,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createDonorReport = `-- name: CreateDonorReport :one
INSERT INTO donor_reports (
    hospital_id, report_name, report_type, period_start, period_end,
    recipient_organization, data, generated_by, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, hospital_id, report_name, report_type, period_start, period_end, recipient_organization, data, generated_at, generated_by, submitted_at, submitted_by, submission_reference, approved_by, approved_at, notes, created_at, updated_at, deleted_at
`

type CreateDonorReportParams struct {
	HospitalID            uuid.UUID   `json:"hospital_id"`
	ReportName            string      `json:"report_name"`
	ReportType            ReportType  `json:"report_type"`
	PeriodStart           pgtype.Date `json:"period_start"`
	PeriodEnd             pgtype.Date `json:"period_end"`
	RecipientOrganization string      `json:"recipient_organization"`
	Data                  []byte      `json:"data"`
	GeneratedBy           uuid.UUID   `json:"generated_by"`
	Notes                 pgtype.Text `json:"notes"`
}

func (q *Queries) CreateDonorReport(ctx context.Context, arg CreateDonorReportParams) (DonorReport, error) {
	row := q.db.QueryRow(ctx, createDonorReport,
		arg.HospitalID,
		arg.ReportName,
		arg.ReportType,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.RecipientOrganization,
		arg.Data,
		arg.GeneratedBy,
		arg.Notes,
	)
	var i DonorReport
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.ReportName,
		&i.ReportType,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.RecipientOrganization,
		&i.Data,
		&i.GeneratedAt,
		&i.GeneratedBy,
		&i.SubmittedAt,
		&i.SubmittedBy,
		&i.SubmissionReference,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteDonorReport = `-- name: DeleteDonorReport :exec
UPDATE donor_reports SET deleted_at = now() WHERE id = $1
`

func (q *Queries) DeleteDonorReport(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDonorReport, id)
	return err
}

const getDonorReport = `-- name: GetDonorReport :one
SELECT id, hospital_id, report_name, report_type, period_start, period_end, recipient_organization, data, generated_at, generated_by, submitted_at, submitted_by, submission_reference, approved_by, approved_at, notes, created_at, updated_at, deleted_at FROM donor_reports WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDonorReport(ctx context.Context, id uuid.UUID) (DonorReport, error) {
	row := q.db.QueryRow(ctx, getDonorReport, id)
	var i DonorReport
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.ReportName,
		&i.ReportType,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.RecipientOrganization,
		&i.Data,
		&i.GeneratedAt,
		&i.GeneratedBy,
		&i.SubmittedAt,
		&i.SubmittedBy,
		&i.SubmissionReference,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listReportsByHospital = `-- name: ListReportsByHospital :many
SELECT id, hospital_id, report_name, report_type, period_start, period_end, recipient_organization, data, generated_at, generated_by, submitted_at, submitted_by, submission_reference, approved_by, approved_at, notes, created_at, updated_at, deleted_at FROM donor_reports
WHERE hospital_id = $1 AND deleted_at IS NULL
ORDER BY period_start DESC, report_type
`

func (q *Queries) ListReportsByHospital(ctx context.Context, hospitalID uuid.UUID) ([]DonorReport, error) {
	rows, err := q.db.Query(ctx, listReportsByHospital, hospitalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DonorReport
	for rows.Next() {
		var i DonorReport
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.ReportName,
			&i.ReportType,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.RecipientOrganization,
			&i.Data,
			&i.GeneratedAt,
			&i.GeneratedBy,
			&i.SubmittedAt,
			&i.SubmittedBy,
			&i.SubmissionReference,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportsByPeriod = `-- name: ListReportsByPeriod :many
SELECT id, hospital_id, report_name, report_type, period_start, period_end, recipient_organization, data, generated_at, generated_by, submitted_at, submitted_by, submission_reference, approved_by, approved_at, notes, created_at, updated_at, deleted_at FROM donor_reports
WHERE hospital_id = $1
  AND period_start >= $2
  AND period_end <= $3
  AND deleted_at IS NULL
ORDER BY period_start DESC
`

type ListReportsByPeriodParams struct {
	HospitalID  uuid.UUID   `json:"hospital_id"`
	PeriodStart pgtype.Date `json:"period_start"`
	PeriodEnd   pgtype.Date `json:"period_end"`
}

func (q *Queries) ListReportsByPeriod(ctx context.Context, arg ListReportsByPeriodParams) ([]DonorReport, error) {
	rows, err := q.db.Query(ctx, listReportsByPeriod, arg.HospitalID, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DonorReport
	for rows.Next() {
		var i DonorReport
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.ReportName,
			&i.ReportType,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.RecipientOrganization,
			&i.Data,
			&i.GeneratedAt,
			&i.GeneratedBy,
			&i.SubmittedAt,
			&i.SubmittedBy,
			&i.SubmissionReference,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportsByType = `-- name: ListReportsByType :many
SELECT id, hospital_id, report_name, report_type, period_start, period_end, recipient_organization, data, generated_at, generated_by, submitted_at, submitted_by, submission_reference, approved_by, approved_at, notes, created_at, updated_at, deleted_at FROM donor_reports
WHERE hospital_id = $1 AND report_type = $2 AND deleted_at IS NULL
ORDER BY period_start DESC
`

type ListReportsByTypeParams struct {
	HospitalID uuid.UUID  `json:"hospital_id"`
	ReportType ReportType `json:"report_type"`
}

func (q *Queries) ListReportsByType(ctx context.Context, arg ListReportsByTypeParams) ([]DonorReport, error) {
	rows, err := q.db.Query(ctx, listReportsByType, arg.HospitalID, arg.ReportType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DonorReport
	for rows.Next() {
		var i DonorReport
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.ReportName,
			&i.ReportType,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.RecipientOrganization,
			&i.Data,
			&i.GeneratedAt,
			&i.GeneratedBy,
			&i.SubmittedAt,
			&i.SubmittedBy,
			&i.SubmissionReference,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnsubmittedReports = `-- name: ListUnsubmittedReports :many
SELECT id, hospital_id, report_name, report_type, period_start, period_end, recipient_organization, data, generated_at, generated_by, submitted_at, submitted_by, submission_reference, approved_by, approved_at, notes, created_at, updated_at, deleted_at FROM donor_reports
WHERE hospital_id = $1 AND submitted_at IS NULL AND deleted_at IS NULL
ORDER BY generated_at DESC
`

func (q *Queries) ListUnsubmittedReports(ctx context.Context, hospitalID uuid.UUID) ([]DonorReport, error) {
	rows, err := q.db.Query(ctx, listUnsubmittedReports, hospitalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DonorReport
	for rows.Next() {
		var i DonorReport
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.ReportName,
			&i.ReportType,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.RecipientOrganization,
			&i.Data,
			&i.GeneratedAt,
			&i.GeneratedBy,
			&i.SubmittedAt,
			&i.SubmittedBy,
			&i.SubmissionReference,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const submitReport = `-- name: SubmitReport :one
UPDATE donor_reports
SET submitted_at = now(), submitted_by = $2, submission_reference = $3
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, hospital_id, report_name, report_type, period_start, period_end, recipient_organization, data, generated_at, generated_by, submitted_at, submitted_by, submission_reference, approved_by, approved_at, notes, created_at, updated_at, deleted_at
`

type SubmitReportParams struct {
	ID                  uuid.UUID   `json:"id"`
	SubmittedBy         pgtype.UUID `json:"submitted_by"`
	SubmissionReference pgtype.Text `json:"submission_reference"`
}

func (q *Queries) SubmitReport(ctx context.Context, arg SubmitReportParams) (DonorReport, error) {
	row := q.db.QueryRow(ctx, submitReport, arg.ID, arg.SubmittedBy, arg.SubmissionReference)
	var i DonorReport
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.ReportName,
		&i.ReportType,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.RecipientOrganization,
		&i.Data,
		&i.GeneratedAt,
		&i.GeneratedBy,
		&i.SubmittedAt,
		&i.SubmittedBy,
		&i.SubmissionReference,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
