// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: drug_interactions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkInteraction = `-- name: CheckInteraction :one
SELECT id, hospital_id, medication_a_id, medication_b_id, severity, interaction_type, description, clinical_effect, management_recommendation, evidence_level, reference_source, is_active, created_at, updated_at, deleted_at FROM drug_interactions
WHERE ((medication_a_id = $1 AND medication_b_id = $2)
   OR (medication_a_id = $2 AND medication_b_id = $1))
AND deleted_at IS NULL
LIMIT 1
`

type CheckInteractionParams struct {
	MedicationAID uuid.UUID `json:"medication_a_id"`
	MedicationBID uuid.UUID `json:"medication_b_id"`
}

func (q *Queries) CheckInteraction(ctx context.Context, arg CheckInteractionParams) (DrugInteraction, error) {
	row := q.db.QueryRow(ctx, checkInteraction, arg.MedicationAID, arg.MedicationBID)
	var i DrugInteraction
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.MedicationAID,
		&i.MedicationBID,
		&i.Severity,
		&i.InteractionType,
		&i.Description,
		&i.ClinicalEffect,
		&i.ManagementRecommendation,
		&i.EvidenceLevel,
		&i.ReferenceSource,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createDrugInteraction = `-- name: CreateDrugInteraction :one
INSERT INTO drug_interactions (
    hospital_id, medication_a_id, medication_b_id, severity, description,
    clinical_effect, management_recommendation
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, hospital_id, medication_a_id, medication_b_id, severity, interaction_type, description, clinical_effect, management_recommendation, evidence_level, reference_source, is_active, created_at, updated_at, deleted_at
`

type CreateDrugInteractionParams struct {
	HospitalID               uuid.UUID   `json:"hospital_id"`
	MedicationAID            uuid.UUID   `json:"medication_a_id"`
	MedicationBID            uuid.UUID   `json:"medication_b_id"`
	Severity                 string      `json:"severity"`
	Description              string      `json:"description"`
	ClinicalEffect           pgtype.Text `json:"clinical_effect"`
	ManagementRecommendation pgtype.Text `json:"management_recommendation"`
}

func (q *Queries) CreateDrugInteraction(ctx context.Context, arg CreateDrugInteractionParams) (DrugInteraction, error) {
	row := q.db.QueryRow(ctx, createDrugInteraction,
		arg.HospitalID,
		arg.MedicationAID,
		arg.MedicationBID,
		arg.Severity,
		arg.Description,
		arg.ClinicalEffect,
		arg.ManagementRecommendation,
	)
	var i DrugInteraction
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.MedicationAID,
		&i.MedicationBID,
		&i.Severity,
		&i.InteractionType,
		&i.Description,
		&i.ClinicalEffect,
		&i.ManagementRecommendation,
		&i.EvidenceLevel,
		&i.ReferenceSource,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteDrugInteraction = `-- name: DeleteDrugInteraction :exec
UPDATE drug_interactions SET deleted_at = now() WHERE id = $1
`

func (q *Queries) DeleteDrugInteraction(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDrugInteraction, id)
	return err
}

const getDrugInteraction = `-- name: GetDrugInteraction :one
SELECT id, hospital_id, medication_a_id, medication_b_id, severity, interaction_type, description, clinical_effect, management_recommendation, evidence_level, reference_source, is_active, created_at, updated_at, deleted_at FROM drug_interactions WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDrugInteraction(ctx context.Context, id uuid.UUID) (DrugInteraction, error) {
	row := q.db.QueryRow(ctx, getDrugInteraction, id)
	var i DrugInteraction
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.MedicationAID,
		&i.MedicationBID,
		&i.Severity,
		&i.InteractionType,
		&i.Description,
		&i.ClinicalEffect,
		&i.ManagementRecommendation,
		&i.EvidenceLevel,
		&i.ReferenceSource,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listInteractionsForMedication = `-- name: ListInteractionsForMedication :many
SELECT id, hospital_id, medication_a_id, medication_b_id, severity, interaction_type, description, clinical_effect, management_recommendation, evidence_level, reference_source, is_active, created_at, updated_at, deleted_at FROM drug_interactions
WHERE (medication_a_id = $1 OR medication_b_id = $1)
AND deleted_at IS NULL
ORDER BY severity DESC
`

func (q *Queries) ListInteractionsForMedication(ctx context.Context, medicationAID uuid.UUID) ([]DrugInteraction, error) {
	rows, err := q.db.Query(ctx, listInteractionsForMedication, medicationAID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DrugInteraction
	for rows.Next() {
		var i DrugInteraction
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.MedicationAID,
			&i.MedicationBID,
			&i.Severity,
			&i.InteractionType,
			&i.Description,
			&i.ClinicalEffect,
			&i.ManagementRecommendation,
			&i.EvidenceLevel,
			&i.ReferenceSource,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSevereInteractions = `-- name: ListSevereInteractions :many
SELECT id, hospital_id, medication_a_id, medication_b_id, severity, interaction_type, description, clinical_effect, management_recommendation, evidence_level, reference_source, is_active, created_at, updated_at, deleted_at FROM drug_interactions
WHERE hospital_id = $1 AND severity IN ('severe', 'contraindicated')
AND deleted_at IS NULL
ORDER BY severity DESC, medication_a_id
`

func (q *Queries) ListSevereInteractions(ctx context.Context, hospitalID uuid.UUID) ([]DrugInteraction, error) {
	rows, err := q.db.Query(ctx, listSevereInteractions, hospitalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DrugInteraction
	for rows.Next() {
		var i DrugInteraction
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.MedicationAID,
			&i.MedicationBID,
			&i.Severity,
			&i.InteractionType,
			&i.Description,
			&i.ClinicalEffect,
			&i.ManagementRecommendation,
			&i.EvidenceLevel,
			&i.ReferenceSource,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
