// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: equipment_maintenance.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeMaintenance = `-- name: CompleteMaintenance :one
UPDATE equipment_maintenance
SET is_completed = TRUE, performed_date = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, hospital_id, equipment_id, maintenance_type, scheduled_date, performed_date, performed_by, technician_name, technician_company, next_due_date, cost, findings, actions_taken, parts_replaced, is_completed, notes, created_at, updated_at, deleted_at
`

type CompleteMaintenanceParams struct {
	ID            uuid.UUID   `json:"id"`
	PerformedDate pgtype.Date `json:"performed_date"`
}

func (q *Queries) CompleteMaintenance(ctx context.Context, arg CompleteMaintenanceParams) (EquipmentMaintenance, error) {
	row := q.db.QueryRow(ctx, completeMaintenance, arg.ID, arg.PerformedDate)
	var i EquipmentMaintenance
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.EquipmentID,
		&i.MaintenanceType,
		&i.ScheduledDate,
		&i.PerformedDate,
		&i.PerformedBy,
		&i.TechnicianName,
		&i.TechnicianCompany,
		&i.NextDueDate,
		&i.Cost,
		&i.Findings,
		&i.ActionsTaken,
		&i.PartsReplaced,
		&i.IsCompleted,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createEquipmentMaintenance = `-- name: CreateEquipmentMaintenance :one
INSERT INTO equipment_maintenance (
    hospital_id, equipment_id, maintenance_type, scheduled_date,
    performed_date, performed_by, technician_name, technician_company,
    next_due_date, cost, findings, actions_taken, parts_replaced, is_completed, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, hospital_id, equipment_id, maintenance_type, scheduled_date, performed_date, performed_by, technician_name, technician_company, next_due_date, cost, findings, actions_taken, parts_replaced, is_completed, notes, created_at, updated_at, deleted_at
`

type CreateEquipmentMaintenanceParams struct {
	HospitalID        uuid.UUID       `json:"hospital_id"`
	EquipmentID       uuid.UUID       `json:"equipment_id"`
	MaintenanceType   MaintenanceType `json:"maintenance_type"`
	ScheduledDate     pgtype.Date     `json:"scheduled_date"`
	PerformedDate     pgtype.Date     `json:"performed_date"`
	PerformedBy       pgtype.UUID     `json:"performed_by"`
	TechnicianName    pgtype.Text     `json:"technician_name"`
	TechnicianCompany pgtype.Text     `json:"technician_company"`
	NextDueDate       pgtype.Date     `json:"next_due_date"`
	Cost              pgtype.Numeric  `json:"cost"`
	Findings          pgtype.Text     `json:"findings"`
	ActionsTaken      pgtype.Text     `json:"actions_taken"`
	PartsReplaced     pgtype.Text     `json:"parts_replaced"`
	IsCompleted       bool            `json:"is_completed"`
	Notes             pgtype.Text     `json:"notes"`
}

func (q *Queries) CreateEquipmentMaintenance(ctx context.Context, arg CreateEquipmentMaintenanceParams) (EquipmentMaintenance, error) {
	row := q.db.QueryRow(ctx, createEquipmentMaintenance,
		arg.HospitalID,
		arg.EquipmentID,
		arg.MaintenanceType,
		arg.ScheduledDate,
		arg.PerformedDate,
		arg.PerformedBy,
		arg.TechnicianName,
		arg.TechnicianCompany,
		arg.NextDueDate,
		arg.Cost,
		arg.Findings,
		arg.ActionsTaken,
		arg.PartsReplaced,
		arg.IsCompleted,
		arg.Notes,
	)
	var i EquipmentMaintenance
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.EquipmentID,
		&i.MaintenanceType,
		&i.ScheduledDate,
		&i.PerformedDate,
		&i.PerformedBy,
		&i.TechnicianName,
		&i.TechnicianCompany,
		&i.NextDueDate,
		&i.Cost,
		&i.Findings,
		&i.ActionsTaken,
		&i.PartsReplaced,
		&i.IsCompleted,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteEquipmentMaintenance = `-- name: DeleteEquipmentMaintenance :exec
UPDATE equipment_maintenance SET deleted_at = now() WHERE id = $1
`

func (q *Queries) DeleteEquipmentMaintenance(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEquipmentMaintenance, id)
	return err
}

const getEquipmentMaintenance = `-- name: GetEquipmentMaintenance :one
SELECT id, hospital_id, equipment_id, maintenance_type, scheduled_date, performed_date, performed_by, technician_name, technician_company, next_due_date, cost, findings, actions_taken, parts_replaced, is_completed, notes, created_at, updated_at, deleted_at FROM equipment_maintenance WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetEquipmentMaintenance(ctx context.Context, id uuid.UUID) (EquipmentMaintenance, error) {
	row := q.db.QueryRow(ctx, getEquipmentMaintenance, id)
	var i EquipmentMaintenance
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.EquipmentID,
		&i.MaintenanceType,
		&i.ScheduledDate,
		&i.PerformedDate,
		&i.PerformedBy,
		&i.TechnicianName,
		&i.TechnicianCompany,
		&i.NextDueDate,
		&i.Cost,
		&i.Findings,
		&i.ActionsTaken,
		&i.PartsReplaced,
		&i.IsCompleted,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listMaintenanceByEquipment = `-- name: ListMaintenanceByEquipment :many
SELECT id, hospital_id, equipment_id, maintenance_type, scheduled_date, performed_date, performed_by, technician_name, technician_company, next_due_date, cost, findings, actions_taken, parts_replaced, is_completed, notes, created_at, updated_at, deleted_at FROM equipment_maintenance
WHERE equipment_id = $1 AND deleted_at IS NULL
ORDER BY performed_date DESC NULLS LAST, scheduled_date DESC
`

func (q *Queries) ListMaintenanceByEquipment(ctx context.Context, equipmentID uuid.UUID) ([]EquipmentMaintenance, error) {
	rows, err := q.db.Query(ctx, listMaintenanceByEquipment, equipmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EquipmentMaintenance
	for rows.Next() {
		var i EquipmentMaintenance
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.EquipmentID,
			&i.MaintenanceType,
			&i.ScheduledDate,
			&i.PerformedDate,
			&i.PerformedBy,
			&i.TechnicianName,
			&i.TechnicianCompany,
			&i.NextDueDate,
			&i.Cost,
			&i.Findings,
			&i.ActionsTaken,
			&i.PartsReplaced,
			&i.IsCompleted,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverdueMaintenance = `-- name: ListOverdueMaintenance :many
SELECT id, hospital_id, equipment_id, maintenance_type, scheduled_date, performed_date, performed_by, technician_name, technician_company, next_due_date, cost, findings, actions_taken, parts_replaced, is_completed, notes, created_at, updated_at, deleted_at FROM equipment_maintenance
WHERE hospital_id = $1
  AND is_completed = FALSE
  AND next_due_date < CURRENT_DATE
  AND deleted_at IS NULL
ORDER BY next_due_date ASC
`

func (q *Queries) ListOverdueMaintenance(ctx context.Context, hospitalID uuid.UUID) ([]EquipmentMaintenance, error) {
	rows, err := q.db.Query(ctx, listOverdueMaintenance, hospitalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EquipmentMaintenance
	for rows.Next() {
		var i EquipmentMaintenance
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.EquipmentID,
			&i.MaintenanceType,
			&i.ScheduledDate,
			&i.PerformedDate,
			&i.PerformedBy,
			&i.TechnicianName,
			&i.TechnicianCompany,
			&i.NextDueDate,
			&i.Cost,
			&i.Findings,
			&i.ActionsTaken,
			&i.PartsReplaced,
			&i.IsCompleted,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingMaintenance = `-- name: ListUpcomingMaintenance :many
SELECT id, hospital_id, equipment_id, maintenance_type, scheduled_date, performed_date, performed_by, technician_name, technician_company, next_due_date, cost, findings, actions_taken, parts_replaced, is_completed, notes, created_at, updated_at, deleted_at FROM equipment_maintenance
WHERE hospital_id = $1 AND is_completed = FALSE AND deleted_at IS NULL
ORDER BY next_due_date ASC NULLS LAST, scheduled_date ASC
`

func (q *Queries) ListUpcomingMaintenance(ctx context.Context, hospitalID uuid.UUID) ([]EquipmentMaintenance, error) {
	rows, err := q.db.Query(ctx, listUpcomingMaintenance, hospitalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EquipmentMaintenance
	for rows.Next() {
		var i EquipmentMaintenance
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.EquipmentID,
			&i.MaintenanceType,
			&i.ScheduledDate,
			&i.PerformedDate,
			&i.PerformedBy,
			&i.TechnicianName,
			&i.TechnicianCompany,
			&i.NextDueDate,
			&i.Cost,
			&i.Findings,
			&i.ActionsTaken,
			&i.PartsReplaced,
			&i.IsCompleted,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
