// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: equipment_certifications.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEquipmentCertification = `-- name: CreateEquipmentCertification :one
INSERT INTO equipment_certifications (
    hospital_id, equipment_id, certification_type, certificate_number,
    issued_by, issued_date, valid_from, valid_until, document_url,
    file_attachment_id, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, hospital_id, equipment_id, certification_type, certificate_number, issued_by, issued_date, valid_from, valid_until, document_url, file_attachment_id, notes, is_active, created_at, updated_at, deleted_at
`

type CreateEquipmentCertificationParams struct {
	HospitalID        uuid.UUID         `json:"hospital_id"`
	EquipmentID       uuid.UUID         `json:"equipment_id"`
	CertificationType CertificationType `json:"certification_type"`
	CertificateNumber pgtype.Text       `json:"certificate_number"`
	IssuedBy          string            `json:"issued_by"`
	IssuedDate        pgtype.Date       `json:"issued_date"`
	ValidFrom         pgtype.Date       `json:"valid_from"`
	ValidUntil        pgtype.Date       `json:"valid_until"`
	DocumentUrl       pgtype.Text       `json:"document_url"`
	FileAttachmentID  pgtype.UUID       `json:"file_attachment_id"`
	Notes             pgtype.Text       `json:"notes"`
}

func (q *Queries) CreateEquipmentCertification(ctx context.Context, arg CreateEquipmentCertificationParams) (EquipmentCertification, error) {
	row := q.db.QueryRow(ctx, createEquipmentCertification,
		arg.HospitalID,
		arg.EquipmentID,
		arg.CertificationType,
		arg.CertificateNumber,
		arg.IssuedBy,
		arg.IssuedDate,
		arg.ValidFrom,
		arg.ValidUntil,
		arg.DocumentUrl,
		arg.FileAttachmentID,
		arg.Notes,
	)
	var i EquipmentCertification
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.EquipmentID,
		&i.CertificationType,
		&i.CertificateNumber,
		&i.IssuedBy,
		&i.IssuedDate,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.DocumentUrl,
		&i.FileAttachmentID,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteEquipmentCertification = `-- name: DeleteEquipmentCertification :exec
UPDATE equipment_certifications SET deleted_at = now() WHERE id = $1
`

func (q *Queries) DeleteEquipmentCertification(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEquipmentCertification, id)
	return err
}

const getEquipmentCertification = `-- name: GetEquipmentCertification :one
SELECT id, hospital_id, equipment_id, certification_type, certificate_number, issued_by, issued_date, valid_from, valid_until, document_url, file_attachment_id, notes, is_active, created_at, updated_at, deleted_at FROM equipment_certifications WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetEquipmentCertification(ctx context.Context, id uuid.UUID) (EquipmentCertification, error) {
	row := q.db.QueryRow(ctx, getEquipmentCertification, id)
	var i EquipmentCertification
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.EquipmentID,
		&i.CertificationType,
		&i.CertificateNumber,
		&i.IssuedBy,
		&i.IssuedDate,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.DocumentUrl,
		&i.FileAttachmentID,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listActiveCertifications = `-- name: ListActiveCertifications :many
SELECT id, hospital_id, equipment_id, certification_type, certificate_number, issued_by, issued_date, valid_from, valid_until, document_url, file_attachment_id, notes, is_active, created_at, updated_at, deleted_at FROM equipment_certifications
WHERE hospital_id = $1 AND is_active = TRUE AND deleted_at IS NULL
ORDER BY valid_until ASC
`

func (q *Queries) ListActiveCertifications(ctx context.Context, hospitalID uuid.UUID) ([]EquipmentCertification, error) {
	rows, err := q.db.Query(ctx, listActiveCertifications, hospitalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EquipmentCertification
	for rows.Next() {
		var i EquipmentCertification
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.EquipmentID,
			&i.CertificationType,
			&i.CertificateNumber,
			&i.IssuedBy,
			&i.IssuedDate,
			&i.ValidFrom,
			&i.ValidUntil,
			&i.DocumentUrl,
			&i.FileAttachmentID,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCertificationsByEquipment = `-- name: ListCertificationsByEquipment :many
SELECT id, hospital_id, equipment_id, certification_type, certificate_number, issued_by, issued_date, valid_from, valid_until, document_url, file_attachment_id, notes, is_active, created_at, updated_at, deleted_at FROM equipment_certifications
WHERE equipment_id = $1 AND deleted_at IS NULL
ORDER BY valid_until DESC
`

func (q *Queries) ListCertificationsByEquipment(ctx context.Context, equipmentID uuid.UUID) ([]EquipmentCertification, error) {
	rows, err := q.db.Query(ctx, listCertificationsByEquipment, equipmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EquipmentCertification
	for rows.Next() {
		var i EquipmentCertification
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.EquipmentID,
			&i.CertificationType,
			&i.CertificateNumber,
			&i.IssuedBy,
			&i.IssuedDate,
			&i.ValidFrom,
			&i.ValidUntil,
			&i.DocumentUrl,
			&i.FileAttachmentID,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCertificationsByType = `-- name: ListCertificationsByType :many
SELECT id, hospital_id, equipment_id, certification_type, certificate_number, issued_by, issued_date, valid_from, valid_until, document_url, file_attachment_id, notes, is_active, created_at, updated_at, deleted_at FROM equipment_certifications
WHERE hospital_id = $1 AND certification_type = $2 AND deleted_at IS NULL
ORDER BY valid_until DESC
`

type ListCertificationsByTypeParams struct {
	HospitalID        uuid.UUID         `json:"hospital_id"`
	CertificationType CertificationType `json:"certification_type"`
}

func (q *Queries) ListCertificationsByType(ctx context.Context, arg ListCertificationsByTypeParams) ([]EquipmentCertification, error) {
	rows, err := q.db.Query(ctx, listCertificationsByType, arg.HospitalID, arg.CertificationType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EquipmentCertification
	for rows.Next() {
		var i EquipmentCertification
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.EquipmentID,
			&i.CertificationType,
			&i.CertificateNumber,
			&i.IssuedBy,
			&i.IssuedDate,
			&i.ValidFrom,
			&i.ValidUntil,
			&i.DocumentUrl,
			&i.FileAttachmentID,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiringCertifications = `-- name: ListExpiringCertifications :many
SELECT c.id, c.hospital_id, c.equipment_id, c.certification_type, c.certificate_number, c.issued_by, c.issued_date, c.valid_from, c.valid_until, c.document_url, c.file_attachment_id, c.notes, c.is_active, c.created_at, c.updated_at, c.deleted_at, e.name AS equipment_name
FROM equipment_certifications c
JOIN equipment e ON c.equipment_id = e.id
WHERE c.hospital_id = $1
  AND c.valid_until <= $2
  AND c.is_active = TRUE
  AND c.deleted_at IS NULL
ORDER BY c.valid_until ASC
`

type ListExpiringCertificationsParams struct {
	HospitalID uuid.UUID   `json:"hospital_id"`
	ValidUntil pgtype.Date `json:"valid_until"`
}

type ListExpiringCertificationsRow struct {
	ID                uuid.UUID          `json:"id"`
	HospitalID        uuid.UUID          `json:"hospital_id"`
	EquipmentID       uuid.UUID          `json:"equipment_id"`
	CertificationType CertificationType  `json:"certification_type"`
	CertificateNumber pgtype.Text        `json:"certificate_number"`
	IssuedBy          string             `json:"issued_by"`
	IssuedDate        pgtype.Date        `json:"issued_date"`
	ValidFrom         pgtype.Date        `json:"valid_from"`
	ValidUntil        pgtype.Date        `json:"valid_until"`
	DocumentUrl       pgtype.Text        `json:"document_url"`
	FileAttachmentID  pgtype.UUID        `json:"file_attachment_id"`
	Notes             pgtype.Text        `json:"notes"`
	IsActive          bool               `json:"is_active"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	EquipmentName     string             `json:"equipment_name"`
}

func (q *Queries) ListExpiringCertifications(ctx context.Context, arg ListExpiringCertificationsParams) ([]ListExpiringCertificationsRow, error) {
	rows, err := q.db.Query(ctx, listExpiringCertifications, arg.HospitalID, arg.ValidUntil)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpiringCertificationsRow
	for rows.Next() {
		var i ListExpiringCertificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.EquipmentID,
			&i.CertificationType,
			&i.CertificateNumber,
			&i.IssuedBy,
			&i.IssuedDate,
			&i.ValidFrom,
			&i.ValidUntil,
			&i.DocumentUrl,
			&i.FileAttachmentID,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.EquipmentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
