// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: equipment.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEquipment = `-- name: CreateEquipment :one
INSERT INTO equipment (
    hospital_id, name, category, serial_number, model, manufacturer,
    purchase_date, purchase_cost, warranty_expiry_date, status,
    location, department_id, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, hospital_id, name, category, serial_number, model, manufacturer, purchase_date, purchase_cost, warranty_expiry_date, status, location, department_id, notes, is_active, created_at, updated_at, deleted_at
`

type CreateEquipmentParams struct {
	HospitalID         uuid.UUID         `json:"hospital_id"`
	Name               string            `json:"name"`
	Category           EquipmentCategory `json:"category"`
	SerialNumber       pgtype.Text       `json:"serial_number"`
	Model              pgtype.Text       `json:"model"`
	Manufacturer       pgtype.Text       `json:"manufacturer"`
	PurchaseDate       pgtype.Date       `json:"purchase_date"`
	PurchaseCost       pgtype.Numeric    `json:"purchase_cost"`
	WarrantyExpiryDate pgtype.Date       `json:"warranty_expiry_date"`
	Status             EquipmentStatus   `json:"status"`
	Location           pgtype.Text       `json:"location"`
	DepartmentID       pgtype.UUID       `json:"department_id"`
	Notes              pgtype.Text       `json:"notes"`
}

func (q *Queries) CreateEquipment(ctx context.Context, arg CreateEquipmentParams) (Equipment, error) {
	row := q.db.QueryRow(ctx, createEquipment,
		arg.HospitalID,
		arg.Name,
		arg.Category,
		arg.SerialNumber,
		arg.Model,
		arg.Manufacturer,
		arg.PurchaseDate,
		arg.PurchaseCost,
		arg.WarrantyExpiryDate,
		arg.Status,
		arg.Location,
		arg.DepartmentID,
		arg.Notes,
	)
	var i Equipment
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.Name,
		&i.Category,
		&i.SerialNumber,
		&i.Model,
		&i.Manufacturer,
		&i.PurchaseDate,
		&i.PurchaseCost,
		&i.WarrantyExpiryDate,
		&i.Status,
		&i.Location,
		&i.DepartmentID,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteEquipment = `-- name: DeleteEquipment :exec
UPDATE equipment SET deleted_at = now() WHERE id = $1
`

func (q *Queries) DeleteEquipment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEquipment, id)
	return err
}

const getEquipment = `-- name: GetEquipment :one
SELECT id, hospital_id, name, category, serial_number, model, manufacturer, purchase_date, purchase_cost, warranty_expiry_date, status, location, department_id, notes, is_active, created_at, updated_at, deleted_at FROM equipment WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetEquipment(ctx context.Context, id uuid.UUID) (Equipment, error) {
	row := q.db.QueryRow(ctx, getEquipment, id)
	var i Equipment
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.Name,
		&i.Category,
		&i.SerialNumber,
		&i.Model,
		&i.Manufacturer,
		&i.PurchaseDate,
		&i.PurchaseCost,
		&i.WarrantyExpiryDate,
		&i.Status,
		&i.Location,
		&i.DepartmentID,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listEquipmentByCategory = `-- name: ListEquipmentByCategory :many
SELECT id, hospital_id, name, category, serial_number, model, manufacturer, purchase_date, purchase_cost, warranty_expiry_date, status, location, department_id, notes, is_active, created_at, updated_at, deleted_at FROM equipment
WHERE hospital_id = $1 AND category = $2 AND deleted_at IS NULL
ORDER BY name
`

type ListEquipmentByCategoryParams struct {
	HospitalID uuid.UUID         `json:"hospital_id"`
	Category   EquipmentCategory `json:"category"`
}

func (q *Queries) ListEquipmentByCategory(ctx context.Context, arg ListEquipmentByCategoryParams) ([]Equipment, error) {
	rows, err := q.db.Query(ctx, listEquipmentByCategory, arg.HospitalID, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Equipment
	for rows.Next() {
		var i Equipment
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.Name,
			&i.Category,
			&i.SerialNumber,
			&i.Model,
			&i.Manufacturer,
			&i.PurchaseDate,
			&i.PurchaseCost,
			&i.WarrantyExpiryDate,
			&i.Status,
			&i.Location,
			&i.DepartmentID,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEquipmentByDepartment = `-- name: ListEquipmentByDepartment :many
SELECT id, hospital_id, name, category, serial_number, model, manufacturer, purchase_date, purchase_cost, warranty_expiry_date, status, location, department_id, notes, is_active, created_at, updated_at, deleted_at FROM equipment
WHERE department_id = $1 AND deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListEquipmentByDepartment(ctx context.Context, departmentID pgtype.UUID) ([]Equipment, error) {
	rows, err := q.db.Query(ctx, listEquipmentByDepartment, departmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Equipment
	for rows.Next() {
		var i Equipment
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.Name,
			&i.Category,
			&i.SerialNumber,
			&i.Model,
			&i.Manufacturer,
			&i.PurchaseDate,
			&i.PurchaseCost,
			&i.WarrantyExpiryDate,
			&i.Status,
			&i.Location,
			&i.DepartmentID,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEquipmentByHospital = `-- name: ListEquipmentByHospital :many
SELECT id, hospital_id, name, category, serial_number, model, manufacturer, purchase_date, purchase_cost, warranty_expiry_date, status, location, department_id, notes, is_active, created_at, updated_at, deleted_at FROM equipment
WHERE hospital_id = $1 AND deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListEquipmentByHospital(ctx context.Context, hospitalID uuid.UUID) ([]Equipment, error) {
	rows, err := q.db.Query(ctx, listEquipmentByHospital, hospitalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Equipment
	for rows.Next() {
		var i Equipment
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.Name,
			&i.Category,
			&i.SerialNumber,
			&i.Model,
			&i.Manufacturer,
			&i.PurchaseDate,
			&i.PurchaseCost,
			&i.WarrantyExpiryDate,
			&i.Status,
			&i.Location,
			&i.DepartmentID,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEquipmentByStatus = `-- name: ListEquipmentByStatus :many
SELECT id, hospital_id, name, category, serial_number, model, manufacturer, purchase_date, purchase_cost, warranty_expiry_date, status, location, department_id, notes, is_active, created_at, updated_at, deleted_at FROM equipment
WHERE hospital_id = $1 AND status = $2 AND deleted_at IS NULL
ORDER BY name
`

type ListEquipmentByStatusParams struct {
	HospitalID uuid.UUID       `json:"hospital_id"`
	Status     EquipmentStatus `json:"status"`
}

func (q *Queries) ListEquipmentByStatus(ctx context.Context, arg ListEquipmentByStatusParams) ([]Equipment, error) {
	rows, err := q.db.Query(ctx, listEquipmentByStatus, arg.HospitalID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Equipment
	for rows.Next() {
		var i Equipment
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.Name,
			&i.Category,
			&i.SerialNumber,
			&i.Model,
			&i.Manufacturer,
			&i.PurchaseDate,
			&i.PurchaseCost,
			&i.WarrantyExpiryDate,
			&i.Status,
			&i.Location,
			&i.DepartmentID,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEquipmentStatus = `-- name: UpdateEquipmentStatus :one
UPDATE equipment
SET status = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, hospital_id, name, category, serial_number, model, manufacturer, purchase_date, purchase_cost, warranty_expiry_date, status, location, department_id, notes, is_active, created_at, updated_at, deleted_at
`

type UpdateEquipmentStatusParams struct {
	ID     uuid.UUID       `json:"id"`
	Status EquipmentStatus `json:"status"`
}

func (q *Queries) UpdateEquipmentStatus(ctx context.Context, arg UpdateEquipmentStatusParams) (Equipment, error) {
	row := q.db.QueryRow(ctx, updateEquipmentStatus, arg.ID, arg.Status)
	var i Equipment
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.Name,
		&i.Category,
		&i.SerialNumber,
		&i.Model,
		&i.Manufacturer,
		&i.PurchaseDate,
		&i.PurchaseCost,
		&i.WarrantyExpiryDate,
		&i.Status,
		&i.Location,
		&i.DepartmentID,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
