// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: file_attachments.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createFileAttachment = `-- name: CreateFileAttachment :one
INSERT INTO file_attachments (
  hospital_id, uploaded_by, entity_type, entity_id, file_name, file_path, mime_type, file_size_bytes, description, is_sensitive
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, hospital_id, uploaded_by, entity_type, entity_id, file_name, file_path, mime_type, file_size_bytes, description, is_sensitive, created_at, updated_at, deleted_at
`

type CreateFileAttachmentParams struct {
	HospitalID    uuid.UUID   `json:"hospital_id"`
	UploadedBy    uuid.UUID   `json:"uploaded_by"`
	EntityType    string      `json:"entity_type"`
	EntityID      uuid.UUID   `json:"entity_id"`
	FileName      string      `json:"file_name"`
	FilePath      string      `json:"file_path"`
	MimeType      string      `json:"mime_type"`
	FileSizeBytes pgtype.Int8 `json:"file_size_bytes"`
	Description   pgtype.Text `json:"description"`
	IsSensitive   bool        `json:"is_sensitive"`
}

func (q *Queries) CreateFileAttachment(ctx context.Context, arg CreateFileAttachmentParams) (FileAttachment, error) {
	row := q.db.QueryRow(ctx, createFileAttachment,
		arg.HospitalID,
		arg.UploadedBy,
		arg.EntityType,
		arg.EntityID,
		arg.FileName,
		arg.FilePath,
		arg.MimeType,
		arg.FileSizeBytes,
		arg.Description,
		arg.IsSensitive,
	)
	var i FileAttachment
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.UploadedBy,
		&i.EntityType,
		&i.EntityID,
		&i.FileName,
		&i.FilePath,
		&i.MimeType,
		&i.FileSizeBytes,
		&i.Description,
		&i.IsSensitive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getFileAttachment = `-- name: GetFileAttachment :one
SELECT id, hospital_id, uploaded_by, entity_type, entity_id, file_name, file_path, mime_type, file_size_bytes, description, is_sensitive, created_at, updated_at, deleted_at FROM file_attachments
WHERE id = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetFileAttachment(ctx context.Context, id uuid.UUID) (FileAttachment, error) {
	row := q.db.QueryRow(ctx, getFileAttachment, id)
	var i FileAttachment
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.UploadedBy,
		&i.EntityType,
		&i.EntityID,
		&i.FileName,
		&i.FilePath,
		&i.MimeType,
		&i.FileSizeBytes,
		&i.Description,
		&i.IsSensitive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listFileAttachmentsByEntity = `-- name: ListFileAttachmentsByEntity :many
SELECT id, hospital_id, uploaded_by, entity_type, entity_id, file_name, file_path, mime_type, file_size_bytes, description, is_sensitive, created_at, updated_at, deleted_at FROM file_attachments
WHERE entity_type = $1 AND entity_id = $2 AND deleted_at IS NULL
ORDER BY created_at DESC
`

type ListFileAttachmentsByEntityParams struct {
	EntityType string    `json:"entity_type"`
	EntityID   uuid.UUID `json:"entity_id"`
}

func (q *Queries) ListFileAttachmentsByEntity(ctx context.Context, arg ListFileAttachmentsByEntityParams) ([]FileAttachment, error) {
	rows, err := q.db.Query(ctx, listFileAttachmentsByEntity, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileAttachment
	for rows.Next() {
		var i FileAttachment
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.UploadedBy,
			&i.EntityType,
			&i.EntityID,
			&i.FileName,
			&i.FilePath,
			&i.MimeType,
			&i.FileSizeBytes,
			&i.Description,
			&i.IsSensitive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFileAttachmentsByHospital = `-- name: ListFileAttachmentsByHospital :many
SELECT id, hospital_id, uploaded_by, entity_type, entity_id, file_name, file_path, mime_type, file_size_bytes, description, is_sensitive, created_at, updated_at, deleted_at FROM file_attachments
WHERE hospital_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListFileAttachmentsByHospitalParams struct {
	HospitalID uuid.UUID `json:"hospital_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListFileAttachmentsByHospital(ctx context.Context, arg ListFileAttachmentsByHospitalParams) ([]FileAttachment, error) {
	rows, err := q.db.Query(ctx, listFileAttachmentsByHospital, arg.HospitalID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileAttachment
	for rows.Next() {
		var i FileAttachment
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.UploadedBy,
			&i.EntityType,
			&i.EntityID,
			&i.FileName,
			&i.FilePath,
			&i.MimeType,
			&i.FileSizeBytes,
			&i.Description,
			&i.IsSensitive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteFileAttachment = `-- name: SoftDeleteFileAttachment :exec
UPDATE file_attachments
SET deleted_at = now()
WHERE id = $1
`

func (q *Queries) SoftDeleteFileAttachment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteFileAttachment, id)
	return err
}
