// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hospitals.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createHospital = `-- name: CreateHospital :one
INSERT INTO hospitals (
  name, short_code, tier, region, country, address, phone, email, license_no, license_expiry, settings
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, name, short_code, tier, region, country, address, phone, email, license_no, license_expiry, is_active, settings, created_at, updated_at, deleted_at
`

type CreateHospitalParams struct {
	Name          string      `json:"name"`
	ShortCode     string      `json:"short_code"`
	Tier          string      `json:"tier"`
	Region        string      `json:"region"`
	Country       string      `json:"country"`
	Address       pgtype.Text `json:"address"`
	Phone         pgtype.Text `json:"phone"`
	Email         pgtype.Text `json:"email"`
	LicenseNo     pgtype.Text `json:"license_no"`
	LicenseExpiry pgtype.Date `json:"license_expiry"`
	Settings      []byte      `json:"settings"`
}

func (q *Queries) CreateHospital(ctx context.Context, arg CreateHospitalParams) (Hospital, error) {
	row := q.db.QueryRow(ctx, createHospital,
		arg.Name,
		arg.ShortCode,
		arg.Tier,
		arg.Region,
		arg.Country,
		arg.Address,
		arg.Phone,
		arg.Email,
		arg.LicenseNo,
		arg.LicenseExpiry,
		arg.Settings,
	)
	var i Hospital
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShortCode,
		&i.Tier,
		&i.Region,
		&i.Country,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.LicenseNo,
		&i.LicenseExpiry,
		&i.IsActive,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getHospital = `-- name: GetHospital :one
SELECT id, name, short_code, tier, region, country, address, phone, email, license_no, license_expiry, is_active, settings, created_at, updated_at, deleted_at FROM hospitals
WHERE id = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetHospital(ctx context.Context, id uuid.UUID) (Hospital, error) {
	row := q.db.QueryRow(ctx, getHospital, id)
	var i Hospital
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShortCode,
		&i.Tier,
		&i.Region,
		&i.Country,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.LicenseNo,
		&i.LicenseExpiry,
		&i.IsActive,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listHospitals = `-- name: ListHospitals :many
SELECT id, name, short_code, tier, region, country, address, phone, email, license_no, license_expiry, is_active, settings, created_at, updated_at, deleted_at FROM hospitals
WHERE deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListHospitals(ctx context.Context) ([]Hospital, error) {
	rows, err := q.db.Query(ctx, listHospitals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Hospital
	for rows.Next() {
		var i Hospital
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ShortCode,
			&i.Tier,
			&i.Region,
			&i.Country,
			&i.Address,
			&i.Phone,
			&i.Email,
			&i.LicenseNo,
			&i.LicenseExpiry,
			&i.IsActive,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteHospital = `-- name: SoftDeleteHospital :exec
UPDATE hospitals
SET deleted_at = now()
WHERE id = $1
`

func (q *Queries) SoftDeleteHospital(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteHospital, id)
	return err
}

const updateHospital = `-- name: UpdateHospital :one
UPDATE hospitals
SET name = $2, tier = $3, region = $4, address = $5, phone = $6, email = $7
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, short_code, tier, region, country, address, phone, email, license_no, license_expiry, is_active, settings, created_at, updated_at, deleted_at
`

type UpdateHospitalParams struct {
	ID      uuid.UUID   `json:"id"`
	Name    string      `json:"name"`
	Tier    string      `json:"tier"`
	Region  string      `json:"region"`
	Address pgtype.Text `json:"address"`
	Phone   pgtype.Text `json:"phone"`
	Email   pgtype.Text `json:"email"`
}

func (q *Queries) UpdateHospital(ctx context.Context, arg UpdateHospitalParams) (Hospital, error) {
	row := q.db.QueryRow(ctx, updateHospital,
		arg.ID,
		arg.Name,
		arg.Tier,
		arg.Region,
		arg.Address,
		arg.Phone,
		arg.Email,
	)
	var i Hospital
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShortCode,
		&i.Tier,
		&i.Region,
		&i.Country,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.LicenseNo,
		&i.LicenseExpiry,
		&i.IsActive,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
