// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: insurance_schemes.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createInsuranceScheme = `-- name: CreateInsuranceScheme :one
INSERT INTO insurance_schemes (
    hospital_id, name, short_code, country, covers_dialysis,
    reimbursement_rate, requires_pre_authorization,
    claim_submission_url, contact_person, contact_phone,
    contact_email, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, hospital_id, name, short_code, country, covers_dialysis, reimbursement_rate, requires_pre_authorization, claim_submission_url, contact_person, contact_phone, contact_email, notes, is_active, created_at, updated_at, deleted_at
`

type CreateInsuranceSchemeParams struct {
	HospitalID               uuid.UUID      `json:"hospital_id"`
	Name                     string         `json:"name"`
	ShortCode                pgtype.Text    `json:"short_code"`
	Country                  pgtype.Text    `json:"country"`
	CoversDialysis           bool           `json:"covers_dialysis"`
	ReimbursementRate        pgtype.Numeric `json:"reimbursement_rate"`
	RequiresPreAuthorization bool           `json:"requires_pre_authorization"`
	ClaimSubmissionUrl       pgtype.Text    `json:"claim_submission_url"`
	ContactPerson            pgtype.Text    `json:"contact_person"`
	ContactPhone             pgtype.Text    `json:"contact_phone"`
	ContactEmail             pgtype.Text    `json:"contact_email"`
	Notes                    pgtype.Text    `json:"notes"`
}

func (q *Queries) CreateInsuranceScheme(ctx context.Context, arg CreateInsuranceSchemeParams) (InsuranceScheme, error) {
	row := q.db.QueryRow(ctx, createInsuranceScheme,
		arg.HospitalID,
		arg.Name,
		arg.ShortCode,
		arg.Country,
		arg.CoversDialysis,
		arg.ReimbursementRate,
		arg.RequiresPreAuthorization,
		arg.ClaimSubmissionUrl,
		arg.ContactPerson,
		arg.ContactPhone,
		arg.ContactEmail,
		arg.Notes,
	)
	var i InsuranceScheme
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.Name,
		&i.ShortCode,
		&i.Country,
		&i.CoversDialysis,
		&i.ReimbursementRate,
		&i.RequiresPreAuthorization,
		&i.ClaimSubmissionUrl,
		&i.ContactPerson,
		&i.ContactPhone,
		&i.ContactEmail,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteInsuranceScheme = `-- name: DeleteInsuranceScheme :exec
UPDATE insurance_schemes SET deleted_at = now() WHERE id = $1
`

func (q *Queries) DeleteInsuranceScheme(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteInsuranceScheme, id)
	return err
}

const getInsuranceScheme = `-- name: GetInsuranceScheme :one
SELECT id, hospital_id, name, short_code, country, covers_dialysis, reimbursement_rate, requires_pre_authorization, claim_submission_url, contact_person, contact_phone, contact_email, notes, is_active, created_at, updated_at, deleted_at FROM insurance_schemes WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetInsuranceScheme(ctx context.Context, id uuid.UUID) (InsuranceScheme, error) {
	row := q.db.QueryRow(ctx, getInsuranceScheme, id)
	var i InsuranceScheme
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.Name,
		&i.ShortCode,
		&i.Country,
		&i.CoversDialysis,
		&i.ReimbursementRate,
		&i.RequiresPreAuthorization,
		&i.ClaimSubmissionUrl,
		&i.ContactPerson,
		&i.ContactPhone,
		&i.ContactEmail,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listActiveInsuranceSchemes = `-- name: ListActiveInsuranceSchemes :many
SELECT id, hospital_id, name, short_code, country, covers_dialysis, reimbursement_rate, requires_pre_authorization, claim_submission_url, contact_person, contact_phone, contact_email, notes, is_active, created_at, updated_at, deleted_at FROM insurance_schemes
WHERE hospital_id = $1 AND is_active = TRUE AND deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListActiveInsuranceSchemes(ctx context.Context, hospitalID uuid.UUID) ([]InsuranceScheme, error) {
	rows, err := q.db.Query(ctx, listActiveInsuranceSchemes, hospitalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InsuranceScheme
	for rows.Next() {
		var i InsuranceScheme
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.Name,
			&i.ShortCode,
			&i.Country,
			&i.CoversDialysis,
			&i.ReimbursementRate,
			&i.RequiresPreAuthorization,
			&i.ClaimSubmissionUrl,
			&i.ContactPerson,
			&i.ContactPhone,
			&i.ContactEmail,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInsuranceSchemesByHospital = `-- name: ListInsuranceSchemesByHospital :many
SELECT id, hospital_id, name, short_code, country, covers_dialysis, reimbursement_rate, requires_pre_authorization, claim_submission_url, contact_person, contact_phone, contact_email, notes, is_active, created_at, updated_at, deleted_at FROM insurance_schemes
WHERE hospital_id = $1 AND deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListInsuranceSchemesByHospital(ctx context.Context, hospitalID uuid.UUID) ([]InsuranceScheme, error) {
	rows, err := q.db.Query(ctx, listInsuranceSchemesByHospital, hospitalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InsuranceScheme
	for rows.Next() {
		var i InsuranceScheme
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.Name,
			&i.ShortCode,
			&i.Country,
			&i.CoversDialysis,
			&i.ReimbursementRate,
			&i.RequiresPreAuthorization,
			&i.ClaimSubmissionUrl,
			&i.ContactPerson,
			&i.ContactPhone,
			&i.ContactEmail,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchemesByCountry = `-- name: ListSchemesByCountry :many
SELECT id, hospital_id, name, short_code, country, covers_dialysis, reimbursement_rate, requires_pre_authorization, claim_submission_url, contact_person, contact_phone, contact_email, notes, is_active, created_at, updated_at, deleted_at FROM insurance_schemes
WHERE hospital_id = $1 AND country = $2 AND deleted_at IS NULL
ORDER BY name
`

type ListSchemesByCountryParams struct {
	HospitalID uuid.UUID   `json:"hospital_id"`
	Country    pgtype.Text `json:"country"`
}

func (q *Queries) ListSchemesByCountry(ctx context.Context, arg ListSchemesByCountryParams) ([]InsuranceScheme, error) {
	rows, err := q.db.Query(ctx, listSchemesByCountry, arg.HospitalID, arg.Country)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InsuranceScheme
	for rows.Next() {
		var i InsuranceScheme
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.Name,
			&i.ShortCode,
			&i.Country,
			&i.CoversDialysis,
			&i.ReimbursementRate,
			&i.RequiresPreAuthorization,
			&i.ClaimSubmissionUrl,
			&i.ContactPerson,
			&i.ContactPhone,
			&i.ContactEmail,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInsuranceScheme = `-- name: UpdateInsuranceScheme :one
UPDATE insurance_schemes
SET name = $2, covers_dialysis = $3, reimbursement_rate = $4,
    contact_person = $5, contact_phone = $6, contact_email = $7
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, hospital_id, name, short_code, country, covers_dialysis, reimbursement_rate, requires_pre_authorization, claim_submission_url, contact_person, contact_phone, contact_email, notes, is_active, created_at, updated_at, deleted_at
`

type UpdateInsuranceSchemeParams struct {
	ID                uuid.UUID      `json:"id"`
	Name              string         `json:"name"`
	CoversDialysis    bool           `json:"covers_dialysis"`
	ReimbursementRate pgtype.Numeric `json:"reimbursement_rate"`
	ContactPerson     pgtype.Text    `json:"contact_person"`
	ContactPhone      pgtype.Text    `json:"contact_phone"`
	ContactEmail      pgtype.Text    `json:"contact_email"`
}

func (q *Queries) UpdateInsuranceScheme(ctx context.Context, arg UpdateInsuranceSchemeParams) (InsuranceScheme, error) {
	row := q.db.QueryRow(ctx, updateInsuranceScheme,
		arg.ID,
		arg.Name,
		arg.CoversDialysis,
		arg.ReimbursementRate,
		arg.ContactPerson,
		arg.ContactPhone,
		arg.ContactEmail,
	)
	var i InsuranceScheme
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.Name,
		&i.ShortCode,
		&i.Country,
		&i.CoversDialysis,
		&i.ReimbursementRate,
		&i.RequiresPreAuthorization,
		&i.ClaimSubmissionUrl,
		&i.ContactPerson,
		&i.ContactPhone,
		&i.ContactEmail,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
