// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invoice_items.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createInvoiceItem = `-- name: CreateInvoiceItem :one
INSERT INTO invoice_items (
    hospital_id, invoice_id, price_list_id, service_name, service_code,
    quantity, unit_price, discount_amount, tax_amount, total_amount,
    is_claimed, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, hospital_id, invoice_id, price_list_id, service_name, service_code, quantity, unit_price, discount_amount, tax_amount, total_amount, is_claimed, notes, created_at, updated_at, deleted_at
`

type CreateInvoiceItemParams struct {
	HospitalID     uuid.UUID      `json:"hospital_id"`
	InvoiceID      uuid.UUID      `json:"invoice_id"`
	PriceListID    pgtype.UUID    `json:"price_list_id"`
	ServiceName    string         `json:"service_name"`
	ServiceCode    pgtype.Text    `json:"service_code"`
	Quantity       int32          `json:"quantity"`
	UnitPrice      pgtype.Numeric `json:"unit_price"`
	DiscountAmount pgtype.Numeric `json:"discount_amount"`
	TaxAmount      pgtype.Numeric `json:"tax_amount"`
	TotalAmount    pgtype.Numeric `json:"total_amount"`
	IsClaimed      bool           `json:"is_claimed"`
	Notes          pgtype.Text    `json:"notes"`
}

func (q *Queries) CreateInvoiceItem(ctx context.Context, arg CreateInvoiceItemParams) (InvoiceItem, error) {
	row := q.db.QueryRow(ctx, createInvoiceItem,
		arg.HospitalID,
		arg.InvoiceID,
		arg.PriceListID,
		arg.ServiceName,
		arg.ServiceCode,
		arg.Quantity,
		arg.UnitPrice,
		arg.DiscountAmount,
		arg.TaxAmount,
		arg.TotalAmount,
		arg.IsClaimed,
		arg.Notes,
	)
	var i InvoiceItem
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.InvoiceID,
		&i.PriceListID,
		&i.ServiceName,
		&i.ServiceCode,
		&i.Quantity,
		&i.UnitPrice,
		&i.DiscountAmount,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.IsClaimed,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteInvoiceItem = `-- name: DeleteInvoiceItem :exec
UPDATE invoice_items SET deleted_at = now() WHERE id = $1
`

func (q *Queries) DeleteInvoiceItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteInvoiceItem, id)
	return err
}

const getInvoiceItem = `-- name: GetInvoiceItem :one
SELECT id, hospital_id, invoice_id, price_list_id, service_name, service_code, quantity, unit_price, discount_amount, tax_amount, total_amount, is_claimed, notes, created_at, updated_at, deleted_at FROM invoice_items WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetInvoiceItem(ctx context.Context, id uuid.UUID) (InvoiceItem, error) {
	row := q.db.QueryRow(ctx, getInvoiceItem, id)
	var i InvoiceItem
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.InvoiceID,
		&i.PriceListID,
		&i.ServiceName,
		&i.ServiceCode,
		&i.Quantity,
		&i.UnitPrice,
		&i.DiscountAmount,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.IsClaimed,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listClaimedItems = `-- name: ListClaimedItems :many
SELECT id, hospital_id, invoice_id, price_list_id, service_name, service_code, quantity, unit_price, discount_amount, tax_amount, total_amount, is_claimed, notes, created_at, updated_at, deleted_at FROM invoice_items
WHERE hospital_id = $1 AND is_claimed = TRUE AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListClaimedItems(ctx context.Context, hospitalID uuid.UUID) ([]InvoiceItem, error) {
	rows, err := q.db.Query(ctx, listClaimedItems, hospitalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InvoiceItem
	for rows.Next() {
		var i InvoiceItem
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.InvoiceID,
			&i.PriceListID,
			&i.ServiceName,
			&i.ServiceCode,
			&i.Quantity,
			&i.UnitPrice,
			&i.DiscountAmount,
			&i.TaxAmount,
			&i.TotalAmount,
			&i.IsClaimed,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsByInvoice = `-- name: ListItemsByInvoice :many
SELECT id, hospital_id, invoice_id, price_list_id, service_name, service_code, quantity, unit_price, discount_amount, tax_amount, total_amount, is_claimed, notes, created_at, updated_at, deleted_at FROM invoice_items
WHERE invoice_id = $1 AND deleted_at IS NULL
ORDER BY created_at
`

func (q *Queries) ListItemsByInvoice(ctx context.Context, invoiceID uuid.UUID) ([]InvoiceItem, error) {
	rows, err := q.db.Query(ctx, listItemsByInvoice, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InvoiceItem
	for rows.Next() {
		var i InvoiceItem
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.InvoiceID,
			&i.PriceListID,
			&i.ServiceName,
			&i.ServiceCode,
			&i.Quantity,
			&i.UnitPrice,
			&i.DiscountAmount,
			&i.TaxAmount,
			&i.TotalAmount,
			&i.IsClaimed,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markItemAsClaimed = `-- name: MarkItemAsClaimed :one
UPDATE invoice_items
SET is_claimed = TRUE
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, hospital_id, invoice_id, price_list_id, service_name, service_code, quantity, unit_price, discount_amount, tax_amount, total_amount, is_claimed, notes, created_at, updated_at, deleted_at
`

func (q *Queries) MarkItemAsClaimed(ctx context.Context, id uuid.UUID) (InvoiceItem, error) {
	row := q.db.QueryRow(ctx, markItemAsClaimed, id)
	var i InvoiceItem
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.InvoiceID,
		&i.PriceListID,
		&i.ServiceName,
		&i.ServiceCode,
		&i.Quantity,
		&i.UnitPrice,
		&i.DiscountAmount,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.IsClaimed,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
