// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: iron_therapy_records.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createIronTherapyRecord = `-- name: CreateIronTherapyRecord :one
INSERT INTO iron_therapy_records (
    hospital_id, patient_id, session_id, administered_by, product, dose_mg,
    route, infusion_duration_mins, dilution, ferritin_at_time, ferritin_target_min,
    ferritin_target_max, tsat_at_time, hb_at_time, adverse_reaction,
    adverse_reaction_type, adverse_reaction_severity, treatment_given,
    test_dose_given, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20)
RETURNING id, hospital_id, patient_id, session_id, administered_by, administered_at, product, dose_mg, route, infusion_duration_mins, dilution, ferritin_at_time, ferritin_target_min, ferritin_target_max, tsat_at_time, hb_at_time, adverse_reaction, adverse_reaction_type, adverse_reaction_severity, treatment_given, test_dose_given, notes, created_at, updated_at, deleted_at
`

type CreateIronTherapyRecordParams struct {
	HospitalID              uuid.UUID       `json:"hospital_id"`
	PatientID               uuid.UUID       `json:"patient_id"`
	SessionID               pgtype.UUID     `json:"session_id"`
	AdministeredBy          uuid.UUID       `json:"administered_by"`
	Product                 string          `json:"product"`
	DoseMg                  int32           `json:"dose_mg"`
	Route                   MedicationRoute `json:"route"`
	InfusionDurationMins    pgtype.Int4     `json:"infusion_duration_mins"`
	Dilution                pgtype.Text     `json:"dilution"`
	FerritinAtTime          pgtype.Numeric  `json:"ferritin_at_time"`
	FerritinTargetMin       pgtype.Numeric  `json:"ferritin_target_min"`
	FerritinTargetMax       pgtype.Numeric  `json:"ferritin_target_max"`
	TsatAtTime              pgtype.Numeric  `json:"tsat_at_time"`
	HbAtTime                pgtype.Numeric  `json:"hb_at_time"`
	AdverseReaction         bool            `json:"adverse_reaction"`
	AdverseReactionType     pgtype.Text     `json:"adverse_reaction_type"`
	AdverseReactionSeverity pgtype.Text     `json:"adverse_reaction_severity"`
	TreatmentGiven          pgtype.Text     `json:"treatment_given"`
	TestDoseGiven           bool            `json:"test_dose_given"`
	Notes                   pgtype.Text     `json:"notes"`
}

func (q *Queries) CreateIronTherapyRecord(ctx context.Context, arg CreateIronTherapyRecordParams) (IronTherapyRecord, error) {
	row := q.db.QueryRow(ctx, createIronTherapyRecord,
		arg.HospitalID,
		arg.PatientID,
		arg.SessionID,
		arg.AdministeredBy,
		arg.Product,
		arg.DoseMg,
		arg.Route,
		arg.InfusionDurationMins,
		arg.Dilution,
		arg.FerritinAtTime,
		arg.FerritinTargetMin,
		arg.FerritinTargetMax,
		arg.TsatAtTime,
		arg.HbAtTime,
		arg.AdverseReaction,
		arg.AdverseReactionType,
		arg.AdverseReactionSeverity,
		arg.TreatmentGiven,
		arg.TestDoseGiven,
		arg.Notes,
	)
	var i IronTherapyRecord
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.PatientID,
		&i.SessionID,
		&i.AdministeredBy,
		&i.AdministeredAt,
		&i.Product,
		&i.DoseMg,
		&i.Route,
		&i.InfusionDurationMins,
		&i.Dilution,
		&i.FerritinAtTime,
		&i.FerritinTargetMin,
		&i.FerritinTargetMax,
		&i.TsatAtTime,
		&i.HbAtTime,
		&i.AdverseReaction,
		&i.AdverseReactionType,
		&i.AdverseReactionSeverity,
		&i.TreatmentGiven,
		&i.TestDoseGiven,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteIronTherapyRecord = `-- name: DeleteIronTherapyRecord :exec
UPDATE iron_therapy_records SET deleted_at = now() WHERE id = $1
`

func (q *Queries) DeleteIronTherapyRecord(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteIronTherapyRecord, id)
	return err
}

const getIronTherapyRecord = `-- name: GetIronTherapyRecord :one
SELECT id, hospital_id, patient_id, session_id, administered_by, administered_at, product, dose_mg, route, infusion_duration_mins, dilution, ferritin_at_time, ferritin_target_min, ferritin_target_max, tsat_at_time, hb_at_time, adverse_reaction, adverse_reaction_type, adverse_reaction_severity, treatment_given, test_dose_given, notes, created_at, updated_at, deleted_at FROM iron_therapy_records WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetIronTherapyRecord(ctx context.Context, id uuid.UUID) (IronTherapyRecord, error) {
	row := q.db.QueryRow(ctx, getIronTherapyRecord, id)
	var i IronTherapyRecord
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.PatientID,
		&i.SessionID,
		&i.AdministeredBy,
		&i.AdministeredAt,
		&i.Product,
		&i.DoseMg,
		&i.Route,
		&i.InfusionDurationMins,
		&i.Dilution,
		&i.FerritinAtTime,
		&i.FerritinTargetMin,
		&i.FerritinTargetMax,
		&i.TsatAtTime,
		&i.HbAtTime,
		&i.AdverseReaction,
		&i.AdverseReactionType,
		&i.AdverseReactionSeverity,
		&i.TreatmentGiven,
		&i.TestDoseGiven,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listIronAdverseReactions = `-- name: ListIronAdverseReactions :many
SELECT id, hospital_id, patient_id, session_id, administered_by, administered_at, product, dose_mg, route, infusion_duration_mins, dilution, ferritin_at_time, ferritin_target_min, ferritin_target_max, tsat_at_time, hb_at_time, adverse_reaction, adverse_reaction_type, adverse_reaction_severity, treatment_given, test_dose_given, notes, created_at, updated_at, deleted_at FROM iron_therapy_records
WHERE hospital_id = $1 AND adverse_reaction = TRUE AND deleted_at IS NULL
ORDER BY administered_at DESC
`

func (q *Queries) ListIronAdverseReactions(ctx context.Context, hospitalID uuid.UUID) ([]IronTherapyRecord, error) {
	rows, err := q.db.Query(ctx, listIronAdverseReactions, hospitalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IronTherapyRecord
	for rows.Next() {
		var i IronTherapyRecord
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.PatientID,
			&i.SessionID,
			&i.AdministeredBy,
			&i.AdministeredAt,
			&i.Product,
			&i.DoseMg,
			&i.Route,
			&i.InfusionDurationMins,
			&i.Dilution,
			&i.FerritinAtTime,
			&i.FerritinTargetMin,
			&i.FerritinTargetMax,
			&i.TsatAtTime,
			&i.HbAtTime,
			&i.AdverseReaction,
			&i.AdverseReactionType,
			&i.AdverseReactionSeverity,
			&i.TreatmentGiven,
			&i.TestDoseGiven,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIronTherapyRecordsByPatient = `-- name: ListIronTherapyRecordsByPatient :many
SELECT id, hospital_id, patient_id, session_id, administered_by, administered_at, product, dose_mg, route, infusion_duration_mins, dilution, ferritin_at_time, ferritin_target_min, ferritin_target_max, tsat_at_time, hb_at_time, adverse_reaction, adverse_reaction_type, adverse_reaction_severity, treatment_given, test_dose_given, notes, created_at, updated_at, deleted_at FROM iron_therapy_records
WHERE patient_id = $1 AND deleted_at IS NULL
ORDER BY administered_at DESC
LIMIT $2 OFFSET $3
`

type ListIronTherapyRecordsByPatientParams struct {
	PatientID uuid.UUID `json:"patient_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListIronTherapyRecordsByPatient(ctx context.Context, arg ListIronTherapyRecordsByPatientParams) ([]IronTherapyRecord, error) {
	rows, err := q.db.Query(ctx, listIronTherapyRecordsByPatient, arg.PatientID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IronTherapyRecord
	for rows.Next() {
		var i IronTherapyRecord
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.PatientID,
			&i.SessionID,
			&i.AdministeredBy,
			&i.AdministeredAt,
			&i.Product,
			&i.DoseMg,
			&i.Route,
			&i.InfusionDurationMins,
			&i.Dilution,
			&i.FerritinAtTime,
			&i.FerritinTargetMin,
			&i.FerritinTargetMax,
			&i.TsatAtTime,
			&i.HbAtTime,
			&i.AdverseReaction,
			&i.AdverseReactionType,
			&i.AdverseReactionSeverity,
			&i.TreatmentGiven,
			&i.TestDoseGiven,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
