// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lab_critical_alerts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acknowledgeCriticalAlert = `-- name: AcknowledgeCriticalAlert :one
UPDATE lab_critical_alerts
SET acknowledged_by = $2, acknowledged_at = now(), action_taken = $3
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, hospital_id, result_id, patient_id, test_name, critical_value, reference_range, severity, alerted_at, acknowledged_by, acknowledged_at, action_taken, doctor_notified, doctor_notified_at, notes, created_at, updated_at, deleted_at
`

type AcknowledgeCriticalAlertParams struct {
	ID             uuid.UUID   `json:"id"`
	AcknowledgedBy pgtype.UUID `json:"acknowledged_by"`
	ActionTaken    pgtype.Text `json:"action_taken"`
}

func (q *Queries) AcknowledgeCriticalAlert(ctx context.Context, arg AcknowledgeCriticalAlertParams) (LabCriticalAlert, error) {
	row := q.db.QueryRow(ctx, acknowledgeCriticalAlert, arg.ID, arg.AcknowledgedBy, arg.ActionTaken)
	var i LabCriticalAlert
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.ResultID,
		&i.PatientID,
		&i.TestName,
		&i.CriticalValue,
		&i.ReferenceRange,
		&i.Severity,
		&i.AlertedAt,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
		&i.ActionTaken,
		&i.DoctorNotified,
		&i.DoctorNotifiedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createLabCriticalAlert = `-- name: CreateLabCriticalAlert :one
INSERT INTO lab_critical_alerts (
    hospital_id, result_id, patient_id, test_name, critical_value,
    reference_range, severity
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, hospital_id, result_id, patient_id, test_name, critical_value, reference_range, severity, alerted_at, acknowledged_by, acknowledged_at, action_taken, doctor_notified, doctor_notified_at, notes, created_at, updated_at, deleted_at
`

type CreateLabCriticalAlertParams struct {
	HospitalID     uuid.UUID   `json:"hospital_id"`
	ResultID       uuid.UUID   `json:"result_id"`
	PatientID      uuid.UUID   `json:"patient_id"`
	TestName       string      `json:"test_name"`
	CriticalValue  string      `json:"critical_value"`
	ReferenceRange pgtype.Text `json:"reference_range"`
	Severity       string      `json:"severity"`
}

func (q *Queries) CreateLabCriticalAlert(ctx context.Context, arg CreateLabCriticalAlertParams) (LabCriticalAlert, error) {
	row := q.db.QueryRow(ctx, createLabCriticalAlert,
		arg.HospitalID,
		arg.ResultID,
		arg.PatientID,
		arg.TestName,
		arg.CriticalValue,
		arg.ReferenceRange,
		arg.Severity,
	)
	var i LabCriticalAlert
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.ResultID,
		&i.PatientID,
		&i.TestName,
		&i.CriticalValue,
		&i.ReferenceRange,
		&i.Severity,
		&i.AlertedAt,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
		&i.ActionTaken,
		&i.DoctorNotified,
		&i.DoctorNotifiedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteLabCriticalAlert = `-- name: DeleteLabCriticalAlert :exec
UPDATE lab_critical_alerts SET deleted_at = now() WHERE id = $1
`

func (q *Queries) DeleteLabCriticalAlert(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLabCriticalAlert, id)
	return err
}

const getLabCriticalAlert = `-- name: GetLabCriticalAlert :one
SELECT id, hospital_id, result_id, patient_id, test_name, critical_value, reference_range, severity, alerted_at, acknowledged_by, acknowledged_at, action_taken, doctor_notified, doctor_notified_at, notes, created_at, updated_at, deleted_at FROM lab_critical_alerts WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetLabCriticalAlert(ctx context.Context, id uuid.UUID) (LabCriticalAlert, error) {
	row := q.db.QueryRow(ctx, getLabCriticalAlert, id)
	var i LabCriticalAlert
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.ResultID,
		&i.PatientID,
		&i.TestName,
		&i.CriticalValue,
		&i.ReferenceRange,
		&i.Severity,
		&i.AlertedAt,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
		&i.ActionTaken,
		&i.DoctorNotified,
		&i.DoctorNotifiedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCriticalAlertsByDateRange = `-- name: ListCriticalAlertsByDateRange :many
SELECT id, hospital_id, result_id, patient_id, test_name, critical_value, reference_range, severity, alerted_at, acknowledged_by, acknowledged_at, action_taken, doctor_notified, doctor_notified_at, notes, created_at, updated_at, deleted_at FROM lab_critical_alerts
WHERE hospital_id = $1
  AND alerted_at >= $2
  AND alerted_at <= $3
  AND deleted_at IS NULL
ORDER BY alerted_at DESC
`

type ListCriticalAlertsByDateRangeParams struct {
	HospitalID  uuid.UUID          `json:"hospital_id"`
	AlertedAt   pgtype.Timestamptz `json:"alerted_at"`
	AlertedAt_2 pgtype.Timestamptz `json:"alerted_at_2"`
}

func (q *Queries) ListCriticalAlertsByDateRange(ctx context.Context, arg ListCriticalAlertsByDateRangeParams) ([]LabCriticalAlert, error) {
	rows, err := q.db.Query(ctx, listCriticalAlertsByDateRange, arg.HospitalID, arg.AlertedAt, arg.AlertedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LabCriticalAlert
	for rows.Next() {
		var i LabCriticalAlert
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.ResultID,
			&i.PatientID,
			&i.TestName,
			&i.CriticalValue,
			&i.ReferenceRange,
			&i.Severity,
			&i.AlertedAt,
			&i.AcknowledgedBy,
			&i.AcknowledgedAt,
			&i.ActionTaken,
			&i.DoctorNotified,
			&i.DoctorNotifiedAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabCriticalAlertsByPatient = `-- name: ListLabCriticalAlertsByPatient :many
SELECT id, hospital_id, result_id, patient_id, test_name, critical_value, reference_range, severity, alerted_at, acknowledged_by, acknowledged_at, action_taken, doctor_notified, doctor_notified_at, notes, created_at, updated_at, deleted_at FROM lab_critical_alerts
WHERE patient_id = $1 AND deleted_at IS NULL
ORDER BY alerted_at DESC
`

func (q *Queries) ListLabCriticalAlertsByPatient(ctx context.Context, patientID uuid.UUID) ([]LabCriticalAlert, error) {
	rows, err := q.db.Query(ctx, listLabCriticalAlertsByPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LabCriticalAlert
	for rows.Next() {
		var i LabCriticalAlert
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.ResultID,
			&i.PatientID,
			&i.TestName,
			&i.CriticalValue,
			&i.ReferenceRange,
			&i.Severity,
			&i.AlertedAt,
			&i.AcknowledgedBy,
			&i.AcknowledgedAt,
			&i.ActionTaken,
			&i.DoctorNotified,
			&i.DoctorNotifiedAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnacknowledgedCriticalAlerts = `-- name: ListUnacknowledgedCriticalAlerts :many
SELECT id, hospital_id, result_id, patient_id, test_name, critical_value, reference_range, severity, alerted_at, acknowledged_by, acknowledged_at, action_taken, doctor_notified, doctor_notified_at, notes, created_at, updated_at, deleted_at FROM lab_critical_alerts
WHERE hospital_id = $1 AND acknowledged_at IS NULL AND deleted_at IS NULL
ORDER BY alerted_at
`

func (q *Queries) ListUnacknowledgedCriticalAlerts(ctx context.Context, hospitalID uuid.UUID) ([]LabCriticalAlert, error) {
	rows, err := q.db.Query(ctx, listUnacknowledgedCriticalAlerts, hospitalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LabCriticalAlert
	for rows.Next() {
		var i LabCriticalAlert
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.ResultID,
			&i.PatientID,
			&i.TestName,
			&i.CriticalValue,
			&i.ReferenceRange,
			&i.Severity,
			&i.AlertedAt,
			&i.AcknowledgedBy,
			&i.AcknowledgedAt,
			&i.ActionTaken,
			&i.DoctorNotified,
			&i.DoctorNotifiedAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const notifyDoctorOfCriticalAlert = `-- name: NotifyDoctorOfCriticalAlert :one
UPDATE lab_critical_alerts
SET doctor_notified = TRUE, doctor_notified_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, hospital_id, result_id, patient_id, test_name, critical_value, reference_range, severity, alerted_at, acknowledged_by, acknowledged_at, action_taken, doctor_notified, doctor_notified_at, notes, created_at, updated_at, deleted_at
`

func (q *Queries) NotifyDoctorOfCriticalAlert(ctx context.Context, id uuid.UUID) (LabCriticalAlert, error) {
	row := q.db.QueryRow(ctx, notifyDoctorOfCriticalAlert, id)
	var i LabCriticalAlert
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.ResultID,
		&i.PatientID,
		&i.TestName,
		&i.CriticalValue,
		&i.ReferenceRange,
		&i.Severity,
		&i.AlertedAt,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
		&i.ActionTaken,
		&i.DoctorNotified,
		&i.DoctorNotifiedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
