// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lab_test_catalog.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createLabTest = `-- name: CreateLabTest :one
INSERT INTO lab_test_catalog (
    hospital_id, code, name, category, unit, turnaround_hrs,
    specimen_type, specimen_volume_ml, requires_fasting, cost_amount, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, hospital_id, code, name, category, unit, turnaround_hrs, specimen_type, specimen_volume_ml, requires_fasting, cost_amount, is_active, notes, created_at, updated_at, deleted_at
`

type CreateLabTestParams struct {
	HospitalID       uuid.UUID      `json:"hospital_id"`
	Code             string         `json:"code"`
	Name             string         `json:"name"`
	Category         pgtype.Text    `json:"category"`
	Unit             pgtype.Text    `json:"unit"`
	TurnaroundHrs    int32          `json:"turnaround_hrs"`
	SpecimenType     SpecimenType   `json:"specimen_type"`
	SpecimenVolumeMl pgtype.Numeric `json:"specimen_volume_ml"`
	RequiresFasting  bool           `json:"requires_fasting"`
	CostAmount       pgtype.Numeric `json:"cost_amount"`
	Notes            pgtype.Text    `json:"notes"`
}

func (q *Queries) CreateLabTest(ctx context.Context, arg CreateLabTestParams) (LabTestCatalog, error) {
	row := q.db.QueryRow(ctx, createLabTest,
		arg.HospitalID,
		arg.Code,
		arg.Name,
		arg.Category,
		arg.Unit,
		arg.TurnaroundHrs,
		arg.SpecimenType,
		arg.SpecimenVolumeMl,
		arg.RequiresFasting,
		arg.CostAmount,
		arg.Notes,
	)
	var i LabTestCatalog
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.Code,
		&i.Name,
		&i.Category,
		&i.Unit,
		&i.TurnaroundHrs,
		&i.SpecimenType,
		&i.SpecimenVolumeMl,
		&i.RequiresFasting,
		&i.CostAmount,
		&i.IsActive,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteLabTest = `-- name: DeleteLabTest :exec
UPDATE lab_test_catalog SET deleted_at = now() WHERE id = $1
`

func (q *Queries) DeleteLabTest(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLabTest, id)
	return err
}

const getLabTest = `-- name: GetLabTest :one
SELECT id, hospital_id, code, name, category, unit, turnaround_hrs, specimen_type, specimen_volume_ml, requires_fasting, cost_amount, is_active, notes, created_at, updated_at, deleted_at FROM lab_test_catalog WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetLabTest(ctx context.Context, id uuid.UUID) (LabTestCatalog, error) {
	row := q.db.QueryRow(ctx, getLabTest, id)
	var i LabTestCatalog
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.Code,
		&i.Name,
		&i.Category,
		&i.Unit,
		&i.TurnaroundHrs,
		&i.SpecimenType,
		&i.SpecimenVolumeMl,
		&i.RequiresFasting,
		&i.CostAmount,
		&i.IsActive,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLabTestByCode = `-- name: GetLabTestByCode :one
SELECT id, hospital_id, code, name, category, unit, turnaround_hrs, specimen_type, specimen_volume_ml, requires_fasting, cost_amount, is_active, notes, created_at, updated_at, deleted_at FROM lab_test_catalog
WHERE hospital_id = $1 AND code = $2 AND deleted_at IS NULL
`

type GetLabTestByCodeParams struct {
	HospitalID uuid.UUID `json:"hospital_id"`
	Code       string    `json:"code"`
}

func (q *Queries) GetLabTestByCode(ctx context.Context, arg GetLabTestByCodeParams) (LabTestCatalog, error) {
	row := q.db.QueryRow(ctx, getLabTestByCode, arg.HospitalID, arg.Code)
	var i LabTestCatalog
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.Code,
		&i.Name,
		&i.Category,
		&i.Unit,
		&i.TurnaroundHrs,
		&i.SpecimenType,
		&i.SpecimenVolumeMl,
		&i.RequiresFasting,
		&i.CostAmount,
		&i.IsActive,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listActiveLabTests = `-- name: ListActiveLabTests :many
SELECT id, hospital_id, code, name, category, unit, turnaround_hrs, specimen_type, specimen_volume_ml, requires_fasting, cost_amount, is_active, notes, created_at, updated_at, deleted_at FROM lab_test_catalog
WHERE hospital_id = $1 AND is_active = TRUE AND deleted_at IS NULL
ORDER BY category, name
`

func (q *Queries) ListActiveLabTests(ctx context.Context, hospitalID uuid.UUID) ([]LabTestCatalog, error) {
	rows, err := q.db.Query(ctx, listActiveLabTests, hospitalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LabTestCatalog
	for rows.Next() {
		var i LabTestCatalog
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.Code,
			&i.Name,
			&i.Category,
			&i.Unit,
			&i.TurnaroundHrs,
			&i.SpecimenType,
			&i.SpecimenVolumeMl,
			&i.RequiresFasting,
			&i.CostAmount,
			&i.IsActive,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabTestsByCategory = `-- name: ListLabTestsByCategory :many
SELECT id, hospital_id, code, name, category, unit, turnaround_hrs, specimen_type, specimen_volume_ml, requires_fasting, cost_amount, is_active, notes, created_at, updated_at, deleted_at FROM lab_test_catalog
WHERE hospital_id = $1 AND category = $2 AND deleted_at IS NULL
ORDER BY name
`

type ListLabTestsByCategoryParams struct {
	HospitalID uuid.UUID   `json:"hospital_id"`
	Category   pgtype.Text `json:"category"`
}

func (q *Queries) ListLabTestsByCategory(ctx context.Context, arg ListLabTestsByCategoryParams) ([]LabTestCatalog, error) {
	rows, err := q.db.Query(ctx, listLabTestsByCategory, arg.HospitalID, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LabTestCatalog
	for rows.Next() {
		var i LabTestCatalog
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.Code,
			&i.Name,
			&i.Category,
			&i.Unit,
			&i.TurnaroundHrs,
			&i.SpecimenType,
			&i.SpecimenVolumeMl,
			&i.RequiresFasting,
			&i.CostAmount,
			&i.IsActive,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabTestsByHospital = `-- name: ListLabTestsByHospital :many
SELECT id, hospital_id, code, name, category, unit, turnaround_hrs, specimen_type, specimen_volume_ml, requires_fasting, cost_amount, is_active, notes, created_at, updated_at, deleted_at FROM lab_test_catalog
WHERE hospital_id = $1 AND deleted_at IS NULL
ORDER BY category, name
`

func (q *Queries) ListLabTestsByHospital(ctx context.Context, hospitalID uuid.UUID) ([]LabTestCatalog, error) {
	rows, err := q.db.Query(ctx, listLabTestsByHospital, hospitalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LabTestCatalog
	for rows.Next() {
		var i LabTestCatalog
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.Code,
			&i.Name,
			&i.Category,
			&i.Unit,
			&i.TurnaroundHrs,
			&i.SpecimenType,
			&i.SpecimenVolumeMl,
			&i.RequiresFasting,
			&i.CostAmount,
			&i.IsActive,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLabTest = `-- name: UpdateLabTest :one
UPDATE lab_test_catalog
SET code = $2, name = $3, category = $4, unit = $5, turnaround_hrs = $6,
    specimen_type = $7, specimen_volume_ml = $8, requires_fasting = $9,
    cost_amount = $10, is_active = $11, notes = $12
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, hospital_id, code, name, category, unit, turnaround_hrs, specimen_type, specimen_volume_ml, requires_fasting, cost_amount, is_active, notes, created_at, updated_at, deleted_at
`

type UpdateLabTestParams struct {
	ID               uuid.UUID      `json:"id"`
	Code             string         `json:"code"`
	Name             string         `json:"name"`
	Category         pgtype.Text    `json:"category"`
	Unit             pgtype.Text    `json:"unit"`
	TurnaroundHrs    int32          `json:"turnaround_hrs"`
	SpecimenType     SpecimenType   `json:"specimen_type"`
	SpecimenVolumeMl pgtype.Numeric `json:"specimen_volume_ml"`
	RequiresFasting  bool           `json:"requires_fasting"`
	CostAmount       pgtype.Numeric `json:"cost_amount"`
	IsActive         bool           `json:"is_active"`
	Notes            pgtype.Text    `json:"notes"`
}

func (q *Queries) UpdateLabTest(ctx context.Context, arg UpdateLabTestParams) (LabTestCatalog, error) {
	row := q.db.QueryRow(ctx, updateLabTest,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Category,
		arg.Unit,
		arg.TurnaroundHrs,
		arg.SpecimenType,
		arg.SpecimenVolumeMl,
		arg.RequiresFasting,
		arg.CostAmount,
		arg.IsActive,
		arg.Notes,
	)
	var i LabTestCatalog
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.Code,
		&i.Name,
		&i.Category,
		&i.Unit,
		&i.TurnaroundHrs,
		&i.SpecimenType,
		&i.SpecimenVolumeMl,
		&i.RequiresFasting,
		&i.CostAmount,
		&i.IsActive,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
