// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: leave_records.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approveLeave = `-- name: ApproveLeave :one
UPDATE leave_records
SET status = 'approved', approved_by = $2, approved_at = now(), days_approved = $3
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, hospital_id, staff_id, leave_type, start_date, end_date, days_requested, days_approved, reason, requested_at, approved_by, approved_at, rejection_reason, status, relief_staff_id, notes, created_at, updated_at, deleted_at
`

type ApproveLeaveParams struct {
	ID           uuid.UUID   `json:"id"`
	ApprovedBy   pgtype.UUID `json:"approved_by"`
	DaysApproved pgtype.Int4 `json:"days_approved"`
}

func (q *Queries) ApproveLeave(ctx context.Context, arg ApproveLeaveParams) (LeaveRecord, error) {
	row := q.db.QueryRow(ctx, approveLeave, arg.ID, arg.ApprovedBy, arg.DaysApproved)
	var i LeaveRecord
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.StaffID,
		&i.LeaveType,
		&i.StartDate,
		&i.EndDate,
		&i.DaysRequested,
		&i.DaysApproved,
		&i.Reason,
		&i.RequestedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectionReason,
		&i.Status,
		&i.ReliefStaffID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createLeaveRecord = `-- name: CreateLeaveRecord :one
INSERT INTO leave_records (
    hospital_id, staff_id, leave_type, start_date, end_date,
    days_requested, reason, status
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, hospital_id, staff_id, leave_type, start_date, end_date, days_requested, days_approved, reason, requested_at, approved_by, approved_at, rejection_reason, status, relief_staff_id, notes, created_at, updated_at, deleted_at
`

type CreateLeaveRecordParams struct {
	HospitalID    uuid.UUID   `json:"hospital_id"`
	StaffID       uuid.UUID   `json:"staff_id"`
	LeaveType     LeaveType   `json:"leave_type"`
	StartDate     pgtype.Date `json:"start_date"`
	EndDate       pgtype.Date `json:"end_date"`
	DaysRequested int32       `json:"days_requested"`
	Reason        pgtype.Text `json:"reason"`
	Status        LeaveStatus `json:"status"`
}

func (q *Queries) CreateLeaveRecord(ctx context.Context, arg CreateLeaveRecordParams) (LeaveRecord, error) {
	row := q.db.QueryRow(ctx, createLeaveRecord,
		arg.HospitalID,
		arg.StaffID,
		arg.LeaveType,
		arg.StartDate,
		arg.EndDate,
		arg.DaysRequested,
		arg.Reason,
		arg.Status,
	)
	var i LeaveRecord
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.StaffID,
		&i.LeaveType,
		&i.StartDate,
		&i.EndDate,
		&i.DaysRequested,
		&i.DaysApproved,
		&i.Reason,
		&i.RequestedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectionReason,
		&i.Status,
		&i.ReliefStaffID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteLeaveRecord = `-- name: DeleteLeaveRecord :exec
UPDATE leave_records SET deleted_at = now() WHERE id = $1
`

func (q *Queries) DeleteLeaveRecord(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLeaveRecord, id)
	return err
}

const getLeaveRecord = `-- name: GetLeaveRecord :one
SELECT id, hospital_id, staff_id, leave_type, start_date, end_date, days_requested, days_approved, reason, requested_at, approved_by, approved_at, rejection_reason, status, relief_staff_id, notes, created_at, updated_at, deleted_at FROM leave_records WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetLeaveRecord(ctx context.Context, id uuid.UUID) (LeaveRecord, error) {
	row := q.db.QueryRow(ctx, getLeaveRecord, id)
	var i LeaveRecord
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.StaffID,
		&i.LeaveType,
		&i.StartDate,
		&i.EndDate,
		&i.DaysRequested,
		&i.DaysApproved,
		&i.Reason,
		&i.RequestedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectionReason,
		&i.Status,
		&i.ReliefStaffID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listLeaveByDateRange = `-- name: ListLeaveByDateRange :many
SELECT id, hospital_id, staff_id, leave_type, start_date, end_date, days_requested, days_approved, reason, requested_at, approved_by, approved_at, rejection_reason, status, relief_staff_id, notes, created_at, updated_at, deleted_at FROM leave_records
WHERE hospital_id = $1
  AND start_date <= $3
  AND end_date >= $2
  AND status = 'approved'
  AND deleted_at IS NULL
ORDER BY start_date
`

type ListLeaveByDateRangeParams struct {
	HospitalID uuid.UUID   `json:"hospital_id"`
	EndDate    pgtype.Date `json:"end_date"`
	StartDate  pgtype.Date `json:"start_date"`
}

func (q *Queries) ListLeaveByDateRange(ctx context.Context, arg ListLeaveByDateRangeParams) ([]LeaveRecord, error) {
	rows, err := q.db.Query(ctx, listLeaveByDateRange, arg.HospitalID, arg.EndDate, arg.StartDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LeaveRecord
	for rows.Next() {
		var i LeaveRecord
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.StaffID,
			&i.LeaveType,
			&i.StartDate,
			&i.EndDate,
			&i.DaysRequested,
			&i.DaysApproved,
			&i.Reason,
			&i.RequestedAt,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.RejectionReason,
			&i.Status,
			&i.ReliefStaffID,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeaveByStaff = `-- name: ListLeaveByStaff :many
SELECT id, hospital_id, staff_id, leave_type, start_date, end_date, days_requested, days_approved, reason, requested_at, approved_by, approved_at, rejection_reason, status, relief_staff_id, notes, created_at, updated_at, deleted_at FROM leave_records
WHERE staff_id = $1 AND deleted_at IS NULL
ORDER BY start_date DESC
`

func (q *Queries) ListLeaveByStaff(ctx context.Context, staffID uuid.UUID) ([]LeaveRecord, error) {
	rows, err := q.db.Query(ctx, listLeaveByStaff, staffID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LeaveRecord
	for rows.Next() {
		var i LeaveRecord
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.StaffID,
			&i.LeaveType,
			&i.StartDate,
			&i.EndDate,
			&i.DaysRequested,
			&i.DaysApproved,
			&i.Reason,
			&i.RequestedAt,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.RejectionReason,
			&i.Status,
			&i.ReliefStaffID,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingLeave = `-- name: ListPendingLeave :many
SELECT id, hospital_id, staff_id, leave_type, start_date, end_date, days_requested, days_approved, reason, requested_at, approved_by, approved_at, rejection_reason, status, relief_staff_id, notes, created_at, updated_at, deleted_at FROM leave_records
WHERE hospital_id = $1 AND status = 'pending' AND deleted_at IS NULL
ORDER BY requested_at ASC
`

func (q *Queries) ListPendingLeave(ctx context.Context, hospitalID uuid.UUID) ([]LeaveRecord, error) {
	rows, err := q.db.Query(ctx, listPendingLeave, hospitalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LeaveRecord
	for rows.Next() {
		var i LeaveRecord
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.StaffID,
			&i.LeaveType,
			&i.StartDate,
			&i.EndDate,
			&i.DaysRequested,
			&i.DaysApproved,
			&i.Reason,
			&i.RequestedAt,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.RejectionReason,
			&i.Status,
			&i.ReliefStaffID,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectLeave = `-- name: RejectLeave :one
UPDATE leave_records
SET status = 'rejected', rejection_reason = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, hospital_id, staff_id, leave_type, start_date, end_date, days_requested, days_approved, reason, requested_at, approved_by, approved_at, rejection_reason, status, relief_staff_id, notes, created_at, updated_at, deleted_at
`

type RejectLeaveParams struct {
	ID              uuid.UUID   `json:"id"`
	RejectionReason pgtype.Text `json:"rejection_reason"`
}

func (q *Queries) RejectLeave(ctx context.Context, arg RejectLeaveParams) (LeaveRecord, error) {
	row := q.db.QueryRow(ctx, rejectLeave, arg.ID, arg.RejectionReason)
	var i LeaveRecord
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.StaffID,
		&i.LeaveType,
		&i.StartDate,
		&i.EndDate,
		&i.DaysRequested,
		&i.DaysApproved,
		&i.Reason,
		&i.RequestedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RejectionReason,
		&i.Status,
		&i.ReliefStaffID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
