// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ConflictResolution string

const (
	ConflictResolutionPending    ConflictResolution = "pending"
	ConflictResolutionServerWins ConflictResolution = "server_wins"
	ConflictResolutionClientWins ConflictResolution = "client_wins"
	ConflictResolutionManual     ConflictResolution = "manual"
)

func (e *ConflictResolution) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConflictResolution(s)
	case string:
		*e = ConflictResolution(s)
	default:
		return fmt.Errorf("unsupported scan type for ConflictResolution: %T", src)
	}
	return nil
}

type NullConflictResolution struct {
	ConflictResolution ConflictResolution `json:"conflict_resolution"`
	Valid              bool               `json:"valid"` // Valid is true if ConflictResolution is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConflictResolution) Scan(value interface{}) error {
	if value == nil {
		ns.ConflictResolution, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConflictResolution.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConflictResolution) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConflictResolution), nil
}

type NotificationPriority string

const (
	NotificationPriorityLow      NotificationPriority = "low"
	NotificationPriorityMedium   NotificationPriority = "medium"
	NotificationPriorityHigh     NotificationPriority = "high"
	NotificationPriorityCritical NotificationPriority = "critical"
)

func (e *NotificationPriority) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationPriority(s)
	case string:
		*e = NotificationPriority(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationPriority: %T", src)
	}
	return nil
}

type NullNotificationPriority struct {
	NotificationPriority NotificationPriority `json:"notification_priority"`
	Valid                bool                 `json:"valid"` // Valid is true if NotificationPriority is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationPriority) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationPriority, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationPriority.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationPriority) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationPriority), nil
}

type SyncOperation string

const (
	SyncOperationCREATE SyncOperation = "CREATE"
	SyncOperationUPDATE SyncOperation = "UPDATE"
	SyncOperationDELETE SyncOperation = "DELETE"
)

func (e *SyncOperation) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SyncOperation(s)
	case string:
		*e = SyncOperation(s)
	default:
		return fmt.Errorf("unsupported scan type for SyncOperation: %T", src)
	}
	return nil
}

type NullSyncOperation struct {
	SyncOperation SyncOperation `json:"sync_operation"`
	Valid         bool          `json:"valid"` // Valid is true if SyncOperation is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSyncOperation) Scan(value interface{}) error {
	if value == nil {
		ns.SyncOperation, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SyncOperation.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSyncOperation) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SyncOperation), nil
}

type SyncStatus string

const (
	SyncStatusPending  SyncStatus = "pending"
	SyncStatusSyncing  SyncStatus = "syncing"
	SyncStatusSynced   SyncStatus = "synced"
	SyncStatusFailed   SyncStatus = "failed"
	SyncStatusConflict SyncStatus = "conflict"
)

func (e *SyncStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SyncStatus(s)
	case string:
		*e = SyncStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SyncStatus: %T", src)
	}
	return nil
}

type NullSyncStatus struct {
	SyncStatus SyncStatus `json:"sync_status"`
	Valid      bool       `json:"valid"` // Valid is true if SyncStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSyncStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SyncStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SyncStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSyncStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SyncStatus), nil
}

type AuditLog struct {
	ID         uuid.UUID          `json:"id"`
	HospitalID uuid.UUID          `json:"hospital_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Action     string             `json:"action"`
	TableName  string             `json:"table_name"`
	RecordID   pgtype.UUID        `json:"record_id"`
	OldData    []byte             `json:"old_data"`
	NewData    []byte             `json:"new_data"`
	IpAddress  *netip.Addr        `json:"ip_address"`
	UserAgent  pgtype.Text        `json:"user_agent"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AuthSession struct {
	ID         uuid.UUID          `json:"id"`
	HospitalID uuid.UUID          `json:"hospital_id"`
	UserID     uuid.UUID          `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	DeviceInfo []byte             `json:"device_info"`
	IpAddress  *netip.Addr        `json:"ip_address"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

type Department struct {
	ID          uuid.UUID          `json:"id"`
	HospitalID  uuid.UUID          `json:"hospital_id"`
	Name        string             `json:"name"`
	Code        pgtype.Text        `json:"code"`
	Description pgtype.Text        `json:"description"`
	HeadUserID  pgtype.UUID        `json:"head_user_id"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type FileAttachment struct {
	ID            uuid.UUID          `json:"id"`
	HospitalID    uuid.UUID          `json:"hospital_id"`
	UploadedBy    uuid.UUID          `json:"uploaded_by"`
	EntityType    string             `json:"entity_type"`
	EntityID      uuid.UUID          `json:"entity_id"`
	FileName      string             `json:"file_name"`
	FilePath      string             `json:"file_path"`
	MimeType      string             `json:"mime_type"`
	FileSizeBytes pgtype.Int8        `json:"file_size_bytes"`
	Description   pgtype.Text        `json:"description"`
	IsSensitive   bool               `json:"is_sensitive"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type Hospital struct {
	ID            uuid.UUID          `json:"id"`
	Name          string             `json:"name"`
	ShortCode     string             `json:"short_code"`
	Tier          string             `json:"tier"`
	Region        string             `json:"region"`
	Country       string             `json:"country"`
	Address       pgtype.Text        `json:"address"`
	Phone         pgtype.Text        `json:"phone"`
	Email         pgtype.Text        `json:"email"`
	LicenseNo     pgtype.Text        `json:"license_no"`
	LicenseExpiry pgtype.Date        `json:"license_expiry"`
	IsActive      bool               `json:"is_active"`
	Settings      []byte             `json:"settings"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type HospitalSetting struct {
	ID          uuid.UUID          `json:"id"`
	HospitalID  uuid.UUID          `json:"hospital_id"`
	Key         string             `json:"key"`
	Value       string             `json:"value"`
	DataType    string             `json:"data_type"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type Notification struct {
	ID         uuid.UUID            `json:"id"`
	HospitalID uuid.UUID            `json:"hospital_id"`
	UserID     uuid.UUID            `json:"user_id"`
	Type       string               `json:"type"`
	Title      string               `json:"title"`
	Message    string               `json:"message"`
	Priority   NotificationPriority `json:"priority"`
	EntityType pgtype.Text          `json:"entity_type"`
	EntityID   pgtype.UUID          `json:"entity_id"`
	ReadAt     pgtype.Timestamptz   `json:"read_at"`
	ActionedAt pgtype.Timestamptz   `json:"actioned_at"`
	ExpiresAt  pgtype.Timestamptz   `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz   `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz   `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz   `json:"deleted_at"`
}

type Role struct {
	ID          uuid.UUID          `json:"id"`
	HospitalID  uuid.UUID          `json:"hospital_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Permissions []byte             `json:"permissions"`
	IsSystem    bool               `json:"is_system"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type SyncConflict struct {
	ID         uuid.UUID          `json:"id"`
	HospitalID uuid.UUID          `json:"hospital_id"`
	QueueID    uuid.UUID          `json:"queue_id"`
	EntityType string             `json:"entity_type"`
	EntityID   uuid.UUID          `json:"entity_id"`
	LocalData  []byte             `json:"local_data"`
	ServerData []byte             `json:"server_data"`
	Resolution ConflictResolution `json:"resolution"`
	ResolvedBy pgtype.UUID        `json:"resolved_by"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
	Notes      pgtype.Text        `json:"notes"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

type SyncQueue struct {
	ID            uuid.UUID          `json:"id"`
	HospitalID    uuid.UUID          `json:"hospital_id"`
	UserID        uuid.UUID          `json:"user_id"`
	EntityType    string             `json:"entity_type"`
	EntityID      uuid.UUID          `json:"entity_id"`
	Operation     SyncOperation      `json:"operation"`
	Payload       []byte             `json:"payload"`
	Priority      int32              `json:"priority"`
	Status        SyncStatus         `json:"status"`
	Attempts      int32              `json:"attempts"`
	LastAttemptAt pgtype.Timestamptz `json:"last_attempt_at"`
	SyncedAt      pgtype.Timestamptz `json:"synced_at"`
	ErrorMessage  pgtype.Text        `json:"error_message"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type User struct {
	ID              uuid.UUID          `json:"id"`
	HospitalID      uuid.UUID          `json:"hospital_id"`
	Email           string             `json:"email"`
	Phone           pgtype.Text        `json:"phone"`
	PasswordHash    string             `json:"password_hash"`
	FullName        string             `json:"full_name"`
	IsActive        bool               `json:"is_active"`
	IsVerified      bool               `json:"is_verified"`
	LastLoginAt     pgtype.Timestamptz `json:"last_login_at"`
	PasswordResetAt pgtype.Timestamptz `json:"password_reset_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type UserRole struct {
	ID           uuid.UUID          `json:"id"`
	HospitalID   uuid.UUID          `json:"hospital_id"`
	UserID       uuid.UUID          `json:"user_id"`
	RoleID       uuid.UUID          `json:"role_id"`
	DepartmentID pgtype.UUID        `json:"department_id"`
	AssignedBy   pgtype.UUID        `json:"assigned_by"`
	AssignedAt   pgtype.Timestamptz `json:"assigned_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}
