// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: next_of_kin.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createNextOfKin = `-- name: CreateNextOfKin :one
INSERT INTO next_of_kin (
    hospital_id, patient_id, full_name, relationship, phone_primary, phone_secondary,
    address, national_id, is_legal_guardian, is_emergency_contact, priority_order
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, hospital_id, patient_id, full_name, relationship, phone_primary, phone_secondary, address, national_id, is_legal_guardian, is_emergency_contact, priority_order, created_at, updated_at, deleted_at
`

type CreateNextOfKinParams struct {
	HospitalID         uuid.UUID   `json:"hospital_id"`
	PatientID          uuid.UUID   `json:"patient_id"`
	FullName           string      `json:"full_name"`
	Relationship       string      `json:"relationship"`
	PhonePrimary       string      `json:"phone_primary"`
	PhoneSecondary     pgtype.Text `json:"phone_secondary"`
	Address            pgtype.Text `json:"address"`
	NationalID         pgtype.Text `json:"national_id"`
	IsLegalGuardian    bool        `json:"is_legal_guardian"`
	IsEmergencyContact bool        `json:"is_emergency_contact"`
	PriorityOrder      int32       `json:"priority_order"`
}

func (q *Queries) CreateNextOfKin(ctx context.Context, arg CreateNextOfKinParams) (NextOfKin, error) {
	row := q.db.QueryRow(ctx, createNextOfKin,
		arg.HospitalID,
		arg.PatientID,
		arg.FullName,
		arg.Relationship,
		arg.PhonePrimary,
		arg.PhoneSecondary,
		arg.Address,
		arg.NationalID,
		arg.IsLegalGuardian,
		arg.IsEmergencyContact,
		arg.PriorityOrder,
	)
	var i NextOfKin
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.PatientID,
		&i.FullName,
		&i.Relationship,
		&i.PhonePrimary,
		&i.PhoneSecondary,
		&i.Address,
		&i.NationalID,
		&i.IsLegalGuardian,
		&i.IsEmergencyContact,
		&i.PriorityOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLegalGuardian = `-- name: GetLegalGuardian :one
SELECT id, hospital_id, patient_id, full_name, relationship, phone_primary, phone_secondary, address, national_id, is_legal_guardian, is_emergency_contact, priority_order, created_at, updated_at, deleted_at FROM next_of_kin
WHERE patient_id = $1 AND is_legal_guardian = TRUE AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetLegalGuardian(ctx context.Context, patientID uuid.UUID) (NextOfKin, error) {
	row := q.db.QueryRow(ctx, getLegalGuardian, patientID)
	var i NextOfKin
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.PatientID,
		&i.FullName,
		&i.Relationship,
		&i.PhonePrimary,
		&i.PhoneSecondary,
		&i.Address,
		&i.NationalID,
		&i.IsLegalGuardian,
		&i.IsEmergencyContact,
		&i.PriorityOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPrimaryContact = `-- name: GetPrimaryContact :one
SELECT id, hospital_id, patient_id, full_name, relationship, phone_primary, phone_secondary, address, national_id, is_legal_guardian, is_emergency_contact, priority_order, created_at, updated_at, deleted_at FROM next_of_kin
WHERE patient_id = $1 AND is_emergency_contact = TRUE AND deleted_at IS NULL
ORDER BY priority_order
LIMIT 1
`

func (q *Queries) GetPrimaryContact(ctx context.Context, patientID uuid.UUID) (NextOfKin, error) {
	row := q.db.QueryRow(ctx, getPrimaryContact, patientID)
	var i NextOfKin
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.PatientID,
		&i.FullName,
		&i.Relationship,
		&i.PhonePrimary,
		&i.PhoneSecondary,
		&i.Address,
		&i.NationalID,
		&i.IsLegalGuardian,
		&i.IsEmergencyContact,
		&i.PriorityOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listNextOfKinByPatient = `-- name: ListNextOfKinByPatient :many
SELECT id, hospital_id, patient_id, full_name, relationship, phone_primary, phone_secondary, address, national_id, is_legal_guardian, is_emergency_contact, priority_order, created_at, updated_at, deleted_at FROM next_of_kin
WHERE patient_id = $1 AND deleted_at IS NULL
ORDER BY priority_order
`

func (q *Queries) ListNextOfKinByPatient(ctx context.Context, patientID uuid.UUID) ([]NextOfKin, error) {
	rows, err := q.db.Query(ctx, listNextOfKinByPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NextOfKin
	for rows.Next() {
		var i NextOfKin
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.PatientID,
			&i.FullName,
			&i.Relationship,
			&i.PhonePrimary,
			&i.PhoneSecondary,
			&i.Address,
			&i.NationalID,
			&i.IsLegalGuardian,
			&i.IsEmergencyContact,
			&i.PriorityOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
