// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
  hospital_id, user_id, type, title, message, priority, entity_type, entity_id, expires_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, hospital_id, user_id, type, title, message, priority, entity_type, entity_id, read_at, actioned_at, expires_at, created_at, updated_at, deleted_at
`

type CreateNotificationParams struct {
	HospitalID uuid.UUID            `json:"hospital_id"`
	UserID     uuid.UUID            `json:"user_id"`
	Type       string               `json:"type"`
	Title      string               `json:"title"`
	Message    string               `json:"message"`
	Priority   NotificationPriority `json:"priority"`
	EntityType pgtype.Text          `json:"entity_type"`
	EntityID   pgtype.UUID          `json:"entity_id"`
	ExpiresAt  pgtype.Timestamptz   `json:"expires_at"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.HospitalID,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Message,
		arg.Priority,
		arg.EntityType,
		arg.EntityID,
		arg.ExpiresAt,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Message,
		&i.Priority,
		&i.EntityType,
		&i.EntityID,
		&i.ReadAt,
		&i.ActionedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getNotification = `-- name: GetNotification :one
SELECT id, hospital_id, user_id, type, title, message, priority, entity_type, entity_id, read_at, actioned_at, expires_at, created_at, updated_at, deleted_at FROM notifications
WHERE id = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetNotification(ctx context.Context, id uuid.UUID) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotification, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Message,
		&i.Priority,
		&i.EntityType,
		&i.EntityID,
		&i.ReadAt,
		&i.ActionedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCriticalUnread = `-- name: ListCriticalUnread :many
SELECT id, hospital_id, user_id, type, title, message, priority, entity_type, entity_id, read_at, actioned_at, expires_at, created_at, updated_at, deleted_at FROM notifications
WHERE user_id = $1 AND priority = 'critical' AND read_at IS NULL AND deleted_at IS NULL
  AND (expires_at IS NULL OR expires_at > now())
ORDER BY created_at DESC
`

func (q *Queries) ListCriticalUnread(ctx context.Context, userID uuid.UUID) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listCriticalUnread, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Message,
			&i.Priority,
			&i.EntityType,
			&i.EntityID,
			&i.ReadAt,
			&i.ActionedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadNotifications = `-- name: ListUnreadNotifications :many
SELECT id, hospital_id, user_id, type, title, message, priority, entity_type, entity_id, read_at, actioned_at, expires_at, created_at, updated_at, deleted_at FROM notifications
WHERE user_id = $1 AND read_at IS NULL AND deleted_at IS NULL
  AND (expires_at IS NULL OR expires_at > now())
ORDER BY priority DESC, created_at DESC
`

func (q *Queries) ListUnreadNotifications(ctx context.Context, userID uuid.UUID) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listUnreadNotifications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Message,
			&i.Priority,
			&i.EntityType,
			&i.EntityID,
			&i.ReadAt,
			&i.ActionedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationActioned = `-- name: MarkNotificationActioned :exec
UPDATE notifications
SET actioned_at = now()
WHERE id = $1
`

func (q *Queries) MarkNotificationActioned(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markNotificationActioned, id)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications
SET read_at = now()
WHERE id = $1
`

func (q *Queries) MarkNotificationRead(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markNotificationRead, id)
	return err
}
