// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: patient_contacts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPatientContact = `-- name: CreatePatientContact :one
INSERT INTO patient_contacts (
    hospital_id, patient_id, contact_type, value, label, is_primary, is_verified
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, hospital_id, patient_id, contact_type, value, label, is_primary, is_verified, created_at, updated_at, deleted_at
`

type CreatePatientContactParams struct {
	HospitalID  uuid.UUID   `json:"hospital_id"`
	PatientID   uuid.UUID   `json:"patient_id"`
	ContactType ContactType `json:"contact_type"`
	Value       string      `json:"value"`
	Label       pgtype.Text `json:"label"`
	IsPrimary   bool        `json:"is_primary"`
	IsVerified  bool        `json:"is_verified"`
}

func (q *Queries) CreatePatientContact(ctx context.Context, arg CreatePatientContactParams) (PatientContact, error) {
	row := q.db.QueryRow(ctx, createPatientContact,
		arg.HospitalID,
		arg.PatientID,
		arg.ContactType,
		arg.Value,
		arg.Label,
		arg.IsPrimary,
		arg.IsVerified,
	)
	var i PatientContact
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.PatientID,
		&i.ContactType,
		&i.Value,
		&i.Label,
		&i.IsPrimary,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPrimaryPhone = `-- name: GetPrimaryPhone :one
SELECT id, hospital_id, patient_id, contact_type, value, label, is_primary, is_verified, created_at, updated_at, deleted_at FROM patient_contacts
WHERE patient_id = $1 AND contact_type = 'phone' AND is_primary = TRUE AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetPrimaryPhone(ctx context.Context, patientID uuid.UUID) (PatientContact, error) {
	row := q.db.QueryRow(ctx, getPrimaryPhone, patientID)
	var i PatientContact
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.PatientID,
		&i.ContactType,
		&i.Value,
		&i.Label,
		&i.IsPrimary,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listContactsByPatient = `-- name: ListContactsByPatient :many
SELECT id, hospital_id, patient_id, contact_type, value, label, is_primary, is_verified, created_at, updated_at, deleted_at FROM patient_contacts
WHERE patient_id = $1 AND deleted_at IS NULL
ORDER BY is_primary DESC, created_at
`

func (q *Queries) ListContactsByPatient(ctx context.Context, patientID uuid.UUID) ([]PatientContact, error) {
	rows, err := q.db.Query(ctx, listContactsByPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PatientContact
	for rows.Next() {
		var i PatientContact
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.PatientID,
			&i.ContactType,
			&i.Value,
			&i.Label,
			&i.IsPrimary,
			&i.IsVerified,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContactPrimary = `-- name: UpdateContactPrimary :exec
UPDATE patient_contacts
SET is_primary = FALSE
WHERE patient_id = $1 AND contact_type = $2 AND id != $3
`

type UpdateContactPrimaryParams struct {
	PatientID   uuid.UUID   `json:"patient_id"`
	ContactType ContactType `json:"contact_type"`
	ID          uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateContactPrimary(ctx context.Context, arg UpdateContactPrimaryParams) error {
	_, err := q.db.Exec(ctx, updateContactPrimary, arg.PatientID, arg.ContactType, arg.ID)
	return err
}
