// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    hospital_id, invoice_id, account_id, patient_id, payment_date,
    payment_time, amount, payment_method, reference_number,
    mobile_money_number, bank_name, cheque_number, card_last_four,
    received_by, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, hospital_id, invoice_id, account_id, patient_id, payment_date, payment_time, amount, payment_method, reference_number, mobile_money_number, bank_name, cheque_number, card_last_four, received_by, notes, created_at, updated_at, deleted_at
`

type CreatePaymentParams struct {
	HospitalID        uuid.UUID      `json:"hospital_id"`
	InvoiceID         pgtype.UUID    `json:"invoice_id"`
	AccountID         uuid.UUID      `json:"account_id"`
	PatientID         uuid.UUID      `json:"patient_id"`
	PaymentDate       pgtype.Date    `json:"payment_date"`
	PaymentTime       pgtype.Time    `json:"payment_time"`
	Amount            pgtype.Numeric `json:"amount"`
	PaymentMethod     PaymentMethod  `json:"payment_method"`
	ReferenceNumber   pgtype.Text    `json:"reference_number"`
	MobileMoneyNumber pgtype.Text    `json:"mobile_money_number"`
	BankName          pgtype.Text    `json:"bank_name"`
	ChequeNumber      pgtype.Text    `json:"cheque_number"`
	CardLastFour      pgtype.Text    `json:"card_last_four"`
	ReceivedBy        uuid.UUID      `json:"received_by"`
	Notes             pgtype.Text    `json:"notes"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.HospitalID,
		arg.InvoiceID,
		arg.AccountID,
		arg.PatientID,
		arg.PaymentDate,
		arg.PaymentTime,
		arg.Amount,
		arg.PaymentMethod,
		arg.ReferenceNumber,
		arg.MobileMoneyNumber,
		arg.BankName,
		arg.ChequeNumber,
		arg.CardLastFour,
		arg.ReceivedBy,
		arg.Notes,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.InvoiceID,
		&i.AccountID,
		&i.PatientID,
		&i.PaymentDate,
		&i.PaymentTime,
		&i.Amount,
		&i.PaymentMethod,
		&i.ReferenceNumber,
		&i.MobileMoneyNumber,
		&i.BankName,
		&i.ChequeNumber,
		&i.CardLastFour,
		&i.ReceivedBy,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deletePayment = `-- name: DeletePayment :exec
UPDATE payments SET deleted_at = now() WHERE id = $1
`

func (q *Queries) DeletePayment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePayment, id)
	return err
}

const getPayment = `-- name: GetPayment :one
SELECT id, hospital_id, invoice_id, account_id, patient_id, payment_date, payment_time, amount, payment_method, reference_number, mobile_money_number, bank_name, cheque_number, card_last_four, received_by, notes, created_at, updated_at, deleted_at FROM payments WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPayment(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.InvoiceID,
		&i.AccountID,
		&i.PatientID,
		&i.PaymentDate,
		&i.PaymentTime,
		&i.Amount,
		&i.PaymentMethod,
		&i.ReferenceNumber,
		&i.MobileMoneyNumber,
		&i.BankName,
		&i.ChequeNumber,
		&i.CardLastFour,
		&i.ReceivedBy,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPaymentTotal = `-- name: GetPaymentTotal :one
SELECT COALESCE(SUM(amount), 0) AS total
FROM payments
WHERE hospital_id = $1
  AND payment_date BETWEEN $2 AND $3
  AND deleted_at IS NULL
`

type GetPaymentTotalParams struct {
	HospitalID    uuid.UUID   `json:"hospital_id"`
	PaymentDate   pgtype.Date `json:"payment_date"`
	PaymentDate_2 pgtype.Date `json:"payment_date_2"`
}

func (q *Queries) GetPaymentTotal(ctx context.Context, arg GetPaymentTotalParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, getPaymentTotal, arg.HospitalID, arg.PaymentDate, arg.PaymentDate_2)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const listPaymentsByDate = `-- name: ListPaymentsByDate :many
SELECT id, hospital_id, invoice_id, account_id, patient_id, payment_date, payment_time, amount, payment_method, reference_number, mobile_money_number, bank_name, cheque_number, card_last_four, received_by, notes, created_at, updated_at, deleted_at FROM payments
WHERE hospital_id = $1
  AND payment_date BETWEEN $2 AND $3
  AND deleted_at IS NULL
ORDER BY payment_date DESC, payment_time DESC
`

type ListPaymentsByDateParams struct {
	HospitalID    uuid.UUID   `json:"hospital_id"`
	PaymentDate   pgtype.Date `json:"payment_date"`
	PaymentDate_2 pgtype.Date `json:"payment_date_2"`
}

func (q *Queries) ListPaymentsByDate(ctx context.Context, arg ListPaymentsByDateParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByDate, arg.HospitalID, arg.PaymentDate, arg.PaymentDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.InvoiceID,
			&i.AccountID,
			&i.PatientID,
			&i.PaymentDate,
			&i.PaymentTime,
			&i.Amount,
			&i.PaymentMethod,
			&i.ReferenceNumber,
			&i.MobileMoneyNumber,
			&i.BankName,
			&i.ChequeNumber,
			&i.CardLastFour,
			&i.ReceivedBy,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByInvoice = `-- name: ListPaymentsByInvoice :many
SELECT id, hospital_id, invoice_id, account_id, patient_id, payment_date, payment_time, amount, payment_method, reference_number, mobile_money_number, bank_name, cheque_number, card_last_four, received_by, notes, created_at, updated_at, deleted_at FROM payments
WHERE invoice_id = $1 AND deleted_at IS NULL
ORDER BY payment_date DESC, payment_time DESC
`

func (q *Queries) ListPaymentsByInvoice(ctx context.Context, invoiceID pgtype.UUID) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByInvoice, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.InvoiceID,
			&i.AccountID,
			&i.PatientID,
			&i.PaymentDate,
			&i.PaymentTime,
			&i.Amount,
			&i.PaymentMethod,
			&i.ReferenceNumber,
			&i.MobileMoneyNumber,
			&i.BankName,
			&i.ChequeNumber,
			&i.CardLastFour,
			&i.ReceivedBy,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByMethod = `-- name: ListPaymentsByMethod :many
SELECT id, hospital_id, invoice_id, account_id, patient_id, payment_date, payment_time, amount, payment_method, reference_number, mobile_money_number, bank_name, cheque_number, card_last_four, received_by, notes, created_at, updated_at, deleted_at FROM payments
WHERE hospital_id = $1 AND payment_method = $2 AND deleted_at IS NULL
ORDER BY payment_date DESC
`

type ListPaymentsByMethodParams struct {
	HospitalID    uuid.UUID     `json:"hospital_id"`
	PaymentMethod PaymentMethod `json:"payment_method"`
}

func (q *Queries) ListPaymentsByMethod(ctx context.Context, arg ListPaymentsByMethodParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByMethod, arg.HospitalID, arg.PaymentMethod)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.InvoiceID,
			&i.AccountID,
			&i.PatientID,
			&i.PaymentDate,
			&i.PaymentTime,
			&i.Amount,
			&i.PaymentMethod,
			&i.ReferenceNumber,
			&i.MobileMoneyNumber,
			&i.BankName,
			&i.ChequeNumber,
			&i.CardLastFour,
			&i.ReceivedBy,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByPatient = `-- name: ListPaymentsByPatient :many
SELECT id, hospital_id, invoice_id, account_id, patient_id, payment_date, payment_time, amount, payment_method, reference_number, mobile_money_number, bank_name, cheque_number, card_last_four, received_by, notes, created_at, updated_at, deleted_at FROM payments
WHERE patient_id = $1 AND deleted_at IS NULL
ORDER BY payment_date DESC, payment_time DESC
LIMIT $2 OFFSET $3
`

type ListPaymentsByPatientParams struct {
	PatientID uuid.UUID `json:"patient_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListPaymentsByPatient(ctx context.Context, arg ListPaymentsByPatientParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByPatient, arg.PatientID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.InvoiceID,
			&i.AccountID,
			&i.PatientID,
			&i.PaymentDate,
			&i.PaymentTime,
			&i.Amount,
			&i.PaymentMethod,
			&i.ReferenceNumber,
			&i.MobileMoneyNumber,
			&i.BankName,
			&i.ChequeNumber,
			&i.CardLastFour,
			&i.ReceivedBy,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
