// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pharmacy_stock.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPharmacyStock = `-- name: CreatePharmacyStock :one
INSERT INTO pharmacy_stock (
    hospital_id, medication_id, batch_number, quantity_current, unit_cost,
    expiry_date, received_date, supplier_name, storage_location, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, hospital_id, medication_id, batch_number, quantity_current, quantity_reserved, quantity_available, unit_cost, expiry_date, received_date, supplier_name, storage_location, is_low_stock, notes, created_at, updated_at, deleted_at
`

type CreatePharmacyStockParams struct {
	HospitalID      uuid.UUID      `json:"hospital_id"`
	MedicationID    uuid.UUID      `json:"medication_id"`
	BatchNumber     string         `json:"batch_number"`
	QuantityCurrent int32          `json:"quantity_current"`
	UnitCost        pgtype.Numeric `json:"unit_cost"`
	ExpiryDate      pgtype.Date    `json:"expiry_date"`
	ReceivedDate    pgtype.Date    `json:"received_date"`
	SupplierName    pgtype.Text    `json:"supplier_name"`
	StorageLocation pgtype.Text    `json:"storage_location"`
	Notes           pgtype.Text    `json:"notes"`
}

func (q *Queries) CreatePharmacyStock(ctx context.Context, arg CreatePharmacyStockParams) (PharmacyStock, error) {
	row := q.db.QueryRow(ctx, createPharmacyStock,
		arg.HospitalID,
		arg.MedicationID,
		arg.BatchNumber,
		arg.QuantityCurrent,
		arg.UnitCost,
		arg.ExpiryDate,
		arg.ReceivedDate,
		arg.SupplierName,
		arg.StorageLocation,
		arg.Notes,
	)
	var i PharmacyStock
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.MedicationID,
		&i.BatchNumber,
		&i.QuantityCurrent,
		&i.QuantityReserved,
		&i.QuantityAvailable,
		&i.UnitCost,
		&i.ExpiryDate,
		&i.ReceivedDate,
		&i.SupplierName,
		&i.StorageLocation,
		&i.IsLowStock,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deletePharmacyStock = `-- name: DeletePharmacyStock :exec
UPDATE pharmacy_stock SET deleted_at = now() WHERE id = $1
`

func (q *Queries) DeletePharmacyStock(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePharmacyStock, id)
	return err
}

const getPharmacyStock = `-- name: GetPharmacyStock :one
SELECT id, hospital_id, medication_id, batch_number, quantity_current, quantity_reserved, quantity_available, unit_cost, expiry_date, received_date, supplier_name, storage_location, is_low_stock, notes, created_at, updated_at, deleted_at FROM pharmacy_stock WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPharmacyStock(ctx context.Context, id uuid.UUID) (PharmacyStock, error) {
	row := q.db.QueryRow(ctx, getPharmacyStock, id)
	var i PharmacyStock
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.MedicationID,
		&i.BatchNumber,
		&i.QuantityCurrent,
		&i.QuantityReserved,
		&i.QuantityAvailable,
		&i.UnitCost,
		&i.ExpiryDate,
		&i.ReceivedDate,
		&i.SupplierName,
		&i.StorageLocation,
		&i.IsLowStock,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listExpiringStock = `-- name: ListExpiringStock :many
SELECT s.id, s.hospital_id, s.medication_id, s.batch_number, s.quantity_current, s.quantity_reserved, s.quantity_available, s.unit_cost, s.expiry_date, s.received_date, s.supplier_name, s.storage_location, s.is_low_stock, s.notes, s.created_at, s.updated_at, s.deleted_at, m.generic_name
FROM pharmacy_stock s
JOIN medications m ON s.medication_id = m.id
WHERE s.hospital_id = $1
  AND s.expiry_date <= $2
  AND s.quantity_current > 0
  AND s.deleted_at IS NULL
ORDER BY s.expiry_date
`

type ListExpiringStockParams struct {
	HospitalID uuid.UUID   `json:"hospital_id"`
	ExpiryDate pgtype.Date `json:"expiry_date"`
}

type ListExpiringStockRow struct {
	ID                uuid.UUID          `json:"id"`
	HospitalID        uuid.UUID          `json:"hospital_id"`
	MedicationID      uuid.UUID          `json:"medication_id"`
	BatchNumber       string             `json:"batch_number"`
	QuantityCurrent   int32              `json:"quantity_current"`
	QuantityReserved  int32              `json:"quantity_reserved"`
	QuantityAvailable int32              `json:"quantity_available"`
	UnitCost          pgtype.Numeric     `json:"unit_cost"`
	ExpiryDate        pgtype.Date        `json:"expiry_date"`
	ReceivedDate      pgtype.Date        `json:"received_date"`
	SupplierName      pgtype.Text        `json:"supplier_name"`
	StorageLocation   pgtype.Text        `json:"storage_location"`
	IsLowStock        bool               `json:"is_low_stock"`
	Notes             pgtype.Text        `json:"notes"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	GenericName       string             `json:"generic_name"`
}

func (q *Queries) ListExpiringStock(ctx context.Context, arg ListExpiringStockParams) ([]ListExpiringStockRow, error) {
	rows, err := q.db.Query(ctx, listExpiringStock, arg.HospitalID, arg.ExpiryDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpiringStockRow
	for rows.Next() {
		var i ListExpiringStockRow
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.MedicationID,
			&i.BatchNumber,
			&i.QuantityCurrent,
			&i.QuantityReserved,
			&i.QuantityAvailable,
			&i.UnitCost,
			&i.ExpiryDate,
			&i.ReceivedDate,
			&i.SupplierName,
			&i.StorageLocation,
			&i.IsLowStock,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.GenericName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLowStock = `-- name: ListLowStock :many
SELECT s.id, s.hospital_id, s.medication_id, s.batch_number, s.quantity_current, s.quantity_reserved, s.quantity_available, s.unit_cost, s.expiry_date, s.received_date, s.supplier_name, s.storage_location, s.is_low_stock, s.notes, s.created_at, s.updated_at, s.deleted_at, m.generic_name, m.reorder_level
FROM pharmacy_stock s
JOIN medications m ON s.medication_id = m.id
WHERE s.hospital_id = $1 AND s.is_low_stock = TRUE AND s.deleted_at IS NULL
ORDER BY m.generic_name
`

type ListLowStockRow struct {
	ID                uuid.UUID          `json:"id"`
	HospitalID        uuid.UUID          `json:"hospital_id"`
	MedicationID      uuid.UUID          `json:"medication_id"`
	BatchNumber       string             `json:"batch_number"`
	QuantityCurrent   int32              `json:"quantity_current"`
	QuantityReserved  int32              `json:"quantity_reserved"`
	QuantityAvailable int32              `json:"quantity_available"`
	UnitCost          pgtype.Numeric     `json:"unit_cost"`
	ExpiryDate        pgtype.Date        `json:"expiry_date"`
	ReceivedDate      pgtype.Date        `json:"received_date"`
	SupplierName      pgtype.Text        `json:"supplier_name"`
	StorageLocation   pgtype.Text        `json:"storage_location"`
	IsLowStock        bool               `json:"is_low_stock"`
	Notes             pgtype.Text        `json:"notes"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	GenericName       string             `json:"generic_name"`
	ReorderLevel      pgtype.Int4        `json:"reorder_level"`
}

func (q *Queries) ListLowStock(ctx context.Context, hospitalID uuid.UUID) ([]ListLowStockRow, error) {
	rows, err := q.db.Query(ctx, listLowStock, hospitalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLowStockRow
	for rows.Next() {
		var i ListLowStockRow
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.MedicationID,
			&i.BatchNumber,
			&i.QuantityCurrent,
			&i.QuantityReserved,
			&i.QuantityAvailable,
			&i.UnitCost,
			&i.ExpiryDate,
			&i.ReceivedDate,
			&i.SupplierName,
			&i.StorageLocation,
			&i.IsLowStock,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.GenericName,
			&i.ReorderLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockByMedication = `-- name: ListStockByMedication :many
SELECT id, hospital_id, medication_id, batch_number, quantity_current, quantity_reserved, quantity_available, unit_cost, expiry_date, received_date, supplier_name, storage_location, is_low_stock, notes, created_at, updated_at, deleted_at FROM pharmacy_stock
WHERE medication_id = $1 AND deleted_at IS NULL
ORDER BY expiry_date
`

func (q *Queries) ListStockByMedication(ctx context.Context, medicationID uuid.UUID) ([]PharmacyStock, error) {
	rows, err := q.db.Query(ctx, listStockByMedication, medicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PharmacyStock
	for rows.Next() {
		var i PharmacyStock
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.MedicationID,
			&i.BatchNumber,
			&i.QuantityCurrent,
			&i.QuantityReserved,
			&i.QuantityAvailable,
			&i.UnitCost,
			&i.ExpiryDate,
			&i.ReceivedDate,
			&i.SupplierName,
			&i.StorageLocation,
			&i.IsLowStock,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStockQuantity = `-- name: UpdateStockQuantity :one
UPDATE pharmacy_stock
SET quantity_current = $2, quantity_available = $2 - quantity_reserved
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, hospital_id, medication_id, batch_number, quantity_current, quantity_reserved, quantity_available, unit_cost, expiry_date, received_date, supplier_name, storage_location, is_low_stock, notes, created_at, updated_at, deleted_at
`

type UpdateStockQuantityParams struct {
	ID              uuid.UUID `json:"id"`
	QuantityCurrent int32     `json:"quantity_current"`
}

func (q *Queries) UpdateStockQuantity(ctx context.Context, arg UpdateStockQuantityParams) (PharmacyStock, error) {
	row := q.db.QueryRow(ctx, updateStockQuantity, arg.ID, arg.QuantityCurrent)
	var i PharmacyStock
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.MedicationID,
		&i.BatchNumber,
		&i.QuantityCurrent,
		&i.QuantityReserved,
		&i.QuantityAvailable,
		&i.UnitCost,
		&i.ExpiryDate,
		&i.ReceivedDate,
		&i.SupplierName,
		&i.StorageLocation,
		&i.IsLowStock,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
