// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: power_outage_logs.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPowerOutageLog = `-- name: CreatePowerOutageLog :one
INSERT INTO power_outage_logs (
    hospital_id, outage_start, outage_end, duration_mins, affected_sessions,
    sessions_terminated_count, sessions_paused_count, generator_available,
    generator_start_delay_mins, backup_power_duration_mins, logged_by,
    incident_severity, patient_safety_impact, equipment_damage,
    data_loss_occurred, recovery_actions, utility_company_notified,
    incident_report_filed, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19)
RETURNING id, hospital_id, outage_start, outage_end, duration_mins, affected_sessions, sessions_terminated_count, sessions_paused_count, generator_available, generator_start_delay_mins, backup_power_duration_mins, logged_by, incident_severity, patient_safety_impact, equipment_damage, data_loss_occurred, recovery_actions, utility_company_notified, incident_report_filed, notes, created_at, updated_at, deleted_at
`

type CreatePowerOutageLogParams struct {
	HospitalID              uuid.UUID          `json:"hospital_id"`
	OutageStart             pgtype.Timestamptz `json:"outage_start"`
	OutageEnd               pgtype.Timestamptz `json:"outage_end"`
	DurationMins            pgtype.Int4        `json:"duration_mins"`
	AffectedSessions        []uuid.UUID        `json:"affected_sessions"`
	SessionsTerminatedCount pgtype.Int4        `json:"sessions_terminated_count"`
	SessionsPausedCount     pgtype.Int4        `json:"sessions_paused_count"`
	GeneratorAvailable      bool               `json:"generator_available"`
	GeneratorStartDelayMins pgtype.Int4        `json:"generator_start_delay_mins"`
	BackupPowerDurationMins pgtype.Int4        `json:"backup_power_duration_mins"`
	LoggedBy                uuid.UUID          `json:"logged_by"`
	IncidentSeverity        string             `json:"incident_severity"`
	PatientSafetyImpact     pgtype.Text        `json:"patient_safety_impact"`
	EquipmentDamage         pgtype.Text        `json:"equipment_damage"`
	DataLossOccurred        bool               `json:"data_loss_occurred"`
	RecoveryActions         pgtype.Text        `json:"recovery_actions"`
	UtilityCompanyNotified  bool               `json:"utility_company_notified"`
	IncidentReportFiled     bool               `json:"incident_report_filed"`
	Notes                   pgtype.Text        `json:"notes"`
}

func (q *Queries) CreatePowerOutageLog(ctx context.Context, arg CreatePowerOutageLogParams) (PowerOutageLog, error) {
	row := q.db.QueryRow(ctx, createPowerOutageLog,
		arg.HospitalID,
		arg.OutageStart,
		arg.OutageEnd,
		arg.DurationMins,
		arg.AffectedSessions,
		arg.SessionsTerminatedCount,
		arg.SessionsPausedCount,
		arg.GeneratorAvailable,
		arg.GeneratorStartDelayMins,
		arg.BackupPowerDurationMins,
		arg.LoggedBy,
		arg.IncidentSeverity,
		arg.PatientSafetyImpact,
		arg.EquipmentDamage,
		arg.DataLossOccurred,
		arg.RecoveryActions,
		arg.UtilityCompanyNotified,
		arg.IncidentReportFiled,
		arg.Notes,
	)
	var i PowerOutageLog
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.OutageStart,
		&i.OutageEnd,
		&i.DurationMins,
		&i.AffectedSessions,
		&i.SessionsTerminatedCount,
		&i.SessionsPausedCount,
		&i.GeneratorAvailable,
		&i.GeneratorStartDelayMins,
		&i.BackupPowerDurationMins,
		&i.LoggedBy,
		&i.IncidentSeverity,
		&i.PatientSafetyImpact,
		&i.EquipmentDamage,
		&i.DataLossOccurred,
		&i.RecoveryActions,
		&i.UtilityCompanyNotified,
		&i.IncidentReportFiled,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deletePowerOutageLog = `-- name: DeletePowerOutageLog :exec
UPDATE power_outage_logs SET deleted_at = now() WHERE id = $1
`

func (q *Queries) DeletePowerOutageLog(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePowerOutageLog, id)
	return err
}

const endPowerOutage = `-- name: EndPowerOutage :one
UPDATE power_outage_logs
SET outage_end = $2, duration_mins = $3, recovery_actions = $4
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, hospital_id, outage_start, outage_end, duration_mins, affected_sessions, sessions_terminated_count, sessions_paused_count, generator_available, generator_start_delay_mins, backup_power_duration_mins, logged_by, incident_severity, patient_safety_impact, equipment_damage, data_loss_occurred, recovery_actions, utility_company_notified, incident_report_filed, notes, created_at, updated_at, deleted_at
`

type EndPowerOutageParams struct {
	ID              uuid.UUID          `json:"id"`
	OutageEnd       pgtype.Timestamptz `json:"outage_end"`
	DurationMins    pgtype.Int4        `json:"duration_mins"`
	RecoveryActions pgtype.Text        `json:"recovery_actions"`
}

func (q *Queries) EndPowerOutage(ctx context.Context, arg EndPowerOutageParams) (PowerOutageLog, error) {
	row := q.db.QueryRow(ctx, endPowerOutage,
		arg.ID,
		arg.OutageEnd,
		arg.DurationMins,
		arg.RecoveryActions,
	)
	var i PowerOutageLog
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.OutageStart,
		&i.OutageEnd,
		&i.DurationMins,
		&i.AffectedSessions,
		&i.SessionsTerminatedCount,
		&i.SessionsPausedCount,
		&i.GeneratorAvailable,
		&i.GeneratorStartDelayMins,
		&i.BackupPowerDurationMins,
		&i.LoggedBy,
		&i.IncidentSeverity,
		&i.PatientSafetyImpact,
		&i.EquipmentDamage,
		&i.DataLossOccurred,
		&i.RecoveryActions,
		&i.UtilityCompanyNotified,
		&i.IncidentReportFiled,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPowerOutageLog = `-- name: GetPowerOutageLog :one
SELECT id, hospital_id, outage_start, outage_end, duration_mins, affected_sessions, sessions_terminated_count, sessions_paused_count, generator_available, generator_start_delay_mins, backup_power_duration_mins, logged_by, incident_severity, patient_safety_impact, equipment_damage, data_loss_occurred, recovery_actions, utility_company_notified, incident_report_filed, notes, created_at, updated_at, deleted_at FROM power_outage_logs WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPowerOutageLog(ctx context.Context, id uuid.UUID) (PowerOutageLog, error) {
	row := q.db.QueryRow(ctx, getPowerOutageLog, id)
	var i PowerOutageLog
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.OutageStart,
		&i.OutageEnd,
		&i.DurationMins,
		&i.AffectedSessions,
		&i.SessionsTerminatedCount,
		&i.SessionsPausedCount,
		&i.GeneratorAvailable,
		&i.GeneratorStartDelayMins,
		&i.BackupPowerDurationMins,
		&i.LoggedBy,
		&i.IncidentSeverity,
		&i.PatientSafetyImpact,
		&i.EquipmentDamage,
		&i.DataLossOccurred,
		&i.RecoveryActions,
		&i.UtilityCompanyNotified,
		&i.IncidentReportFiled,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listOngoingOutages = `-- name: ListOngoingOutages :many
SELECT id, hospital_id, outage_start, outage_end, duration_mins, affected_sessions, sessions_terminated_count, sessions_paused_count, generator_available, generator_start_delay_mins, backup_power_duration_mins, logged_by, incident_severity, patient_safety_impact, equipment_damage, data_loss_occurred, recovery_actions, utility_company_notified, incident_report_filed, notes, created_at, updated_at, deleted_at FROM power_outage_logs
WHERE hospital_id = $1
  AND outage_end IS NULL
  AND deleted_at IS NULL
ORDER BY outage_start
`

func (q *Queries) ListOngoingOutages(ctx context.Context, hospitalID uuid.UUID) ([]PowerOutageLog, error) {
	rows, err := q.db.Query(ctx, listOngoingOutages, hospitalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PowerOutageLog
	for rows.Next() {
		var i PowerOutageLog
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.OutageStart,
			&i.OutageEnd,
			&i.DurationMins,
			&i.AffectedSessions,
			&i.SessionsTerminatedCount,
			&i.SessionsPausedCount,
			&i.GeneratorAvailable,
			&i.GeneratorStartDelayMins,
			&i.BackupPowerDurationMins,
			&i.LoggedBy,
			&i.IncidentSeverity,
			&i.PatientSafetyImpact,
			&i.EquipmentDamage,
			&i.DataLossOccurred,
			&i.RecoveryActions,
			&i.UtilityCompanyNotified,
			&i.IncidentReportFiled,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPowerOutagesByHospital = `-- name: ListPowerOutagesByHospital :many
SELECT id, hospital_id, outage_start, outage_end, duration_mins, affected_sessions, sessions_terminated_count, sessions_paused_count, generator_available, generator_start_delay_mins, backup_power_duration_mins, logged_by, incident_severity, patient_safety_impact, equipment_damage, data_loss_occurred, recovery_actions, utility_company_notified, incident_report_filed, notes, created_at, updated_at, deleted_at FROM power_outage_logs
WHERE hospital_id = $1 AND deleted_at IS NULL
ORDER BY outage_start DESC
`

func (q *Queries) ListPowerOutagesByHospital(ctx context.Context, hospitalID uuid.UUID) ([]PowerOutageLog, error) {
	rows, err := q.db.Query(ctx, listPowerOutagesByHospital, hospitalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PowerOutageLog
	for rows.Next() {
		var i PowerOutageLog
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.OutageStart,
			&i.OutageEnd,
			&i.DurationMins,
			&i.AffectedSessions,
			&i.SessionsTerminatedCount,
			&i.SessionsPausedCount,
			&i.GeneratorAvailable,
			&i.GeneratorStartDelayMins,
			&i.BackupPowerDurationMins,
			&i.LoggedBy,
			&i.IncidentSeverity,
			&i.PatientSafetyImpact,
			&i.EquipmentDamage,
			&i.DataLossOccurred,
			&i.RecoveryActions,
			&i.UtilityCompanyNotified,
			&i.IncidentReportFiled,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSevereOutages = `-- name: ListSevereOutages :many
SELECT id, hospital_id, outage_start, outage_end, duration_mins, affected_sessions, sessions_terminated_count, sessions_paused_count, generator_available, generator_start_delay_mins, backup_power_duration_mins, logged_by, incident_severity, patient_safety_impact, equipment_damage, data_loss_occurred, recovery_actions, utility_company_notified, incident_report_filed, notes, created_at, updated_at, deleted_at FROM power_outage_logs
WHERE hospital_id = $1
  AND incident_severity IN ('severe', 'life_threatening')
  AND deleted_at IS NULL
ORDER BY outage_start DESC
`

func (q *Queries) ListSevereOutages(ctx context.Context, hospitalID uuid.UUID) ([]PowerOutageLog, error) {
	rows, err := q.db.Query(ctx, listSevereOutages, hospitalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PowerOutageLog
	for rows.Next() {
		var i PowerOutageLog
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.OutageStart,
			&i.OutageEnd,
			&i.DurationMins,
			&i.AffectedSessions,
			&i.SessionsTerminatedCount,
			&i.SessionsPausedCount,
			&i.GeneratorAvailable,
			&i.GeneratorStartDelayMins,
			&i.BackupPowerDurationMins,
			&i.LoggedBy,
			&i.IncidentSeverity,
			&i.PatientSafetyImpact,
			&i.EquipmentDamage,
			&i.DataLossOccurred,
			&i.RecoveryActions,
			&i.UtilityCompanyNotified,
			&i.IncidentReportFiled,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
