// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prescriptions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelPrescription = `-- name: CancelPrescription :one
UPDATE prescriptions
SET status = 'cancelled', cancelled_by = $2, cancelled_at = now(), cancellation_reason = $3
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, hospital_id, patient_id, session_id, prescribed_by, prescribed_date, prescribed_time, status, valid_from, valid_until, diagnosis, clinical_notes, pharmacist_verified_by, pharmacist_verified_at, dispensed_by, dispensed_at, cancelled_by, cancelled_at, cancellation_reason, created_at, updated_at, deleted_at
`

type CancelPrescriptionParams struct {
	ID                 uuid.UUID   `json:"id"`
	CancelledBy        pgtype.UUID `json:"cancelled_by"`
	CancellationReason pgtype.Text `json:"cancellation_reason"`
}

func (q *Queries) CancelPrescription(ctx context.Context, arg CancelPrescriptionParams) (Prescription, error) {
	row := q.db.QueryRow(ctx, cancelPrescription, arg.ID, arg.CancelledBy, arg.CancellationReason)
	var i Prescription
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.PatientID,
		&i.SessionID,
		&i.PrescribedBy,
		&i.PrescribedDate,
		&i.PrescribedTime,
		&i.Status,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.Diagnosis,
		&i.ClinicalNotes,
		&i.PharmacistVerifiedBy,
		&i.PharmacistVerifiedAt,
		&i.DispensedBy,
		&i.DispensedAt,
		&i.CancelledBy,
		&i.CancelledAt,
		&i.CancellationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createPrescription = `-- name: CreatePrescription :one
INSERT INTO prescriptions (
    hospital_id, patient_id, session_id, prescribed_by, prescribed_date,
    prescribed_time, valid_from, valid_until, diagnosis, clinical_notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, hospital_id, patient_id, session_id, prescribed_by, prescribed_date, prescribed_time, status, valid_from, valid_until, diagnosis, clinical_notes, pharmacist_verified_by, pharmacist_verified_at, dispensed_by, dispensed_at, cancelled_by, cancelled_at, cancellation_reason, created_at, updated_at, deleted_at
`

type CreatePrescriptionParams struct {
	HospitalID     uuid.UUID   `json:"hospital_id"`
	PatientID      uuid.UUID   `json:"patient_id"`
	SessionID      pgtype.UUID `json:"session_id"`
	PrescribedBy   uuid.UUID   `json:"prescribed_by"`
	PrescribedDate pgtype.Date `json:"prescribed_date"`
	PrescribedTime pgtype.Time `json:"prescribed_time"`
	ValidFrom      pgtype.Date `json:"valid_from"`
	ValidUntil     pgtype.Date `json:"valid_until"`
	Diagnosis      pgtype.Text `json:"diagnosis"`
	ClinicalNotes  pgtype.Text `json:"clinical_notes"`
}

func (q *Queries) CreatePrescription(ctx context.Context, arg CreatePrescriptionParams) (Prescription, error) {
	row := q.db.QueryRow(ctx, createPrescription,
		arg.HospitalID,
		arg.PatientID,
		arg.SessionID,
		arg.PrescribedBy,
		arg.PrescribedDate,
		arg.PrescribedTime,
		arg.ValidFrom,
		arg.ValidUntil,
		arg.Diagnosis,
		arg.ClinicalNotes,
	)
	var i Prescription
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.PatientID,
		&i.SessionID,
		&i.PrescribedBy,
		&i.PrescribedDate,
		&i.PrescribedTime,
		&i.Status,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.Diagnosis,
		&i.ClinicalNotes,
		&i.PharmacistVerifiedBy,
		&i.PharmacistVerifiedAt,
		&i.DispensedBy,
		&i.DispensedAt,
		&i.CancelledBy,
		&i.CancelledAt,
		&i.CancellationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deletePrescription = `-- name: DeletePrescription :exec
UPDATE prescriptions SET deleted_at = now() WHERE id = $1
`

func (q *Queries) DeletePrescription(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePrescription, id)
	return err
}

const dispensePrescription = `-- name: DispensePrescription :one
UPDATE prescriptions
SET dispensed_by = $2, dispensed_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, hospital_id, patient_id, session_id, prescribed_by, prescribed_date, prescribed_time, status, valid_from, valid_until, diagnosis, clinical_notes, pharmacist_verified_by, pharmacist_verified_at, dispensed_by, dispensed_at, cancelled_by, cancelled_at, cancellation_reason, created_at, updated_at, deleted_at
`

type DispensePrescriptionParams struct {
	ID          uuid.UUID   `json:"id"`
	DispensedBy pgtype.UUID `json:"dispensed_by"`
}

func (q *Queries) DispensePrescription(ctx context.Context, arg DispensePrescriptionParams) (Prescription, error) {
	row := q.db.QueryRow(ctx, dispensePrescription, arg.ID, arg.DispensedBy)
	var i Prescription
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.PatientID,
		&i.SessionID,
		&i.PrescribedBy,
		&i.PrescribedDate,
		&i.PrescribedTime,
		&i.Status,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.Diagnosis,
		&i.ClinicalNotes,
		&i.PharmacistVerifiedBy,
		&i.PharmacistVerifiedAt,
		&i.DispensedBy,
		&i.DispensedAt,
		&i.CancelledBy,
		&i.CancelledAt,
		&i.CancellationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPrescription = `-- name: GetPrescription :one
SELECT id, hospital_id, patient_id, session_id, prescribed_by, prescribed_date, prescribed_time, status, valid_from, valid_until, diagnosis, clinical_notes, pharmacist_verified_by, pharmacist_verified_at, dispensed_by, dispensed_at, cancelled_by, cancelled_at, cancellation_reason, created_at, updated_at, deleted_at FROM prescriptions WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPrescription(ctx context.Context, id uuid.UUID) (Prescription, error) {
	row := q.db.QueryRow(ctx, getPrescription, id)
	var i Prescription
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.PatientID,
		&i.SessionID,
		&i.PrescribedBy,
		&i.PrescribedDate,
		&i.PrescribedTime,
		&i.Status,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.Diagnosis,
		&i.ClinicalNotes,
		&i.PharmacistVerifiedBy,
		&i.PharmacistVerifiedAt,
		&i.DispensedBy,
		&i.DispensedAt,
		&i.CancelledBy,
		&i.CancelledAt,
		&i.CancellationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listActivePrescriptions = `-- name: ListActivePrescriptions :many
SELECT id, hospital_id, patient_id, session_id, prescribed_by, prescribed_date, prescribed_time, status, valid_from, valid_until, diagnosis, clinical_notes, pharmacist_verified_by, pharmacist_verified_at, dispensed_by, dispensed_at, cancelled_by, cancelled_at, cancellation_reason, created_at, updated_at, deleted_at FROM prescriptions
WHERE hospital_id = $1 AND status = 'active' AND deleted_at IS NULL
ORDER BY prescribed_date DESC
`

func (q *Queries) ListActivePrescriptions(ctx context.Context, hospitalID uuid.UUID) ([]Prescription, error) {
	rows, err := q.db.Query(ctx, listActivePrescriptions, hospitalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Prescription
	for rows.Next() {
		var i Prescription
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.PatientID,
			&i.SessionID,
			&i.PrescribedBy,
			&i.PrescribedDate,
			&i.PrescribedTime,
			&i.Status,
			&i.ValidFrom,
			&i.ValidUntil,
			&i.Diagnosis,
			&i.ClinicalNotes,
			&i.PharmacistVerifiedBy,
			&i.PharmacistVerifiedAt,
			&i.DispensedBy,
			&i.DispensedAt,
			&i.CancelledBy,
			&i.CancelledAt,
			&i.CancellationReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMedicationPrescriptionsByPatient = `-- name: ListMedicationPrescriptionsByPatient :many
SELECT id, hospital_id, patient_id, session_id, prescribed_by, prescribed_date, prescribed_time, status, valid_from, valid_until, diagnosis, clinical_notes, pharmacist_verified_by, pharmacist_verified_at, dispensed_by, dispensed_at, cancelled_by, cancelled_at, cancellation_reason, created_at, updated_at, deleted_at FROM prescriptions
WHERE patient_id = $1 AND deleted_at IS NULL
ORDER BY prescribed_date DESC, prescribed_time DESC
LIMIT $2 OFFSET $3
`

type ListMedicationPrescriptionsByPatientParams struct {
	PatientID uuid.UUID `json:"patient_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListMedicationPrescriptionsByPatient(ctx context.Context, arg ListMedicationPrescriptionsByPatientParams) ([]Prescription, error) {
	rows, err := q.db.Query(ctx, listMedicationPrescriptionsByPatient, arg.PatientID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Prescription
	for rows.Next() {
		var i Prescription
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.PatientID,
			&i.SessionID,
			&i.PrescribedBy,
			&i.PrescribedDate,
			&i.PrescribedTime,
			&i.Status,
			&i.ValidFrom,
			&i.ValidUntil,
			&i.Diagnosis,
			&i.ClinicalNotes,
			&i.PharmacistVerifiedBy,
			&i.PharmacistVerifiedAt,
			&i.DispensedBy,
			&i.DispensedAt,
			&i.CancelledBy,
			&i.CancelledAt,
			&i.CancellationReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const verifyPrescription = `-- name: VerifyPrescription :one
UPDATE prescriptions
SET pharmacist_verified_by = $2, pharmacist_verified_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, hospital_id, patient_id, session_id, prescribed_by, prescribed_date, prescribed_time, status, valid_from, valid_until, diagnosis, clinical_notes, pharmacist_verified_by, pharmacist_verified_at, dispensed_by, dispensed_at, cancelled_by, cancelled_at, cancellation_reason, created_at, updated_at, deleted_at
`

type VerifyPrescriptionParams struct {
	ID                   uuid.UUID   `json:"id"`
	PharmacistVerifiedBy pgtype.UUID `json:"pharmacist_verified_by"`
}

func (q *Queries) VerifyPrescription(ctx context.Context, arg VerifyPrescriptionParams) (Prescription, error) {
	row := q.db.QueryRow(ctx, verifyPrescription, arg.ID, arg.PharmacistVerifiedBy)
	var i Prescription
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.PatientID,
		&i.SessionID,
		&i.PrescribedBy,
		&i.PrescribedDate,
		&i.PrescribedTime,
		&i.Status,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.Diagnosis,
		&i.ClinicalNotes,
		&i.PharmacistVerifiedBy,
		&i.PharmacistVerifiedAt,
		&i.DispensedBy,
		&i.DispensedAt,
		&i.CancelledBy,
		&i.CancelledAt,
		&i.CancellationReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
