// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prescription_items.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPrescriptionItem = `-- name: CreatePrescriptionItem :one
INSERT INTO prescription_items (
    hospital_id, prescription_id, medication_id, dose, frequency, route,
    duration_days, quantity_prescribed, instructions, start_date, end_date,
    is_prn, prn_indication, is_stat, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, hospital_id, prescription_id, medication_id, dose, frequency, route, duration_days, quantity_prescribed, quantity_dispensed, instructions, start_date, end_date, is_prn, prn_indication, is_stat, notes, created_at, updated_at, deleted_at
`

type CreatePrescriptionItemParams struct {
	HospitalID         uuid.UUID       `json:"hospital_id"`
	PrescriptionID     uuid.UUID       `json:"prescription_id"`
	MedicationID       uuid.UUID       `json:"medication_id"`
	Dose               string          `json:"dose"`
	Frequency          string          `json:"frequency"`
	Route              MedicationRoute `json:"route"`
	DurationDays       pgtype.Int4     `json:"duration_days"`
	QuantityPrescribed int32           `json:"quantity_prescribed"`
	Instructions       pgtype.Text     `json:"instructions"`
	StartDate          pgtype.Date     `json:"start_date"`
	EndDate            pgtype.Date     `json:"end_date"`
	IsPrn              bool            `json:"is_prn"`
	PrnIndication      pgtype.Text     `json:"prn_indication"`
	IsStat             bool            `json:"is_stat"`
	Notes              pgtype.Text     `json:"notes"`
}

func (q *Queries) CreatePrescriptionItem(ctx context.Context, arg CreatePrescriptionItemParams) (PrescriptionItem, error) {
	row := q.db.QueryRow(ctx, createPrescriptionItem,
		arg.HospitalID,
		arg.PrescriptionID,
		arg.MedicationID,
		arg.Dose,
		arg.Frequency,
		arg.Route,
		arg.DurationDays,
		arg.QuantityPrescribed,
		arg.Instructions,
		arg.StartDate,
		arg.EndDate,
		arg.IsPrn,
		arg.PrnIndication,
		arg.IsStat,
		arg.Notes,
	)
	var i PrescriptionItem
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.PrescriptionID,
		&i.MedicationID,
		&i.Dose,
		&i.Frequency,
		&i.Route,
		&i.DurationDays,
		&i.QuantityPrescribed,
		&i.QuantityDispensed,
		&i.Instructions,
		&i.StartDate,
		&i.EndDate,
		&i.IsPrn,
		&i.PrnIndication,
		&i.IsStat,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deletePrescriptionItem = `-- name: DeletePrescriptionItem :exec
UPDATE prescription_items SET deleted_at = now() WHERE id = $1
`

func (q *Queries) DeletePrescriptionItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePrescriptionItem, id)
	return err
}

const getPrescriptionItem = `-- name: GetPrescriptionItem :one
SELECT id, hospital_id, prescription_id, medication_id, dose, frequency, route, duration_days, quantity_prescribed, quantity_dispensed, instructions, start_date, end_date, is_prn, prn_indication, is_stat, notes, created_at, updated_at, deleted_at FROM prescription_items WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPrescriptionItem(ctx context.Context, id uuid.UUID) (PrescriptionItem, error) {
	row := q.db.QueryRow(ctx, getPrescriptionItem, id)
	var i PrescriptionItem
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.PrescriptionID,
		&i.MedicationID,
		&i.Dose,
		&i.Frequency,
		&i.Route,
		&i.DurationDays,
		&i.QuantityPrescribed,
		&i.QuantityDispensed,
		&i.Instructions,
		&i.StartDate,
		&i.EndDate,
		&i.IsPrn,
		&i.PrnIndication,
		&i.IsStat,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listActiveMedicationIDsForPatient = `-- name: ListActiveMedicationIDsForPatient :many
SELECT DISTINCT pi.medication_id
FROM prescription_items pi
JOIN prescriptions p ON p.id = pi.prescription_id
WHERE p.patient_id = $1
  AND p.status = 'active'
  AND p.deleted_at IS NULL
  AND pi.deleted_at IS NULL
  AND (pi.end_date IS NULL OR pi.end_date >= CURRENT_DATE)
`

func (q *Queries) ListActiveMedicationIDsForPatient(ctx context.Context, patientID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listActiveMedicationIDsForPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var medication_id uuid.UUID
		if err := rows.Scan(&medication_id); err != nil {
			return nil, err
		}
		items = append(items, medication_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrescriptionItemsByPrescription = `-- name: ListPrescriptionItemsByPrescription :many
SELECT id, hospital_id, prescription_id, medication_id, dose, frequency, route, duration_days, quantity_prescribed, quantity_dispensed, instructions, start_date, end_date, is_prn, prn_indication, is_stat, notes, created_at, updated_at, deleted_at FROM prescription_items
WHERE prescription_id = $1 AND deleted_at IS NULL
ORDER BY created_at
`

func (q *Queries) ListPrescriptionItemsByPrescription(ctx context.Context, prescriptionID uuid.UUID) ([]PrescriptionItem, error) {
	rows, err := q.db.Query(ctx, listPrescriptionItemsByPrescription, prescriptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrescriptionItem
	for rows.Next() {
		var i PrescriptionItem
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.PrescriptionID,
			&i.MedicationID,
			&i.Dose,
			&i.Frequency,
			&i.Route,
			&i.DurationDays,
			&i.QuantityPrescribed,
			&i.QuantityDispensed,
			&i.Instructions,
			&i.StartDate,
			&i.EndDate,
			&i.IsPrn,
			&i.PrnIndication,
			&i.IsStat,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDispensedQuantity = `-- name: UpdateDispensedQuantity :one
UPDATE prescription_items
SET quantity_dispensed = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, hospital_id, prescription_id, medication_id, dose, frequency, route, duration_days, quantity_prescribed, quantity_dispensed, instructions, start_date, end_date, is_prn, prn_indication, is_stat, notes, created_at, updated_at, deleted_at
`

type UpdateDispensedQuantityParams struct {
	ID                uuid.UUID   `json:"id"`
	QuantityDispensed pgtype.Int4 `json:"quantity_dispensed"`
}

func (q *Queries) UpdateDispensedQuantity(ctx context.Context, arg UpdateDispensedQuantityParams) (PrescriptionItem, error) {
	row := q.db.QueryRow(ctx, updateDispensedQuantity, arg.ID, arg.QuantityDispensed)
	var i PrescriptionItem
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.PrescriptionID,
		&i.MedicationID,
		&i.Dose,
		&i.Frequency,
		&i.Route,
		&i.DurationDays,
		&i.QuantityPrescribed,
		&i.QuantityDispensed,
		&i.Instructions,
		&i.StartDate,
		&i.EndDate,
		&i.IsPrn,
		&i.PrnIndication,
		&i.IsStat,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
