// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: price_lists.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPriceList = `-- name: CreatePriceList :one
INSERT INTO price_lists (
    hospital_id, service_name, service_code, service_category,
    unit_price, scheme_id, effective_from, effective_until, description
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, hospital_id, service_name, service_code, service_category, unit_price, scheme_id, effective_from, effective_until, description, is_active, created_at, updated_at, deleted_at
`

type CreatePriceListParams struct {
	HospitalID      uuid.UUID      `json:"hospital_id"`
	ServiceName     string         `json:"service_name"`
	ServiceCode     pgtype.Text    `json:"service_code"`
	ServiceCategory pgtype.Text    `json:"service_category"`
	UnitPrice       pgtype.Numeric `json:"unit_price"`
	SchemeID        pgtype.UUID    `json:"scheme_id"`
	EffectiveFrom   pgtype.Date    `json:"effective_from"`
	EffectiveUntil  pgtype.Date    `json:"effective_until"`
	Description     pgtype.Text    `json:"description"`
}

func (q *Queries) CreatePriceList(ctx context.Context, arg CreatePriceListParams) (PriceList, error) {
	row := q.db.QueryRow(ctx, createPriceList,
		arg.HospitalID,
		arg.ServiceName,
		arg.ServiceCode,
		arg.ServiceCategory,
		arg.UnitPrice,
		arg.SchemeID,
		arg.EffectiveFrom,
		arg.EffectiveUntil,
		arg.Description,
	)
	var i PriceList
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.ServiceName,
		&i.ServiceCode,
		&i.ServiceCategory,
		&i.UnitPrice,
		&i.SchemeID,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deletePriceList = `-- name: DeletePriceList :exec
UPDATE price_lists SET deleted_at = now() WHERE id = $1
`

func (q *Queries) DeletePriceList(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePriceList, id)
	return err
}

const getPriceByServiceCode = `-- name: GetPriceByServiceCode :one
SELECT id, hospital_id, service_name, service_code, service_category, unit_price, scheme_id, effective_from, effective_until, description, is_active, created_at, updated_at, deleted_at FROM price_lists
WHERE hospital_id = $1
  AND service_code = $2
  AND (scheme_id = $3 OR scheme_id IS NULL)
  AND effective_from <= CURRENT_DATE
  AND (effective_until IS NULL OR effective_until >= CURRENT_DATE)
  AND deleted_at IS NULL
ORDER BY scheme_id DESC NULLS LAST
LIMIT 1
`

type GetPriceByServiceCodeParams struct {
	HospitalID  uuid.UUID   `json:"hospital_id"`
	ServiceCode pgtype.Text `json:"service_code"`
	SchemeID    pgtype.UUID `json:"scheme_id"`
}

func (q *Queries) GetPriceByServiceCode(ctx context.Context, arg GetPriceByServiceCodeParams) (PriceList, error) {
	row := q.db.QueryRow(ctx, getPriceByServiceCode, arg.HospitalID, arg.ServiceCode, arg.SchemeID)
	var i PriceList
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.ServiceName,
		&i.ServiceCode,
		&i.ServiceCategory,
		&i.UnitPrice,
		&i.SchemeID,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPriceList = `-- name: GetPriceList :one
SELECT id, hospital_id, service_name, service_code, service_category, unit_price, scheme_id, effective_from, effective_until, description, is_active, created_at, updated_at, deleted_at FROM price_lists WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPriceList(ctx context.Context, id uuid.UUID) (PriceList, error) {
	row := q.db.QueryRow(ctx, getPriceList, id)
	var i PriceList
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.ServiceName,
		&i.ServiceCode,
		&i.ServiceCategory,
		&i.UnitPrice,
		&i.SchemeID,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listActivePrices = `-- name: ListActivePrices :many
SELECT id, hospital_id, service_name, service_code, service_category, unit_price, scheme_id, effective_from, effective_until, description, is_active, created_at, updated_at, deleted_at FROM price_lists
WHERE hospital_id = $1
  AND effective_from <= CURRENT_DATE
  AND (effective_until IS NULL OR effective_until >= CURRENT_DATE)
  AND deleted_at IS NULL
ORDER BY service_name
`

func (q *Queries) ListActivePrices(ctx context.Context, hospitalID uuid.UUID) ([]PriceList, error) {
	rows, err := q.db.Query(ctx, listActivePrices, hospitalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PriceList
	for rows.Next() {
		var i PriceList
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.ServiceName,
			&i.ServiceCode,
			&i.ServiceCategory,
			&i.UnitPrice,
			&i.SchemeID,
			&i.EffectiveFrom,
			&i.EffectiveUntil,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPricesByHospital = `-- name: ListPricesByHospital :many
SELECT id, hospital_id, service_name, service_code, service_category, unit_price, scheme_id, effective_from, effective_until, description, is_active, created_at, updated_at, deleted_at FROM price_lists
WHERE hospital_id = $1 AND deleted_at IS NULL
ORDER BY service_name
`

func (q *Queries) ListPricesByHospital(ctx context.Context, hospitalID uuid.UUID) ([]PriceList, error) {
	rows, err := q.db.Query(ctx, listPricesByHospital, hospitalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PriceList
	for rows.Next() {
		var i PriceList
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.ServiceName,
			&i.ServiceCode,
			&i.ServiceCategory,
			&i.UnitPrice,
			&i.SchemeID,
			&i.EffectiveFrom,
			&i.EffectiveUntil,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPricesByScheme = `-- name: ListPricesByScheme :many
SELECT id, hospital_id, service_name, service_code, service_category, unit_price, scheme_id, effective_from, effective_until, description, is_active, created_at, updated_at, deleted_at FROM price_lists
WHERE hospital_id = $1 AND scheme_id = $2 AND deleted_at IS NULL
ORDER BY service_name
`

type ListPricesBySchemeParams struct {
	HospitalID uuid.UUID   `json:"hospital_id"`
	SchemeID   pgtype.UUID `json:"scheme_id"`
}

func (q *Queries) ListPricesByScheme(ctx context.Context, arg ListPricesBySchemeParams) ([]PriceList, error) {
	rows, err := q.db.Query(ctx, listPricesByScheme, arg.HospitalID, arg.SchemeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PriceList
	for rows.Next() {
		var i PriceList
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.ServiceName,
			&i.ServiceCode,
			&i.ServiceCategory,
			&i.UnitPrice,
			&i.SchemeID,
			&i.EffectiveFrom,
			&i.EffectiveUntil,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePriceList = `-- name: UpdatePriceList :one
UPDATE price_lists
SET service_name = $2, unit_price = $3, effective_from = $4, effective_until = $5
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, hospital_id, service_name, service_code, service_category, unit_price, scheme_id, effective_from, effective_until, description, is_active, created_at, updated_at, deleted_at
`

type UpdatePriceListParams struct {
	ID             uuid.UUID      `json:"id"`
	ServiceName    string         `json:"service_name"`
	UnitPrice      pgtype.Numeric `json:"unit_price"`
	EffectiveFrom  pgtype.Date    `json:"effective_from"`
	EffectiveUntil pgtype.Date    `json:"effective_until"`
}

func (q *Queries) UpdatePriceList(ctx context.Context, arg UpdatePriceListParams) (PriceList, error) {
	row := q.db.QueryRow(ctx, updatePriceList,
		arg.ID,
		arg.ServiceName,
		arg.UnitPrice,
		arg.EffectiveFrom,
		arg.EffectiveUntil,
	)
	var i PriceList
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.ServiceName,
		&i.ServiceCode,
		&i.ServiceCategory,
		&i.UnitPrice,
		&i.SchemeID,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
