// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AssignUserRole(ctx context.Context, arg AssignUserRoleParams) (UserRole, error)
	CleanupExpiredSessions(ctx context.Context) error
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (AuthSession, error)
	CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error)
	CreateFileAttachment(ctx context.Context, arg CreateFileAttachmentParams) (FileAttachment, error)
	CreateHospital(ctx context.Context, arg CreateHospitalParams) (Hospital, error)
	CreateHospitalSetting(ctx context.Context, arg CreateHospitalSettingParams) (HospitalSetting, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateSyncConflict(ctx context.Context, arg CreateSyncConflictParams) (SyncConflict, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteHospitalSetting(ctx context.Context, arg DeleteHospitalSettingParams) error
	EnqueueSync(ctx context.Context, arg EnqueueSyncParams) (SyncQueue, error)
	GetAuditLog(ctx context.Context, id uuid.UUID) (AuditLog, error)
	GetAuthSession(ctx context.Context, tokenHash string) (AuthSession, error)
	GetDepartment(ctx context.Context, id uuid.UUID) (Department, error)
	GetFileAttachment(ctx context.Context, id uuid.UUID) (FileAttachment, error)
	GetHospital(ctx context.Context, id uuid.UUID) (Hospital, error)
	GetHospitalSetting(ctx context.Context, arg GetHospitalSettingParams) (HospitalSetting, error)
	GetNotification(ctx context.Context, id uuid.UUID) (Notification, error)
	GetPendingSyncItems(ctx context.Context, arg GetPendingSyncItemsParams) ([]SyncQueue, error)
	GetRole(ctx context.Context, id uuid.UUID) (Role, error)
	GetSyncConflict(ctx context.Context, id uuid.UUID) (SyncConflict, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error)
	GetUserRoles(ctx context.Context, userID uuid.UUID) ([]GetUserRolesRow, error)
	GetUsersInRole(ctx context.Context, roleID uuid.UUID) ([]GetUsersInRoleRow, error)
	ListActiveUsers(ctx context.Context, hospitalID uuid.UUID) ([]User, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListAuditLogsByTable(ctx context.Context, arg ListAuditLogsByTableParams) ([]AuditLog, error)
	ListAuditLogsByUser(ctx context.Context, arg ListAuditLogsByUserParams) ([]AuditLog, error)
	ListCriticalUnread(ctx context.Context, userID uuid.UUID) ([]Notification, error)
	ListDepartments(ctx context.Context, hospitalID uuid.UUID) ([]Department, error)
	ListFileAttachmentsByEntity(ctx context.Context, arg ListFileAttachmentsByEntityParams) ([]FileAttachment, error)
	ListFileAttachmentsByHospital(ctx context.Context, arg ListFileAttachmentsByHospitalParams) ([]FileAttachment, error)
	ListHospitalSettings(ctx context.Context, hospitalID uuid.UUID) ([]HospitalSetting, error)
	ListHospitals(ctx context.Context) ([]Hospital, error)
	ListPendingConflicts(ctx context.Context, hospitalID uuid.UUID) ([]SyncConflict, error)
	ListRoles(ctx context.Context, hospitalID uuid.UUID) ([]Role, error)
	ListUnreadNotifications(ctx context.Context, userID uuid.UUID) ([]Notification, error)
	ListUserSessions(ctx context.Context, userID uuid.UUID) ([]AuthSession, error)
	MarkNotificationActioned(ctx context.Context, id uuid.UUID) error
	MarkNotificationRead(ctx context.Context, id uuid.UUID) error
	MarkSyncFailed(ctx context.Context, arg MarkSyncFailedParams) error
	MarkSyncSynced(ctx context.Context, id uuid.UUID) error
	RequeueFailedSyncs(ctx context.Context) error
	ResolveConflict(ctx context.Context, arg ResolveConflictParams) error
	RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error
	RevokeSession(ctx context.Context, tokenHash string) error
	RevokeUserRole(ctx context.Context, arg RevokeUserRoleParams) error
	SoftDeleteDepartment(ctx context.Context, id uuid.UUID) error
	SoftDeleteFileAttachment(ctx context.Context, id uuid.UUID) error
	SoftDeleteHospital(ctx context.Context, id uuid.UUID) error
	SoftDeleteRole(ctx context.Context, id uuid.UUID) error
	SoftDeleteUser(ctx context.Context, id uuid.UUID) error
	UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (Department, error)
	UpdateHospital(ctx context.Context, arg UpdateHospitalParams) (Hospital, error)
	UpdateHospitalSetting(ctx context.Context, arg UpdateHospitalSettingParams) (HospitalSetting, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
