// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AbandonAccess(ctx context.Context, arg AbandonAccessParams) (VascularAccess, error)
	AbortSession(ctx context.Context, arg AbortSessionParams) (DialysisSession, error)
	AcknowledgeAlert(ctx context.Context, arg AcknowledgeAlertParams) (SessionVital, error)
	ApproveWaterTest(ctx context.Context, arg ApproveWaterTestParams) (WaterTreatmentLog, error)
	AssignCHWToPatient(ctx context.Context, arg AssignCHWToPatientParams) (ChwPatientAssignment, error)
	AssignUserRole(ctx context.Context, arg AssignUserRoleParams) (UserRole, error)
	CheckActiveConsent(ctx context.Context, arg CheckActiveConsentParams) (Consent, error)
	CheckDrugAllergy(ctx context.Context, arg CheckDrugAllergyParams) (Allergy, error)
	CleanupExpiredSessions(ctx context.Context) error
	CompleteAssignment(ctx context.Context, id uuid.UUID) (SessionStaffAssignment, error)
	CompleteSession(ctx context.Context, arg CompleteSessionParams) (DialysisSession, error)
	CreateAdequacyAssessment(ctx context.Context, arg CreateAdequacyAssessmentParams) (AdequacyAssessment, error)
	CreateAdmission(ctx context.Context, arg CreateAdmissionParams) (Admission, error)
	CreateAllergy(ctx context.Context, arg CreateAllergyParams) (Allergy, error)
	CreateAnticoagulationRecord(ctx context.Context, arg CreateAnticoagulationRecordParams) (AnticoagulationRecord, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (AuthSession, error)
	CreateCHW(ctx context.Context, arg CreateCHWParams) (CommunityHealthWorker, error)
	CreateComorbidity(ctx context.Context, arg CreateComorbidityParams) (Comorbidity, error)
	CreateConsent(ctx context.Context, arg CreateConsentParams) (Consent, error)
	CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error)
	CreateDiagnosis(ctx context.Context, arg CreateDiagnosisParams) (Diagnosis, error)
	CreateDialysateRecord(ctx context.Context, arg CreateDialysateRecordParams) (DialysateRecord, error)
	CreateDialysisMachine(ctx context.Context, arg CreateDialysisMachineParams) (DialysisMachine, error)
	CreateDialysisPrescription(ctx context.Context, arg CreateDialysisPrescriptionParams) (DialysisPrescription, error)
	CreateDialysisSession(ctx context.Context, arg CreateDialysisSessionParams) (DialysisSession, error)
	CreateDryWeightRecord(ctx context.Context, arg CreateDryWeightRecordParams) (DryWeightRecord, error)
	CreateFileAttachment(ctx context.Context, arg CreateFileAttachmentParams) (FileAttachment, error)
	CreateHospital(ctx context.Context, arg CreateHospitalParams) (Hospital, error)
	CreateHospitalSetting(ctx context.Context, arg CreateHospitalSettingParams) (HospitalSetting, error)
	CreateInfectionControlLog(ctx context.Context, arg CreateInfectionControlLogParams) (InfectionControlLog, error)
	CreateNextOfKin(ctx context.Context, arg CreateNextOfKinParams) (NextOfKin, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreatePatient(ctx context.Context, arg CreatePatientParams) (Patient, error)
	CreatePatientContact(ctx context.Context, arg CreatePatientContactParams) (PatientContact, error)
	CreatePatientFlag(ctx context.Context, arg CreatePatientFlagParams) (PatientFlag, error)
	CreatePatientIdentifier(ctx context.Context, arg CreatePatientIdentifierParams) (PatientIdentifier, error)
	CreatePowerOutageLog(ctx context.Context, arg CreatePowerOutageLogParams) (PowerOutageLog, error)
	CreateReferral(ctx context.Context, arg CreateReferralParams) (Referral, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateSessionComplication(ctx context.Context, arg CreateSessionComplicationParams) (SessionComplication, error)
	CreateSessionFluidBalance(ctx context.Context, arg CreateSessionFluidBalanceParams) (SessionFluidBalance, error)
	CreateSessionNursingNote(ctx context.Context, arg CreateSessionNursingNoteParams) (SessionNursingNote, error)
	CreateSessionSchedule(ctx context.Context, arg CreateSessionScheduleParams) (SessionSchedule, error)
	CreateSessionStaffAssignment(ctx context.Context, arg CreateSessionStaffAssignmentParams) (SessionStaffAssignment, error)
	CreateSessionVital(ctx context.Context, arg CreateSessionVitalParams) (SessionVital, error)
	CreateSyncConflict(ctx context.Context, arg CreateSyncConflictParams) (SyncConflict, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVascularAccess(ctx context.Context, arg CreateVascularAccessParams) (VascularAccess, error)
	CreateVascularAccessAssessment(ctx context.Context, arg CreateVascularAccessAssessmentParams) (VascularAccessAssessment, error)
	CreateWaterTreatmentLog(ctx context.Context, arg CreateWaterTreatmentLogParams) (WaterTreatmentLog, error)
	DeactivateSchedule(ctx context.Context, id uuid.UUID) (SessionSchedule, error)
	DeleteAdequacyAssessment(ctx context.Context, id uuid.UUID) error
	DeleteAnticoagulationRecord(ctx context.Context, id uuid.UUID) error
	DeleteDialysateRecord(ctx context.Context, id uuid.UUID) error
	DeleteDialysisMachine(ctx context.Context, id uuid.UUID) error
	DeleteDialysisPrescription(ctx context.Context, id uuid.UUID) error
	DeleteDialysisSession(ctx context.Context, id uuid.UUID) error
	DeleteDryWeightRecord(ctx context.Context, id uuid.UUID) error
	DeleteHospitalSetting(ctx context.Context, arg DeleteHospitalSettingParams) error
	DeleteInfectionControlLog(ctx context.Context, id uuid.UUID) error
	DeletePowerOutageLog(ctx context.Context, id uuid.UUID) error
	DeleteSessionComplication(ctx context.Context, id uuid.UUID) error
	DeleteSessionFluidBalance(ctx context.Context, id uuid.UUID) error
	DeleteSessionNursingNote(ctx context.Context, id uuid.UUID) error
	DeleteSessionSchedule(ctx context.Context, id uuid.UUID) error
	DeleteSessionStaffAssignment(ctx context.Context, id uuid.UUID) error
	DeleteSessionVital(ctx context.Context, id uuid.UUID) error
	DeleteVascularAccess(ctx context.Context, id uuid.UUID) error
	DeleteVascularAccessAssessment(ctx context.Context, id uuid.UUID) error
	DeleteWaterTreatmentLog(ctx context.Context, id uuid.UUID) error
	DischargePatient(ctx context.Context, arg DischargePatientParams) (Admission, error)
	EndPowerOutage(ctx context.Context, arg EndPowerOutageParams) (PowerOutageLog, error)
	EnqueueSync(ctx context.Context, arg EnqueueSyncParams) (SyncQueue, error)
	FindByIdentifier(ctx context.Context, arg FindByIdentifierParams) (PatientIdentifier, error)
	GetActiveAllergies(ctx context.Context, patientID uuid.UUID) ([]Allergy, error)
	GetActiveFlags(ctx context.Context, patientID uuid.UUID) ([]PatientFlag, error)
	GetAdequacyAssessment(ctx context.Context, id uuid.UUID) (AdequacyAssessment, error)
	GetAnticoagulationBySession(ctx context.Context, sessionID uuid.UUID) (AnticoagulationRecord, error)
	GetAnticoagulationRecord(ctx context.Context, id uuid.UUID) (AnticoagulationRecord, error)
	GetAuditLog(ctx context.Context, id uuid.UUID) (AuditLog, error)
	GetAuthSession(ctx context.Context, tokenHash string) (AuthSession, error)
	GetCHWByPatient(ctx context.Context, patientID uuid.UUID) (CommunityHealthWorker, error)
	GetConsentByType(ctx context.Context, arg GetConsentByTypeParams) (Consent, error)
	GetCurrentAdmission(ctx context.Context, patientID uuid.UUID) (Admission, error)
	GetCurrentDryWeight(ctx context.Context, patientID uuid.UUID) (DryWeightRecord, error)
	GetDepartment(ctx context.Context, id uuid.UUID) (Department, error)
	GetDialysateBySession(ctx context.Context, sessionID uuid.UUID) (DialysateRecord, error)
	GetDialysateRecord(ctx context.Context, id uuid.UUID) (DialysateRecord, error)
	GetDialysisMachine(ctx context.Context, id uuid.UUID) (DialysisMachine, error)
	GetDialysisPrescription(ctx context.Context, id uuid.UUID) (DialysisPrescription, error)
	GetDialysisSession(ctx context.Context, id uuid.UUID) (DialysisSession, error)
	GetDryWeightRecord(ctx context.Context, id uuid.UUID) (DryWeightRecord, error)
	GetFileAttachment(ctx context.Context, id uuid.UUID) (FileAttachment, error)
	GetFluidBalanceBySession(ctx context.Context, sessionID uuid.UUID) (SessionFluidBalance, error)
	GetHospital(ctx context.Context, id uuid.UUID) (Hospital, error)
	GetHospitalSetting(ctx context.Context, arg GetHospitalSettingParams) (HospitalSetting, error)
	GetInfectionControlLog(ctx context.Context, id uuid.UUID) (InfectionControlLog, error)
	GetInfectiousFlags(ctx context.Context, patientID uuid.UUID) ([]PatientFlag, error)
	GetLatestDisinfectionForMachine(ctx context.Context, machineID uuid.UUID) (InfectionControlLog, error)
	GetLegalGuardian(ctx context.Context, patientID uuid.UUID) (NextOfKin, error)
	GetNotification(ctx context.Context, id uuid.UUID) (Notification, error)
	GetPatient(ctx context.Context, id uuid.UUID) (Patient, error)
	GetPatientByMRN(ctx context.Context, arg GetPatientByMRNParams) (Patient, error)
	GetPatientByNationalID(ctx context.Context, nationalID pgtype.Text) (Patient, error)
	GetPatientsByCHW(ctx context.Context, chwID uuid.UUID) ([]Patient, error)
	GetPendingSyncItems(ctx context.Context, arg GetPendingSyncItemsParams) ([]SyncQueue, error)
	GetPowerOutageLog(ctx context.Context, id uuid.UUID) (PowerOutageLog, error)
	GetPrescriptionBySession(ctx context.Context, sessionID uuid.UUID) (DialysisPrescription, error)
	GetPrimaryAccessForPatient(ctx context.Context, patientID uuid.UUID) (VascularAccess, error)
	GetPrimaryContact(ctx context.Context, patientID uuid.UUID) (NextOfKin, error)
	GetPrimaryDiagnosis(ctx context.Context, patientID uuid.UUID) (Diagnosis, error)
	GetPrimaryPhone(ctx context.Context, patientID uuid.UUID) (PatientContact, error)
	GetRole(ctx context.Context, id uuid.UUID) (Role, error)
	GetSessionComplication(ctx context.Context, id uuid.UUID) (SessionComplication, error)
	GetSessionFluidBalance(ctx context.Context, id uuid.UUID) (SessionFluidBalance, error)
	GetSessionNursingNote(ctx context.Context, id uuid.UUID) (SessionNursingNote, error)
	GetSessionSchedule(ctx context.Context, id uuid.UUID) (SessionSchedule, error)
	GetSessionStaffAssignment(ctx context.Context, id uuid.UUID) (SessionStaffAssignment, error)
	GetSessionVital(ctx context.Context, id uuid.UUID) (SessionVital, error)
	GetSyncConflict(ctx context.Context, id uuid.UUID) (SyncConflict, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error)
	GetUserRoles(ctx context.Context, userID uuid.UUID) ([]GetUserRolesRow, error)
	GetUsersInRole(ctx context.Context, roleID uuid.UUID) ([]GetUsersInRoleRow, error)
	GetVascularAccess(ctx context.Context, id uuid.UUID) (VascularAccess, error)
	GetVascularAccessAssessment(ctx context.Context, id uuid.UUID) (VascularAccessAssessment, error)
	GetWaterTreatmentLog(ctx context.Context, id uuid.UUID) (WaterTreatmentLog, error)
	ListActiveAdmissions(ctx context.Context, hospitalID uuid.UUID) ([]Admission, error)
	ListActiveAssignmentsByStaff(ctx context.Context, staffID uuid.UUID) ([]SessionStaffAssignment, error)
	ListActivePatients(ctx context.Context, arg ListActivePatientsParams) ([]Patient, error)
	ListActiveSchedulesByMachine(ctx context.Context, machineID pgtype.UUID) ([]SessionSchedule, error)
	ListActiveSchedulesByPatient(ctx context.Context, patientID uuid.UUID) ([]SessionSchedule, error)
	ListActiveSessions(ctx context.Context, hospitalID uuid.UUID) ([]DialysisSession, error)
	ListActiveSessionsByMachine(ctx context.Context, machineID uuid.UUID) ([]DialysisSession, error)
	ListActiveUsers(ctx context.Context, hospitalID uuid.UUID) ([]User, error)
	ListAdequacyAssessmentsByPatient(ctx context.Context, patientID uuid.UUID) ([]AdequacyAssessment, error)
	ListAnticoagulationRecordsByPatient(ctx context.Context, patientID uuid.UUID) ([]AnticoagulationRecord, error)
	ListAssessmentsByAccess(ctx context.Context, accessID uuid.UUID) ([]VascularAccessAssessment, error)
	ListAssessmentsBySession(ctx context.Context, sessionID pgtype.UUID) ([]VascularAccessAssessment, error)
	ListAssessmentsRequiringIntervention(ctx context.Context, hospitalID uuid.UUID) ([]VascularAccessAssessment, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListAuditLogsByTable(ctx context.Context, arg ListAuditLogsByTableParams) ([]AuditLog, error)
	ListAuditLogsByUser(ctx context.Context, arg ListAuditLogsByUserParams) ([]AuditLog, error)
	ListAvailableMachines(ctx context.Context, hospitalID uuid.UUID) ([]DialysisMachine, error)
	ListCHWsByRegion(ctx context.Context, arg ListCHWsByRegionParams) ([]CommunityHealthWorker, error)
	ListComorbiditiesByPatient(ctx context.Context, patientID uuid.UUID) ([]Comorbidity, error)
	ListComplicationsByPatient(ctx context.Context, patientID uuid.UUID) ([]SessionComplication, error)
	ListComplicationsBySession(ctx context.Context, sessionID uuid.UUID) ([]SessionComplication, error)
	ListConsentsByPatient(ctx context.Context, patientID uuid.UUID) ([]Consent, error)
	ListContactsByPatient(ctx context.Context, patientID uuid.UUID) ([]PatientContact, error)
	ListCriticalUnread(ctx context.Context, userID uuid.UUID) ([]Notification, error)
	ListDepartments(ctx context.Context, hospitalID uuid.UUID) ([]Department, error)
	ListDiagnosesByPatient(ctx context.Context, patientID uuid.UUID) ([]Diagnosis, error)
	ListDialysateRecordsByBatch(ctx context.Context, arg ListDialysateRecordsByBatchParams) ([]DialysateRecord, error)
	ListDialysisMachinesByHospital(ctx context.Context, hospitalID uuid.UUID) ([]DialysisMachine, error)
	ListDryWeightRecordsByPatient(ctx context.Context, patientID uuid.UUID) ([]DryWeightRecord, error)
	ListFailedWaterTests(ctx context.Context, hospitalID uuid.UUID) ([]WaterTreatmentLog, error)
	ListFileAttachmentsByEntity(ctx context.Context, arg ListFileAttachmentsByEntityParams) ([]FileAttachment, error)
	ListFileAttachmentsByHospital(ctx context.Context, arg ListFileAttachmentsByHospitalParams) ([]FileAttachment, error)
	ListFlaggedNotes(ctx context.Context, hospitalID uuid.UUID) ([]SessionNursingNote, error)
	ListFluidBalancesByPatient(ctx context.Context, patientID uuid.UUID) ([]SessionFluidBalance, error)
	ListHBVDedicatedMachines(ctx context.Context, hospitalID uuid.UUID) ([]DialysisMachine, error)
	ListHBVDisinfections(ctx context.Context, hospitalID uuid.UUID) ([]InfectionControlLog, error)
	ListHospitalSettings(ctx context.Context, hospitalID uuid.UUID) ([]HospitalSetting, error)
	ListHospitals(ctx context.Context) ([]Hospital, error)
	ListIdentifiersByPatient(ctx context.Context, patientID uuid.UUID) ([]PatientIdentifier, error)
	ListInadequateAssessments(ctx context.Context, hospitalID uuid.UUID) ([]AdequacyAssessment, error)
	ListInfectionLogsByMachine(ctx context.Context, machineID uuid.UUID) ([]InfectionControlLog, error)
	ListNextOfKinByPatient(ctx context.Context, patientID uuid.UUID) ([]NextOfKin, error)
	ListNursingNotesBySession(ctx context.Context, sessionID uuid.UUID) ([]SessionNursingNote, error)
	ListOngoingOutages(ctx context.Context, hospitalID uuid.UUID) ([]PowerOutageLog, error)
	ListPendingConflicts(ctx context.Context, hospitalID uuid.UUID) ([]SyncConflict, error)
	ListPendingWaterTests(ctx context.Context, hospitalID uuid.UUID) ([]WaterTreatmentLog, error)
	ListPowerOutagesByHospital(ctx context.Context, hospitalID uuid.UUID) ([]PowerOutageLog, error)
	ListPrescriptionsByPatient(ctx context.Context, patientID uuid.UUID) ([]DialysisPrescription, error)
	ListRecordsWithComplications(ctx context.Context, hospitalID uuid.UUID) ([]AnticoagulationRecord, error)
	ListReferralsByPatient(ctx context.Context, patientID uuid.UUID) ([]Referral, error)
	ListRoles(ctx context.Context, hospitalID uuid.UUID) ([]Role, error)
	ListSchedulesByHospital(ctx context.Context, hospitalID uuid.UUID) ([]SessionSchedule, error)
	ListSessionsByDate(ctx context.Context, arg ListSessionsByDateParams) ([]DialysisSession, error)
	ListSessionsByPatient(ctx context.Context, arg ListSessionsByPatientParams) ([]DialysisSession, error)
	ListSevereComplications(ctx context.Context, hospitalID uuid.UUID) ([]SessionComplication, error)
	ListSevereOutages(ctx context.Context, hospitalID uuid.UUID) ([]PowerOutageLog, error)
	ListStaffAssignmentsBySession(ctx context.Context, sessionID uuid.UUID) ([]SessionStaffAssignment, error)
	ListTransfersByPatient(ctx context.Context, patientID uuid.UUID) ([]Transfer, error)
	ListUnreadNotifications(ctx context.Context, userID uuid.UUID) ([]Notification, error)
	ListUnverifiedMachines(ctx context.Context, hospitalID uuid.UUID) ([]InfectionControlLog, error)
	ListUserSessions(ctx context.Context, userID uuid.UUID) ([]AuthSession, error)
	ListVascularAccessByPatient(ctx context.Context, patientID uuid.UUID) ([]VascularAccess, error)
	ListVitalsBySession(ctx context.Context, sessionID uuid.UUID) ([]SessionVital, error)
	ListVitalsWithAlerts(ctx context.Context, sessionID uuid.UUID) ([]SessionVital, error)
	ListWaterTestsByDate(ctx context.Context, arg ListWaterTestsByDateParams) ([]WaterTreatmentLog, error)
	MarkNoteReviewedByDoctor(ctx context.Context, arg MarkNoteReviewedByDoctorParams) (SessionNursingNote, error)
	MarkNotificationActioned(ctx context.Context, id uuid.UUID) error
	MarkNotificationRead(ctx context.Context, id uuid.UUID) error
	MarkPatientDeceased(ctx context.Context, id uuid.UUID) error
	MarkSyncFailed(ctx context.Context, arg MarkSyncFailedParams) error
	MarkSyncSynced(ctx context.Context, id uuid.UUID) error
	RequeueFailedSyncs(ctx context.Context) error
	ResolveConflict(ctx context.Context, arg ResolveConflictParams) error
	ResolveFlag(ctx context.Context, arg ResolveFlagParams) error
	RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error
	RevokeSession(ctx context.Context, tokenHash string) error
	RevokeUserRole(ctx context.Context, arg RevokeUserRoleParams) error
	SearchPatientsByName(ctx context.Context, arg SearchPatientsByNameParams) ([]Patient, error)
	SoftDeleteDepartment(ctx context.Context, id uuid.UUID) error
	SoftDeleteFileAttachment(ctx context.Context, id uuid.UUID) error
	SoftDeleteHospital(ctx context.Context, id uuid.UUID) error
	SoftDeletePatient(ctx context.Context, id uuid.UUID) error
	SoftDeleteRole(ctx context.Context, id uuid.UUID) error
	SoftDeleteUser(ctx context.Context, id uuid.UUID) error
	StartAssignment(ctx context.Context, id uuid.UUID) (SessionStaffAssignment, error)
	StartSession(ctx context.Context, arg StartSessionParams) (DialysisSession, error)
	UpdateAdequacyAssessment(ctx context.Context, arg UpdateAdequacyAssessmentParams) (AdequacyAssessment, error)
	UpdateAnticoagulationRecord(ctx context.Context, arg UpdateAnticoagulationRecordParams) (AnticoagulationRecord, error)
	UpdateComorbidityStatus(ctx context.Context, arg UpdateComorbidityStatusParams) (Comorbidity, error)
	UpdateContactPrimary(ctx context.Context, arg UpdateContactPrimaryParams) error
	UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (Department, error)
	UpdateDialysisMachine(ctx context.Context, arg UpdateDialysisMachineParams) (DialysisMachine, error)
	UpdateDialysisPrescription(ctx context.Context, arg UpdateDialysisPrescriptionParams) (DialysisPrescription, error)
	UpdateDryWeightRecord(ctx context.Context, arg UpdateDryWeightRecordParams) (DryWeightRecord, error)
	UpdateHospital(ctx context.Context, arg UpdateHospitalParams) (Hospital, error)
	UpdateHospitalSetting(ctx context.Context, arg UpdateHospitalSettingParams) (HospitalSetting, error)
	UpdateMachineStatus(ctx context.Context, arg UpdateMachineStatusParams) (DialysisMachine, error)
	UpdatePatient(ctx context.Context, arg UpdatePatientParams) (Patient, error)
	UpdateReferralStatus(ctx context.Context, arg UpdateReferralStatusParams) (Referral, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error)
	UpdateSessionComplication(ctx context.Context, arg UpdateSessionComplicationParams) (SessionComplication, error)
	UpdateSessionFluidBalance(ctx context.Context, arg UpdateSessionFluidBalanceParams) (SessionFluidBalance, error)
	UpdateSessionSchedule(ctx context.Context, arg UpdateSessionScheduleParams) (SessionSchedule, error)
	UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) (DialysisSession, error)
	UpdateTransferStatus(ctx context.Context, arg UpdateTransferStatusParams) (Transfer, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateVascularAccess(ctx context.Context, arg UpdateVascularAccessParams) (VascularAccess, error)
	UpdateWaterTestResults(ctx context.Context, arg UpdateWaterTestResultsParams) (WaterTreatmentLog, error)
	VerifyDialysateComposition(ctx context.Context, arg VerifyDialysateCompositionParams) (DialysateRecord, error)
	VerifyMachineReady(ctx context.Context, arg VerifyMachineReadyParams) (InfectionControlLog, error)
	WithdrawConsent(ctx context.Context, arg WithdrawConsentParams) error
}

var _ Querier = (*Queries)(nil)
