// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: referrals.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createReferral = `-- name: CreateReferral :one
INSERT INTO referrals (
    hospital_id, patient_id, direction, from_facility, to_facility, from_doctor,
    to_doctor_id, reason, urgency, referral_letter_url, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, hospital_id, patient_id, direction, from_facility, to_facility, from_doctor, to_doctor_id, reason, urgency, status, referral_date, response_date, response_notes, referral_letter_url, created_by, created_at, updated_at, deleted_at
`

type CreateReferralParams struct {
	HospitalID        uuid.UUID         `json:"hospital_id"`
	PatientID         uuid.UUID         `json:"patient_id"`
	Direction         ReferralDirection `json:"direction"`
	FromFacility      pgtype.Text       `json:"from_facility"`
	ToFacility        pgtype.Text       `json:"to_facility"`
	FromDoctor        pgtype.Text       `json:"from_doctor"`
	ToDoctorID        pgtype.UUID       `json:"to_doctor_id"`
	Reason            string            `json:"reason"`
	Urgency           ReferralUrgency   `json:"urgency"`
	ReferralLetterUrl pgtype.Text       `json:"referral_letter_url"`
	CreatedBy         uuid.UUID         `json:"created_by"`
}

func (q *Queries) CreateReferral(ctx context.Context, arg CreateReferralParams) (Referral, error) {
	row := q.db.QueryRow(ctx, createReferral,
		arg.HospitalID,
		arg.PatientID,
		arg.Direction,
		arg.FromFacility,
		arg.ToFacility,
		arg.FromDoctor,
		arg.ToDoctorID,
		arg.Reason,
		arg.Urgency,
		arg.ReferralLetterUrl,
		arg.CreatedBy,
	)
	var i Referral
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.PatientID,
		&i.Direction,
		&i.FromFacility,
		&i.ToFacility,
		&i.FromDoctor,
		&i.ToDoctorID,
		&i.Reason,
		&i.Urgency,
		&i.Status,
		&i.ReferralDate,
		&i.ResponseDate,
		&i.ResponseNotes,
		&i.ReferralLetterUrl,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listReferralsByPatient = `-- name: ListReferralsByPatient :many
SELECT id, hospital_id, patient_id, direction, from_facility, to_facility, from_doctor, to_doctor_id, reason, urgency, status, referral_date, response_date, response_notes, referral_letter_url, created_by, created_at, updated_at, deleted_at FROM referrals
WHERE patient_id = $1 AND deleted_at IS NULL
ORDER BY referral_date DESC
`

func (q *Queries) ListReferralsByPatient(ctx context.Context, patientID uuid.UUID) ([]Referral, error) {
	rows, err := q.db.Query(ctx, listReferralsByPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Referral
	for rows.Next() {
		var i Referral
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.PatientID,
			&i.Direction,
			&i.FromFacility,
			&i.ToFacility,
			&i.FromDoctor,
			&i.ToDoctorID,
			&i.Reason,
			&i.Urgency,
			&i.Status,
			&i.ReferralDate,
			&i.ResponseDate,
			&i.ResponseNotes,
			&i.ReferralLetterUrl,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReferralStatus = `-- name: UpdateReferralStatus :one
UPDATE referrals
SET status = $2, response_date = $3, response_notes = $4
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, hospital_id, patient_id, direction, from_facility, to_facility, from_doctor, to_doctor_id, reason, urgency, status, referral_date, response_date, response_notes, referral_letter_url, created_by, created_at, updated_at, deleted_at
`

type UpdateReferralStatusParams struct {
	ID            uuid.UUID      `json:"id"`
	Status        ReferralStatus `json:"status"`
	ResponseDate  pgtype.Date    `json:"response_date"`
	ResponseNotes pgtype.Text    `json:"response_notes"`
}

func (q *Queries) UpdateReferralStatus(ctx context.Context, arg UpdateReferralStatusParams) (Referral, error) {
	row := q.db.QueryRow(ctx, updateReferralStatus,
		arg.ID,
		arg.Status,
		arg.ResponseDate,
		arg.ResponseNotes,
	)
	var i Referral
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.PatientID,
		&i.Direction,
		&i.FromFacility,
		&i.ToFacility,
		&i.FromDoctor,
		&i.ToDoctorID,
		&i.Reason,
		&i.Urgency,
		&i.Status,
		&i.ReferralDate,
		&i.ResponseDate,
		&i.ResponseNotes,
		&i.ReferralLetterUrl,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
