// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roles.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRole = `-- name: CreateRole :one
INSERT INTO roles (
  hospital_id, name, description, permissions, is_system
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id, hospital_id, name, description, permissions, is_system, created_at, updated_at, deleted_at
`

type CreateRoleParams struct {
	HospitalID  uuid.UUID   `json:"hospital_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Permissions []byte      `json:"permissions"`
	IsSystem    bool        `json:"is_system"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.HospitalID,
		arg.Name,
		arg.Description,
		arg.Permissions,
		arg.IsSystem,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.Name,
		&i.Description,
		&i.Permissions,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getRole = `-- name: GetRole :one
SELECT id, hospital_id, name, description, permissions, is_system, created_at, updated_at, deleted_at FROM roles
WHERE id = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetRole(ctx context.Context, id uuid.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, getRole, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.Name,
		&i.Description,
		&i.Permissions,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listRoles = `-- name: ListRoles :many
SELECT id, hospital_id, name, description, permissions, is_system, created_at, updated_at, deleted_at FROM roles
WHERE hospital_id = $1 AND deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListRoles(ctx context.Context, hospitalID uuid.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles, hospitalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.Name,
			&i.Description,
			&i.Permissions,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteRole = `-- name: SoftDeleteRole :exec
UPDATE roles
SET deleted_at = now()
WHERE id = $1
`

func (q *Queries) SoftDeleteRole(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteRole, id)
	return err
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles
SET name = $2, description = $3, permissions = $4
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, hospital_id, name, description, permissions, is_system, created_at, updated_at, deleted_at
`

type UpdateRoleParams struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Permissions []byte      `json:"permissions"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, updateRole,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Permissions,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.Name,
		&i.Description,
		&i.Permissions,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
