// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_staff_assignments.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeAssignment = `-- name: CompleteAssignment :one
UPDATE session_staff_assignments
SET completed_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, hospital_id, session_id, staff_id, role, assigned_at, assigned_by, started_at, completed_at, notes, created_at, updated_at, deleted_at
`

func (q *Queries) CompleteAssignment(ctx context.Context, id uuid.UUID) (SessionStaffAssignment, error) {
	row := q.db.QueryRow(ctx, completeAssignment, id)
	var i SessionStaffAssignment
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.SessionID,
		&i.StaffID,
		&i.Role,
		&i.AssignedAt,
		&i.AssignedBy,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createSessionStaffAssignment = `-- name: CreateSessionStaffAssignment :one
INSERT INTO session_staff_assignments (
    hospital_id, session_id, staff_id, role, assigned_by, notes
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, hospital_id, session_id, staff_id, role, assigned_at, assigned_by, started_at, completed_at, notes, created_at, updated_at, deleted_at
`

type CreateSessionStaffAssignmentParams struct {
	HospitalID uuid.UUID   `json:"hospital_id"`
	SessionID  uuid.UUID   `json:"session_id"`
	StaffID    uuid.UUID   `json:"staff_id"`
	Role       string      `json:"role"`
	AssignedBy uuid.UUID   `json:"assigned_by"`
	Notes      pgtype.Text `json:"notes"`
}

func (q *Queries) CreateSessionStaffAssignment(ctx context.Context, arg CreateSessionStaffAssignmentParams) (SessionStaffAssignment, error) {
	row := q.db.QueryRow(ctx, createSessionStaffAssignment,
		arg.HospitalID,
		arg.SessionID,
		arg.StaffID,
		arg.Role,
		arg.AssignedBy,
		arg.Notes,
	)
	var i SessionStaffAssignment
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.SessionID,
		&i.StaffID,
		&i.Role,
		&i.AssignedAt,
		&i.AssignedBy,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteSessionStaffAssignment = `-- name: DeleteSessionStaffAssignment :exec
UPDATE session_staff_assignments SET deleted_at = now() WHERE id = $1
`

func (q *Queries) DeleteSessionStaffAssignment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionStaffAssignment, id)
	return err
}

const getSessionStaffAssignment = `-- name: GetSessionStaffAssignment :one
SELECT id, hospital_id, session_id, staff_id, role, assigned_at, assigned_by, started_at, completed_at, notes, created_at, updated_at, deleted_at FROM session_staff_assignments WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSessionStaffAssignment(ctx context.Context, id uuid.UUID) (SessionStaffAssignment, error) {
	row := q.db.QueryRow(ctx, getSessionStaffAssignment, id)
	var i SessionStaffAssignment
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.SessionID,
		&i.StaffID,
		&i.Role,
		&i.AssignedAt,
		&i.AssignedBy,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listActiveAssignmentsByStaff = `-- name: ListActiveAssignmentsByStaff :many
SELECT id, hospital_id, session_id, staff_id, role, assigned_at, assigned_by, started_at, completed_at, notes, created_at, updated_at, deleted_at FROM session_staff_assignments
WHERE staff_id = $1
  AND started_at IS NOT NULL
  AND completed_at IS NULL
  AND deleted_at IS NULL
ORDER BY started_at
`

func (q *Queries) ListActiveAssignmentsByStaff(ctx context.Context, staffID uuid.UUID) ([]SessionStaffAssignment, error) {
	rows, err := q.db.Query(ctx, listActiveAssignmentsByStaff, staffID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionStaffAssignment
	for rows.Next() {
		var i SessionStaffAssignment
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.SessionID,
			&i.StaffID,
			&i.Role,
			&i.AssignedAt,
			&i.AssignedBy,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaffAssignmentsBySession = `-- name: ListStaffAssignmentsBySession :many
SELECT id, hospital_id, session_id, staff_id, role, assigned_at, assigned_by, started_at, completed_at, notes, created_at, updated_at, deleted_at FROM session_staff_assignments
WHERE session_id = $1 AND deleted_at IS NULL
ORDER BY assigned_at
`

func (q *Queries) ListStaffAssignmentsBySession(ctx context.Context, sessionID uuid.UUID) ([]SessionStaffAssignment, error) {
	rows, err := q.db.Query(ctx, listStaffAssignmentsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionStaffAssignment
	for rows.Next() {
		var i SessionStaffAssignment
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.SessionID,
			&i.StaffID,
			&i.Role,
			&i.AssignedAt,
			&i.AssignedBy,
			&i.StartedAt,
			&i.CompletedAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startAssignment = `-- name: StartAssignment :one
UPDATE session_staff_assignments
SET started_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, hospital_id, session_id, staff_id, role, assigned_at, assigned_by, started_at, completed_at, notes, created_at, updated_at, deleted_at
`

func (q *Queries) StartAssignment(ctx context.Context, id uuid.UUID) (SessionStaffAssignment, error) {
	row := q.db.QueryRow(ctx, startAssignment, id)
	var i SessionStaffAssignment
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.SessionID,
		&i.StaffID,
		&i.Role,
		&i.AssignedAt,
		&i.AssignedBy,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
