// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_schedules.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSessionSchedule = `-- name: CreateSessionSchedule :one
INSERT INTO session_schedules (
    hospital_id, patient_id, machine_id, shift, days_of_week, frequency_weeks,
    modality, prescribed_duration_mins, effective_from, effective_until,
    is_active, created_by, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, hospital_id, patient_id, machine_id, shift, days_of_week, frequency_weeks, modality, prescribed_duration_mins, effective_from, effective_until, is_active, created_by, notes, created_at, updated_at, deleted_at
`

type CreateSessionScheduleParams struct {
	HospitalID             uuid.UUID        `json:"hospital_id"`
	PatientID              uuid.UUID        `json:"patient_id"`
	MachineID              pgtype.UUID      `json:"machine_id"`
	Shift                  ShiftType        `json:"shift"`
	DaysOfWeek             []int32          `json:"days_of_week"`
	FrequencyWeeks         int32            `json:"frequency_weeks"`
	Modality               DialysisModality `json:"modality"`
	PrescribedDurationMins int32            `json:"prescribed_duration_mins"`
	EffectiveFrom          pgtype.Date      `json:"effective_from"`
	EffectiveUntil         pgtype.Date      `json:"effective_until"`
	IsActive               bool             `json:"is_active"`
	CreatedBy              uuid.UUID        `json:"created_by"`
	Notes                  pgtype.Text      `json:"notes"`
}

func (q *Queries) CreateSessionSchedule(ctx context.Context, arg CreateSessionScheduleParams) (SessionSchedule, error) {
	row := q.db.QueryRow(ctx, createSessionSchedule,
		arg.HospitalID,
		arg.PatientID,
		arg.MachineID,
		arg.Shift,
		arg.DaysOfWeek,
		arg.FrequencyWeeks,
		arg.Modality,
		arg.PrescribedDurationMins,
		arg.EffectiveFrom,
		arg.EffectiveUntil,
		arg.IsActive,
		arg.CreatedBy,
		arg.Notes,
	)
	var i SessionSchedule
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.PatientID,
		&i.MachineID,
		&i.Shift,
		&i.DaysOfWeek,
		&i.FrequencyWeeks,
		&i.Modality,
		&i.PrescribedDurationMins,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.IsActive,
		&i.CreatedBy,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deactivateSchedule = `-- name: DeactivateSchedule :one
UPDATE session_schedules
SET is_active = FALSE, effective_until = CURRENT_DATE
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, hospital_id, patient_id, machine_id, shift, days_of_week, frequency_weeks, modality, prescribed_duration_mins, effective_from, effective_until, is_active, created_by, notes, created_at, updated_at, deleted_at
`

func (q *Queries) DeactivateSchedule(ctx context.Context, id uuid.UUID) (SessionSchedule, error) {
	row := q.db.QueryRow(ctx, deactivateSchedule, id)
	var i SessionSchedule
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.PatientID,
		&i.MachineID,
		&i.Shift,
		&i.DaysOfWeek,
		&i.FrequencyWeeks,
		&i.Modality,
		&i.PrescribedDurationMins,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.IsActive,
		&i.CreatedBy,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteSessionSchedule = `-- name: DeleteSessionSchedule :exec
UPDATE session_schedules SET deleted_at = now() WHERE id = $1
`

func (q *Queries) DeleteSessionSchedule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionSchedule, id)
	return err
}

const getSessionSchedule = `-- name: GetSessionSchedule :one
SELECT id, hospital_id, patient_id, machine_id, shift, days_of_week, frequency_weeks, modality, prescribed_duration_mins, effective_from, effective_until, is_active, created_by, notes, created_at, updated_at, deleted_at FROM session_schedules WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSessionSchedule(ctx context.Context, id uuid.UUID) (SessionSchedule, error) {
	row := q.db.QueryRow(ctx, getSessionSchedule, id)
	var i SessionSchedule
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.PatientID,
		&i.MachineID,
		&i.Shift,
		&i.DaysOfWeek,
		&i.FrequencyWeeks,
		&i.Modality,
		&i.PrescribedDurationMins,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.IsActive,
		&i.CreatedBy,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listActiveSchedulesByMachine = `-- name: ListActiveSchedulesByMachine :many
SELECT id, hospital_id, patient_id, machine_id, shift, days_of_week, frequency_weeks, modality, prescribed_duration_mins, effective_from, effective_until, is_active, created_by, notes, created_at, updated_at, deleted_at FROM session_schedules
WHERE machine_id = $1 AND is_active = TRUE AND deleted_at IS NULL
ORDER BY effective_from DESC
`

func (q *Queries) ListActiveSchedulesByMachine(ctx context.Context, machineID pgtype.UUID) ([]SessionSchedule, error) {
	rows, err := q.db.Query(ctx, listActiveSchedulesByMachine, machineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionSchedule
	for rows.Next() {
		var i SessionSchedule
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.PatientID,
			&i.MachineID,
			&i.Shift,
			&i.DaysOfWeek,
			&i.FrequencyWeeks,
			&i.Modality,
			&i.PrescribedDurationMins,
			&i.EffectiveFrom,
			&i.EffectiveUntil,
			&i.IsActive,
			&i.CreatedBy,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveSchedulesByPatient = `-- name: ListActiveSchedulesByPatient :many
SELECT id, hospital_id, patient_id, machine_id, shift, days_of_week, frequency_weeks, modality, prescribed_duration_mins, effective_from, effective_until, is_active, created_by, notes, created_at, updated_at, deleted_at FROM session_schedules
WHERE patient_id = $1 AND is_active = TRUE AND deleted_at IS NULL
ORDER BY effective_from DESC
`

func (q *Queries) ListActiveSchedulesByPatient(ctx context.Context, patientID uuid.UUID) ([]SessionSchedule, error) {
	rows, err := q.db.Query(ctx, listActiveSchedulesByPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionSchedule
	for rows.Next() {
		var i SessionSchedule
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.PatientID,
			&i.MachineID,
			&i.Shift,
			&i.DaysOfWeek,
			&i.FrequencyWeeks,
			&i.Modality,
			&i.PrescribedDurationMins,
			&i.EffectiveFrom,
			&i.EffectiveUntil,
			&i.IsActive,
			&i.CreatedBy,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulesByHospital = `-- name: ListSchedulesByHospital :many
SELECT id, hospital_id, patient_id, machine_id, shift, days_of_week, frequency_weeks, modality, prescribed_duration_mins, effective_from, effective_until, is_active, created_by, notes, created_at, updated_at, deleted_at FROM session_schedules
WHERE hospital_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListSchedulesByHospital(ctx context.Context, hospitalID uuid.UUID) ([]SessionSchedule, error) {
	rows, err := q.db.Query(ctx, listSchedulesByHospital, hospitalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionSchedule
	for rows.Next() {
		var i SessionSchedule
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.PatientID,
			&i.MachineID,
			&i.Shift,
			&i.DaysOfWeek,
			&i.FrequencyWeeks,
			&i.Modality,
			&i.PrescribedDurationMins,
			&i.EffectiveFrom,
			&i.EffectiveUntil,
			&i.IsActive,
			&i.CreatedBy,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionSchedule = `-- name: UpdateSessionSchedule :one
UPDATE session_schedules
SET machine_id = $2, shift = $3, days_of_week = $4, frequency_weeks = $5,
    modality = $6, prescribed_duration_mins = $7, effective_from = $8,
    effective_until = $9, is_active = $10, notes = $11
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, hospital_id, patient_id, machine_id, shift, days_of_week, frequency_weeks, modality, prescribed_duration_mins, effective_from, effective_until, is_active, created_by, notes, created_at, updated_at, deleted_at
`

type UpdateSessionScheduleParams struct {
	ID                     uuid.UUID        `json:"id"`
	MachineID              pgtype.UUID      `json:"machine_id"`
	Shift                  ShiftType        `json:"shift"`
	DaysOfWeek             []int32          `json:"days_of_week"`
	FrequencyWeeks         int32            `json:"frequency_weeks"`
	Modality               DialysisModality `json:"modality"`
	PrescribedDurationMins int32            `json:"prescribed_duration_mins"`
	EffectiveFrom          pgtype.Date      `json:"effective_from"`
	EffectiveUntil         pgtype.Date      `json:"effective_until"`
	IsActive               bool             `json:"is_active"`
	Notes                  pgtype.Text      `json:"notes"`
}

func (q *Queries) UpdateSessionSchedule(ctx context.Context, arg UpdateSessionScheduleParams) (SessionSchedule, error) {
	row := q.db.QueryRow(ctx, updateSessionSchedule,
		arg.ID,
		arg.MachineID,
		arg.Shift,
		arg.DaysOfWeek,
		arg.FrequencyWeeks,
		arg.Modality,
		arg.PrescribedDurationMins,
		arg.EffectiveFrom,
		arg.EffectiveUntil,
		arg.IsActive,
		arg.Notes,
	)
	var i SessionSchedule
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.PatientID,
		&i.MachineID,
		&i.Shift,
		&i.DaysOfWeek,
		&i.FrequencyWeeks,
		&i.Modality,
		&i.PrescribedDurationMins,
		&i.EffectiveFrom,
		&i.EffectiveUntil,
		&i.IsActive,
		&i.CreatedBy,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
