// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_nursing_notes.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSessionNursingNote = `-- name: CreateSessionNursingNote :one
INSERT INTO session_nursing_notes (
    hospital_id, session_id, patient_id, nurse_id, note_type,
    recorded_at, content, is_flagged_for_doctor
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, hospital_id, session_id, patient_id, nurse_id, note_type, recorded_at, content, is_flagged_for_doctor, doctor_reviewed_by, doctor_reviewed_at, created_at, updated_at, deleted_at
`

type CreateSessionNursingNoteParams struct {
	HospitalID         uuid.UUID          `json:"hospital_id"`
	SessionID          uuid.UUID          `json:"session_id"`
	PatientID          uuid.UUID          `json:"patient_id"`
	NurseID            uuid.UUID          `json:"nurse_id"`
	NoteType           string             `json:"note_type"`
	RecordedAt         pgtype.Timestamptz `json:"recorded_at"`
	Content            string             `json:"content"`
	IsFlaggedForDoctor bool               `json:"is_flagged_for_doctor"`
}

func (q *Queries) CreateSessionNursingNote(ctx context.Context, arg CreateSessionNursingNoteParams) (SessionNursingNote, error) {
	row := q.db.QueryRow(ctx, createSessionNursingNote,
		arg.HospitalID,
		arg.SessionID,
		arg.PatientID,
		arg.NurseID,
		arg.NoteType,
		arg.RecordedAt,
		arg.Content,
		arg.IsFlaggedForDoctor,
	)
	var i SessionNursingNote
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.SessionID,
		&i.PatientID,
		&i.NurseID,
		&i.NoteType,
		&i.RecordedAt,
		&i.Content,
		&i.IsFlaggedForDoctor,
		&i.DoctorReviewedBy,
		&i.DoctorReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteSessionNursingNote = `-- name: DeleteSessionNursingNote :exec
UPDATE session_nursing_notes SET deleted_at = now() WHERE id = $1
`

func (q *Queries) DeleteSessionNursingNote(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionNursingNote, id)
	return err
}

const getSessionNursingNote = `-- name: GetSessionNursingNote :one
SELECT id, hospital_id, session_id, patient_id, nurse_id, note_type, recorded_at, content, is_flagged_for_doctor, doctor_reviewed_by, doctor_reviewed_at, created_at, updated_at, deleted_at FROM session_nursing_notes WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSessionNursingNote(ctx context.Context, id uuid.UUID) (SessionNursingNote, error) {
	row := q.db.QueryRow(ctx, getSessionNursingNote, id)
	var i SessionNursingNote
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.SessionID,
		&i.PatientID,
		&i.NurseID,
		&i.NoteType,
		&i.RecordedAt,
		&i.Content,
		&i.IsFlaggedForDoctor,
		&i.DoctorReviewedBy,
		&i.DoctorReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listFlaggedNotes = `-- name: ListFlaggedNotes :many
SELECT id, hospital_id, session_id, patient_id, nurse_id, note_type, recorded_at, content, is_flagged_for_doctor, doctor_reviewed_by, doctor_reviewed_at, created_at, updated_at, deleted_at FROM session_nursing_notes
WHERE hospital_id = $1
  AND is_flagged_for_doctor = TRUE
  AND doctor_reviewed_at IS NULL
  AND deleted_at IS NULL
ORDER BY recorded_at
`

func (q *Queries) ListFlaggedNotes(ctx context.Context, hospitalID uuid.UUID) ([]SessionNursingNote, error) {
	rows, err := q.db.Query(ctx, listFlaggedNotes, hospitalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionNursingNote
	for rows.Next() {
		var i SessionNursingNote
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.SessionID,
			&i.PatientID,
			&i.NurseID,
			&i.NoteType,
			&i.RecordedAt,
			&i.Content,
			&i.IsFlaggedForDoctor,
			&i.DoctorReviewedBy,
			&i.DoctorReviewedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNursingNotesBySession = `-- name: ListNursingNotesBySession :many
SELECT id, hospital_id, session_id, patient_id, nurse_id, note_type, recorded_at, content, is_flagged_for_doctor, doctor_reviewed_by, doctor_reviewed_at, created_at, updated_at, deleted_at FROM session_nursing_notes
WHERE session_id = $1 AND deleted_at IS NULL
ORDER BY recorded_at
`

func (q *Queries) ListNursingNotesBySession(ctx context.Context, sessionID uuid.UUID) ([]SessionNursingNote, error) {
	rows, err := q.db.Query(ctx, listNursingNotesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionNursingNote
	for rows.Next() {
		var i SessionNursingNote
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.SessionID,
			&i.PatientID,
			&i.NurseID,
			&i.NoteType,
			&i.RecordedAt,
			&i.Content,
			&i.IsFlaggedForDoctor,
			&i.DoctorReviewedBy,
			&i.DoctorReviewedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNoteReviewedByDoctor = `-- name: MarkNoteReviewedByDoctor :one
UPDATE session_nursing_notes
SET doctor_reviewed_by = $2, doctor_reviewed_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, hospital_id, session_id, patient_id, nurse_id, note_type, recorded_at, content, is_flagged_for_doctor, doctor_reviewed_by, doctor_reviewed_at, created_at, updated_at, deleted_at
`

type MarkNoteReviewedByDoctorParams struct {
	ID               uuid.UUID   `json:"id"`
	DoctorReviewedBy pgtype.UUID `json:"doctor_reviewed_by"`
}

func (q *Queries) MarkNoteReviewedByDoctor(ctx context.Context, arg MarkNoteReviewedByDoctorParams) (SessionNursingNote, error) {
	row := q.db.QueryRow(ctx, markNoteReviewedByDoctor, arg.ID, arg.DoctorReviewedBy)
	var i SessionNursingNote
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.SessionID,
		&i.PatientID,
		&i.NurseID,
		&i.NoteType,
		&i.RecordedAt,
		&i.Content,
		&i.IsFlaggedForDoctor,
		&i.DoctorReviewedBy,
		&i.DoctorReviewedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
