// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: staff_qualifications.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createStaffQualification = `-- name: CreateStaffQualification :one
INSERT INTO staff_qualifications (
    hospital_id, staff_id, qualification_type, qualification_name,
    institution, country, year_obtained, certificate_number,
    expiry_date, document_url, file_attachment_id, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, hospital_id, staff_id, qualification_type, qualification_name, institution, country, year_obtained, certificate_number, expiry_date, document_url, file_attachment_id, is_verified, verified_by, verified_at, notes, created_at, updated_at, deleted_at
`

type CreateStaffQualificationParams struct {
	HospitalID        uuid.UUID   `json:"hospital_id"`
	StaffID           uuid.UUID   `json:"staff_id"`
	QualificationType string      `json:"qualification_type"`
	QualificationName string      `json:"qualification_name"`
	Institution       pgtype.Text `json:"institution"`
	Country           pgtype.Text `json:"country"`
	YearObtained      pgtype.Int4 `json:"year_obtained"`
	CertificateNumber pgtype.Text `json:"certificate_number"`
	ExpiryDate        pgtype.Date `json:"expiry_date"`
	DocumentUrl       pgtype.Text `json:"document_url"`
	FileAttachmentID  pgtype.UUID `json:"file_attachment_id"`
	Notes             pgtype.Text `json:"notes"`
}

func (q *Queries) CreateStaffQualification(ctx context.Context, arg CreateStaffQualificationParams) (StaffQualification, error) {
	row := q.db.QueryRow(ctx, createStaffQualification,
		arg.HospitalID,
		arg.StaffID,
		arg.QualificationType,
		arg.QualificationName,
		arg.Institution,
		arg.Country,
		arg.YearObtained,
		arg.CertificateNumber,
		arg.ExpiryDate,
		arg.DocumentUrl,
		arg.FileAttachmentID,
		arg.Notes,
	)
	var i StaffQualification
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.StaffID,
		&i.QualificationType,
		&i.QualificationName,
		&i.Institution,
		&i.Country,
		&i.YearObtained,
		&i.CertificateNumber,
		&i.ExpiryDate,
		&i.DocumentUrl,
		&i.FileAttachmentID,
		&i.IsVerified,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteStaffQualification = `-- name: DeleteStaffQualification :exec
UPDATE staff_qualifications SET deleted_at = now() WHERE id = $1
`

func (q *Queries) DeleteStaffQualification(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteStaffQualification, id)
	return err
}

const getStaffQualification = `-- name: GetStaffQualification :one
SELECT id, hospital_id, staff_id, qualification_type, qualification_name, institution, country, year_obtained, certificate_number, expiry_date, document_url, file_attachment_id, is_verified, verified_by, verified_at, notes, created_at, updated_at, deleted_at FROM staff_qualifications WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetStaffQualification(ctx context.Context, id uuid.UUID) (StaffQualification, error) {
	row := q.db.QueryRow(ctx, getStaffQualification, id)
	var i StaffQualification
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.StaffID,
		&i.QualificationType,
		&i.QualificationName,
		&i.Institution,
		&i.Country,
		&i.YearObtained,
		&i.CertificateNumber,
		&i.ExpiryDate,
		&i.DocumentUrl,
		&i.FileAttachmentID,
		&i.IsVerified,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listExpiringQualifications = `-- name: ListExpiringQualifications :many
SELECT id, hospital_id, staff_id, qualification_type, qualification_name, institution, country, year_obtained, certificate_number, expiry_date, document_url, file_attachment_id, is_verified, verified_by, verified_at, notes, created_at, updated_at, deleted_at FROM staff_qualifications
WHERE hospital_id = $1
  AND expiry_date <= $2
  AND deleted_at IS NULL
ORDER BY expiry_date ASC
`

type ListExpiringQualificationsParams struct {
	HospitalID uuid.UUID   `json:"hospital_id"`
	ExpiryDate pgtype.Date `json:"expiry_date"`
}

func (q *Queries) ListExpiringQualifications(ctx context.Context, arg ListExpiringQualificationsParams) ([]StaffQualification, error) {
	rows, err := q.db.Query(ctx, listExpiringQualifications, arg.HospitalID, arg.ExpiryDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StaffQualification
	for rows.Next() {
		var i StaffQualification
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.StaffID,
			&i.QualificationType,
			&i.QualificationName,
			&i.Institution,
			&i.Country,
			&i.YearObtained,
			&i.CertificateNumber,
			&i.ExpiryDate,
			&i.DocumentUrl,
			&i.FileAttachmentID,
			&i.IsVerified,
			&i.VerifiedBy,
			&i.VerifiedAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQualificationsByStaff = `-- name: ListQualificationsByStaff :many
SELECT id, hospital_id, staff_id, qualification_type, qualification_name, institution, country, year_obtained, certificate_number, expiry_date, document_url, file_attachment_id, is_verified, verified_by, verified_at, notes, created_at, updated_at, deleted_at FROM staff_qualifications
WHERE staff_id = $1 AND deleted_at IS NULL
ORDER BY year_obtained DESC
`

func (q *Queries) ListQualificationsByStaff(ctx context.Context, staffID uuid.UUID) ([]StaffQualification, error) {
	rows, err := q.db.Query(ctx, listQualificationsByStaff, staffID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StaffQualification
	for rows.Next() {
		var i StaffQualification
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.StaffID,
			&i.QualificationType,
			&i.QualificationName,
			&i.Institution,
			&i.Country,
			&i.YearObtained,
			&i.CertificateNumber,
			&i.ExpiryDate,
			&i.DocumentUrl,
			&i.FileAttachmentID,
			&i.IsVerified,
			&i.VerifiedBy,
			&i.VerifiedAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const verifyQualification = `-- name: VerifyQualification :one
UPDATE staff_qualifications
SET is_verified = TRUE, verified_by = $2, verified_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, hospital_id, staff_id, qualification_type, qualification_name, institution, country, year_obtained, certificate_number, expiry_date, document_url, file_attachment_id, is_verified, verified_by, verified_at, notes, created_at, updated_at, deleted_at
`

type VerifyQualificationParams struct {
	ID         uuid.UUID   `json:"id"`
	VerifiedBy pgtype.UUID `json:"verified_by"`
}

func (q *Queries) VerifyQualification(ctx context.Context, arg VerifyQualificationParams) (StaffQualification, error) {
	row := q.db.QueryRow(ctx, verifyQualification, arg.ID, arg.VerifiedBy)
	var i StaffQualification
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.StaffID,
		&i.QualificationType,
		&i.QualificationName,
		&i.Institution,
		&i.Country,
		&i.YearObtained,
		&i.CertificateNumber,
		&i.ExpiryDate,
		&i.DocumentUrl,
		&i.FileAttachmentID,
		&i.IsVerified,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
