// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: staff_performance.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createStaffPerformance = `-- name: CreateStaffPerformance :one
INSERT INTO staff_performance (
    hospital_id, staff_id, review_period_start, review_period_end,
    review_date, appraised_by, overall_score, technical_competence_score,
    communication_score, teamwork_score, punctuality_score, patient_care_score,
    strengths, areas_for_improvement, goals_next_period,
    training_recommendations, promotion_recommended, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
RETURNING id, hospital_id, staff_id, review_period_start, review_period_end, review_date, appraised_by, overall_score, technical_competence_score, communication_score, teamwork_score, punctuality_score, patient_care_score, strengths, areas_for_improvement, goals_next_period, training_recommendations, staff_comments, promotion_recommended, notes, created_at, updated_at, deleted_at
`

type CreateStaffPerformanceParams struct {
	HospitalID               uuid.UUID      `json:"hospital_id"`
	StaffID                  uuid.UUID      `json:"staff_id"`
	ReviewPeriodStart        pgtype.Date    `json:"review_period_start"`
	ReviewPeriodEnd          pgtype.Date    `json:"review_period_end"`
	ReviewDate               pgtype.Date    `json:"review_date"`
	AppraisedBy              uuid.UUID      `json:"appraised_by"`
	OverallScore             pgtype.Numeric `json:"overall_score"`
	TechnicalCompetenceScore pgtype.Numeric `json:"technical_competence_score"`
	CommunicationScore       pgtype.Numeric `json:"communication_score"`
	TeamworkScore            pgtype.Numeric `json:"teamwork_score"`
	PunctualityScore         pgtype.Numeric `json:"punctuality_score"`
	PatientCareScore         pgtype.Numeric `json:"patient_care_score"`
	Strengths                pgtype.Text    `json:"strengths"`
	AreasForImprovement      pgtype.Text    `json:"areas_for_improvement"`
	GoalsNextPeriod          pgtype.Text    `json:"goals_next_period"`
	TrainingRecommendations  pgtype.Text    `json:"training_recommendations"`
	PromotionRecommended     bool           `json:"promotion_recommended"`
	Notes                    pgtype.Text    `json:"notes"`
}

func (q *Queries) CreateStaffPerformance(ctx context.Context, arg CreateStaffPerformanceParams) (StaffPerformance, error) {
	row := q.db.QueryRow(ctx, createStaffPerformance,
		arg.HospitalID,
		arg.StaffID,
		arg.ReviewPeriodStart,
		arg.ReviewPeriodEnd,
		arg.ReviewDate,
		arg.AppraisedBy,
		arg.OverallScore,
		arg.TechnicalCompetenceScore,
		arg.CommunicationScore,
		arg.TeamworkScore,
		arg.PunctualityScore,
		arg.PatientCareScore,
		arg.Strengths,
		arg.AreasForImprovement,
		arg.GoalsNextPeriod,
		arg.TrainingRecommendations,
		arg.PromotionRecommended,
		arg.Notes,
	)
	var i StaffPerformance
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.StaffID,
		&i.ReviewPeriodStart,
		&i.ReviewPeriodEnd,
		&i.ReviewDate,
		&i.AppraisedBy,
		&i.OverallScore,
		&i.TechnicalCompetenceScore,
		&i.CommunicationScore,
		&i.TeamworkScore,
		&i.PunctualityScore,
		&i.PatientCareScore,
		&i.Strengths,
		&i.AreasForImprovement,
		&i.GoalsNextPeriod,
		&i.TrainingRecommendations,
		&i.StaffComments,
		&i.PromotionRecommended,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteStaffPerformance = `-- name: DeleteStaffPerformance :exec
UPDATE staff_performance SET deleted_at = now() WHERE id = $1
`

func (q *Queries) DeleteStaffPerformance(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteStaffPerformance, id)
	return err
}

const getLatestPerformance = `-- name: GetLatestPerformance :one
SELECT id, hospital_id, staff_id, review_period_start, review_period_end, review_date, appraised_by, overall_score, technical_competence_score, communication_score, teamwork_score, punctuality_score, patient_care_score, strengths, areas_for_improvement, goals_next_period, training_recommendations, staff_comments, promotion_recommended, notes, created_at, updated_at, deleted_at FROM staff_performance
WHERE staff_id = $1 AND deleted_at IS NULL
ORDER BY review_period_end DESC
LIMIT 1
`

func (q *Queries) GetLatestPerformance(ctx context.Context, staffID uuid.UUID) (StaffPerformance, error) {
	row := q.db.QueryRow(ctx, getLatestPerformance, staffID)
	var i StaffPerformance
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.StaffID,
		&i.ReviewPeriodStart,
		&i.ReviewPeriodEnd,
		&i.ReviewDate,
		&i.AppraisedBy,
		&i.OverallScore,
		&i.TechnicalCompetenceScore,
		&i.CommunicationScore,
		&i.TeamworkScore,
		&i.PunctualityScore,
		&i.PatientCareScore,
		&i.Strengths,
		&i.AreasForImprovement,
		&i.GoalsNextPeriod,
		&i.TrainingRecommendations,
		&i.StaffComments,
		&i.PromotionRecommended,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getStaffPerformance = `-- name: GetStaffPerformance :one
SELECT id, hospital_id, staff_id, review_period_start, review_period_end, review_date, appraised_by, overall_score, technical_competence_score, communication_score, teamwork_score, punctuality_score, patient_care_score, strengths, areas_for_improvement, goals_next_period, training_recommendations, staff_comments, promotion_recommended, notes, created_at, updated_at, deleted_at FROM staff_performance WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetStaffPerformance(ctx context.Context, id uuid.UUID) (StaffPerformance, error) {
	row := q.db.QueryRow(ctx, getStaffPerformance, id)
	var i StaffPerformance
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.StaffID,
		&i.ReviewPeriodStart,
		&i.ReviewPeriodEnd,
		&i.ReviewDate,
		&i.AppraisedBy,
		&i.OverallScore,
		&i.TechnicalCompetenceScore,
		&i.CommunicationScore,
		&i.TeamworkScore,
		&i.PunctualityScore,
		&i.PatientCareScore,
		&i.Strengths,
		&i.AreasForImprovement,
		&i.GoalsNextPeriod,
		&i.TrainingRecommendations,
		&i.StaffComments,
		&i.PromotionRecommended,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPerformanceByPeriod = `-- name: ListPerformanceByPeriod :many
SELECT id, hospital_id, staff_id, review_period_start, review_period_end, review_date, appraised_by, overall_score, technical_competence_score, communication_score, teamwork_score, punctuality_score, patient_care_score, strengths, areas_for_improvement, goals_next_period, training_recommendations, staff_comments, promotion_recommended, notes, created_at, updated_at, deleted_at FROM staff_performance
WHERE hospital_id = $1
  AND review_period_start >= $2
  AND review_period_end <= $3
  AND deleted_at IS NULL
ORDER BY review_period_start
`

type ListPerformanceByPeriodParams struct {
	HospitalID        uuid.UUID   `json:"hospital_id"`
	ReviewPeriodStart pgtype.Date `json:"review_period_start"`
	ReviewPeriodEnd   pgtype.Date `json:"review_period_end"`
}

func (q *Queries) ListPerformanceByPeriod(ctx context.Context, arg ListPerformanceByPeriodParams) ([]StaffPerformance, error) {
	rows, err := q.db.Query(ctx, listPerformanceByPeriod, arg.HospitalID, arg.ReviewPeriodStart, arg.ReviewPeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StaffPerformance
	for rows.Next() {
		var i StaffPerformance
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.StaffID,
			&i.ReviewPeriodStart,
			&i.ReviewPeriodEnd,
			&i.ReviewDate,
			&i.AppraisedBy,
			&i.OverallScore,
			&i.TechnicalCompetenceScore,
			&i.CommunicationScore,
			&i.TeamworkScore,
			&i.PunctualityScore,
			&i.PatientCareScore,
			&i.Strengths,
			&i.AreasForImprovement,
			&i.GoalsNextPeriod,
			&i.TrainingRecommendations,
			&i.StaffComments,
			&i.PromotionRecommended,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPerformanceByStaff = `-- name: ListPerformanceByStaff :many
SELECT id, hospital_id, staff_id, review_period_start, review_period_end, review_date, appraised_by, overall_score, technical_competence_score, communication_score, teamwork_score, punctuality_score, patient_care_score, strengths, areas_for_improvement, goals_next_period, training_recommendations, staff_comments, promotion_recommended, notes, created_at, updated_at, deleted_at FROM staff_performance
WHERE staff_id = $1 AND deleted_at IS NULL
ORDER BY review_period_start DESC
`

func (q *Queries) ListPerformanceByStaff(ctx context.Context, staffID uuid.UUID) ([]StaffPerformance, error) {
	rows, err := q.db.Query(ctx, listPerformanceByStaff, staffID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StaffPerformance
	for rows.Next() {
		var i StaffPerformance
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.StaffID,
			&i.ReviewPeriodStart,
			&i.ReviewPeriodEnd,
			&i.ReviewDate,
			&i.AppraisedBy,
			&i.OverallScore,
			&i.TechnicalCompetenceScore,
			&i.CommunicationScore,
			&i.TeamworkScore,
			&i.PunctualityScore,
			&i.PatientCareScore,
			&i.Strengths,
			&i.AreasForImprovement,
			&i.GoalsNextPeriod,
			&i.TrainingRecommendations,
			&i.StaffComments,
			&i.PromotionRecommended,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopPerformers = `-- name: ListTopPerformers :many
SELECT id, hospital_id, staff_id, review_period_start, review_period_end, review_date, appraised_by, overall_score, technical_competence_score, communication_score, teamwork_score, punctuality_score, patient_care_score, strengths, areas_for_improvement, goals_next_period, training_recommendations, staff_comments, promotion_recommended, notes, created_at, updated_at, deleted_at FROM staff_performance
WHERE hospital_id = $1
  AND review_period_start >= $2
  AND overall_score IS NOT NULL
  AND deleted_at IS NULL
ORDER BY overall_score DESC
LIMIT $3
`

type ListTopPerformersParams struct {
	HospitalID        uuid.UUID   `json:"hospital_id"`
	ReviewPeriodStart pgtype.Date `json:"review_period_start"`
	Limit             int32       `json:"limit"`
}

func (q *Queries) ListTopPerformers(ctx context.Context, arg ListTopPerformersParams) ([]StaffPerformance, error) {
	rows, err := q.db.Query(ctx, listTopPerformers, arg.HospitalID, arg.ReviewPeriodStart, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StaffPerformance
	for rows.Next() {
		var i StaffPerformance
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.StaffID,
			&i.ReviewPeriodStart,
			&i.ReviewPeriodEnd,
			&i.ReviewDate,
			&i.AppraisedBy,
			&i.OverallScore,
			&i.TechnicalCompetenceScore,
			&i.CommunicationScore,
			&i.TeamworkScore,
			&i.PunctualityScore,
			&i.PatientCareScore,
			&i.Strengths,
			&i.AreasForImprovement,
			&i.GoalsNextPeriod,
			&i.TrainingRecommendations,
			&i.StaffComments,
			&i.PromotionRecommended,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
