// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stock_movements.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createStockMovement = `-- name: CreateStockMovement :one
INSERT INTO stock_movements (
    hospital_id, stock_id, movement_type, quantity, reference_type,
    reference_id, performed_by, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, hospital_id, medication_id, stock_id, movement_type, quantity, quantity_before, quantity_after, unit_cost, total_cost, reference_type, reference_id, performed_by, movement_date, movement_time, reason, notes, created_at, updated_at, deleted_at
`

type CreateStockMovementParams struct {
	HospitalID    uuid.UUID         `json:"hospital_id"`
	StockID       pgtype.UUID       `json:"stock_id"`
	MovementType  StockMovementType `json:"movement_type"`
	Quantity      int32             `json:"quantity"`
	ReferenceType pgtype.Text       `json:"reference_type"`
	ReferenceID   pgtype.UUID       `json:"reference_id"`
	PerformedBy   uuid.UUID         `json:"performed_by"`
	Notes         pgtype.Text       `json:"notes"`
}

func (q *Queries) CreateStockMovement(ctx context.Context, arg CreateStockMovementParams) (StockMovement, error) {
	row := q.db.QueryRow(ctx, createStockMovement,
		arg.HospitalID,
		arg.StockID,
		arg.MovementType,
		arg.Quantity,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.PerformedBy,
		arg.Notes,
	)
	var i StockMovement
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.MedicationID,
		&i.StockID,
		&i.MovementType,
		&i.Quantity,
		&i.QuantityBefore,
		&i.QuantityAfter,
		&i.UnitCost,
		&i.TotalCost,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.PerformedBy,
		&i.MovementDate,
		&i.MovementTime,
		&i.Reason,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteStockMovement = `-- name: DeleteStockMovement :exec
UPDATE stock_movements SET deleted_at = now() WHERE id = $1
`

func (q *Queries) DeleteStockMovement(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteStockMovement, id)
	return err
}

const getMovementsByReference = `-- name: GetMovementsByReference :many
SELECT id, hospital_id, medication_id, stock_id, movement_type, quantity, quantity_before, quantity_after, unit_cost, total_cost, reference_type, reference_id, performed_by, movement_date, movement_time, reason, notes, created_at, updated_at, deleted_at FROM stock_movements
WHERE reference_type = $1 AND reference_id = $2 AND deleted_at IS NULL
ORDER BY movement_date
`

type GetMovementsByReferenceParams struct {
	ReferenceType pgtype.Text `json:"reference_type"`
	ReferenceID   pgtype.UUID `json:"reference_id"`
}

func (q *Queries) GetMovementsByReference(ctx context.Context, arg GetMovementsByReferenceParams) ([]StockMovement, error) {
	rows, err := q.db.Query(ctx, getMovementsByReference, arg.ReferenceType, arg.ReferenceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockMovement
	for rows.Next() {
		var i StockMovement
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.MedicationID,
			&i.StockID,
			&i.MovementType,
			&i.Quantity,
			&i.QuantityBefore,
			&i.QuantityAfter,
			&i.UnitCost,
			&i.TotalCost,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.PerformedBy,
			&i.MovementDate,
			&i.MovementTime,
			&i.Reason,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStockMovement = `-- name: GetStockMovement :one
SELECT id, hospital_id, medication_id, stock_id, movement_type, quantity, quantity_before, quantity_after, unit_cost, total_cost, reference_type, reference_id, performed_by, movement_date, movement_time, reason, notes, created_at, updated_at, deleted_at FROM stock_movements WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetStockMovement(ctx context.Context, id uuid.UUID) (StockMovement, error) {
	row := q.db.QueryRow(ctx, getStockMovement, id)
	var i StockMovement
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.MedicationID,
		&i.StockID,
		&i.MovementType,
		&i.Quantity,
		&i.QuantityBefore,
		&i.QuantityAfter,
		&i.UnitCost,
		&i.TotalCost,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.PerformedBy,
		&i.MovementDate,
		&i.MovementTime,
		&i.Reason,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listMovementsByHospital = `-- name: ListMovementsByHospital :many
SELECT id, hospital_id, medication_id, stock_id, movement_type, quantity, quantity_before, quantity_after, unit_cost, total_cost, reference_type, reference_id, performed_by, movement_date, movement_time, reason, notes, created_at, updated_at, deleted_at FROM stock_movements
WHERE hospital_id = $1 AND deleted_at IS NULL
ORDER BY movement_date DESC
LIMIT $2 OFFSET $3
`

type ListMovementsByHospitalParams struct {
	HospitalID uuid.UUID `json:"hospital_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListMovementsByHospital(ctx context.Context, arg ListMovementsByHospitalParams) ([]StockMovement, error) {
	rows, err := q.db.Query(ctx, listMovementsByHospital, arg.HospitalID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockMovement
	for rows.Next() {
		var i StockMovement
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.MedicationID,
			&i.StockID,
			&i.MovementType,
			&i.Quantity,
			&i.QuantityBefore,
			&i.QuantityAfter,
			&i.UnitCost,
			&i.TotalCost,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.PerformedBy,
			&i.MovementDate,
			&i.MovementTime,
			&i.Reason,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMovementsByStock = `-- name: ListMovementsByStock :many
SELECT id, hospital_id, medication_id, stock_id, movement_type, quantity, quantity_before, quantity_after, unit_cost, total_cost, reference_type, reference_id, performed_by, movement_date, movement_time, reason, notes, created_at, updated_at, deleted_at FROM stock_movements
WHERE stock_id = $1 AND deleted_at IS NULL
ORDER BY movement_date DESC
LIMIT $2 OFFSET $3
`

type ListMovementsByStockParams struct {
	StockID pgtype.UUID `json:"stock_id"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListMovementsByStock(ctx context.Context, arg ListMovementsByStockParams) ([]StockMovement, error) {
	rows, err := q.db.Query(ctx, listMovementsByStock, arg.StockID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockMovement
	for rows.Next() {
		var i StockMovement
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.MedicationID,
			&i.StockID,
			&i.MovementType,
			&i.Quantity,
			&i.QuantityBefore,
			&i.QuantityAfter,
			&i.UnitCost,
			&i.TotalCost,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.PerformedBy,
			&i.MovementDate,
			&i.MovementTime,
			&i.Reason,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMovementsByType = `-- name: ListMovementsByType :many
SELECT id, hospital_id, medication_id, stock_id, movement_type, quantity, quantity_before, quantity_after, unit_cost, total_cost, reference_type, reference_id, performed_by, movement_date, movement_time, reason, notes, created_at, updated_at, deleted_at FROM stock_movements
WHERE hospital_id = $1 AND movement_type = $2 AND deleted_at IS NULL
ORDER BY movement_date DESC
LIMIT $3 OFFSET $4
`

type ListMovementsByTypeParams struct {
	HospitalID   uuid.UUID         `json:"hospital_id"`
	MovementType StockMovementType `json:"movement_type"`
	Limit        int32             `json:"limit"`
	Offset       int32             `json:"offset"`
}

func (q *Queries) ListMovementsByType(ctx context.Context, arg ListMovementsByTypeParams) ([]StockMovement, error) {
	rows, err := q.db.Query(ctx, listMovementsByType,
		arg.HospitalID,
		arg.MovementType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockMovement
	for rows.Next() {
		var i StockMovement
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.MedicationID,
			&i.StockID,
			&i.MovementType,
			&i.Quantity,
			&i.QuantityBefore,
			&i.QuantityAfter,
			&i.UnitCost,
			&i.TotalCost,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.PerformedBy,
			&i.MovementDate,
			&i.MovementTime,
			&i.Reason,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
