// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: training_records.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeTraining = `-- name: CompleteTraining :one
UPDATE training_records
SET completed_at = now(), score = $2, pass_status = $3,
    certificate_url = $4, certificate_number = $5, certificate_expiry_date = $6
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, hospital_id, staff_id, training_name, training_category, training_provider, training_start_date, training_end_date, duration_hours, completed_at, score, pass_status, certificate_url, certificate_number, certificate_expiry_date, cpd_points, notes, created_at, updated_at, deleted_at
`

type CompleteTrainingParams struct {
	ID                    uuid.UUID      `json:"id"`
	Score                 pgtype.Numeric `json:"score"`
	PassStatus            pgtype.Text    `json:"pass_status"`
	CertificateUrl        pgtype.Text    `json:"certificate_url"`
	CertificateNumber     pgtype.Text    `json:"certificate_number"`
	CertificateExpiryDate pgtype.Date    `json:"certificate_expiry_date"`
}

func (q *Queries) CompleteTraining(ctx context.Context, arg CompleteTrainingParams) (TrainingRecord, error) {
	row := q.db.QueryRow(ctx, completeTraining,
		arg.ID,
		arg.Score,
		arg.PassStatus,
		arg.CertificateUrl,
		arg.CertificateNumber,
		arg.CertificateExpiryDate,
	)
	var i TrainingRecord
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.StaffID,
		&i.TrainingName,
		&i.TrainingCategory,
		&i.TrainingProvider,
		&i.TrainingStartDate,
		&i.TrainingEndDate,
		&i.DurationHours,
		&i.CompletedAt,
		&i.Score,
		&i.PassStatus,
		&i.CertificateUrl,
		&i.CertificateNumber,
		&i.CertificateExpiryDate,
		&i.CpdPoints,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createTrainingRecord = `-- name: CreateTrainingRecord :one
INSERT INTO training_records (
    hospital_id, staff_id, training_name, training_category,
    training_provider, training_start_date, training_end_date,
    duration_hours, cpd_points, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, hospital_id, staff_id, training_name, training_category, training_provider, training_start_date, training_end_date, duration_hours, completed_at, score, pass_status, certificate_url, certificate_number, certificate_expiry_date, cpd_points, notes, created_at, updated_at, deleted_at
`

type CreateTrainingRecordParams struct {
	HospitalID        uuid.UUID      `json:"hospital_id"`
	StaffID           uuid.UUID      `json:"staff_id"`
	TrainingName      string         `json:"training_name"`
	TrainingCategory  pgtype.Text    `json:"training_category"`
	TrainingProvider  pgtype.Text    `json:"training_provider"`
	TrainingStartDate pgtype.Date    `json:"training_start_date"`
	TrainingEndDate   pgtype.Date    `json:"training_end_date"`
	DurationHours     pgtype.Numeric `json:"duration_hours"`
	CpdPoints         pgtype.Numeric `json:"cpd_points"`
	Notes             pgtype.Text    `json:"notes"`
}

func (q *Queries) CreateTrainingRecord(ctx context.Context, arg CreateTrainingRecordParams) (TrainingRecord, error) {
	row := q.db.QueryRow(ctx, createTrainingRecord,
		arg.HospitalID,
		arg.StaffID,
		arg.TrainingName,
		arg.TrainingCategory,
		arg.TrainingProvider,
		arg.TrainingStartDate,
		arg.TrainingEndDate,
		arg.DurationHours,
		arg.CpdPoints,
		arg.Notes,
	)
	var i TrainingRecord
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.StaffID,
		&i.TrainingName,
		&i.TrainingCategory,
		&i.TrainingProvider,
		&i.TrainingStartDate,
		&i.TrainingEndDate,
		&i.DurationHours,
		&i.CompletedAt,
		&i.Score,
		&i.PassStatus,
		&i.CertificateUrl,
		&i.CertificateNumber,
		&i.CertificateExpiryDate,
		&i.CpdPoints,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteTrainingRecord = `-- name: DeleteTrainingRecord :exec
UPDATE training_records SET deleted_at = now() WHERE id = $1
`

func (q *Queries) DeleteTrainingRecord(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTrainingRecord, id)
	return err
}

const getTotalCPDPoints = `-- name: GetTotalCPDPoints :one
SELECT COALESCE(SUM(cpd_points), 0) AS total_cpd_points
FROM training_records
WHERE staff_id = $1
  AND training_start_date BETWEEN $2 AND $3
  AND deleted_at IS NULL
`

type GetTotalCPDPointsParams struct {
	StaffID             uuid.UUID   `json:"staff_id"`
	TrainingStartDate   pgtype.Date `json:"training_start_date"`
	TrainingStartDate_2 pgtype.Date `json:"training_start_date_2"`
}

func (q *Queries) GetTotalCPDPoints(ctx context.Context, arg GetTotalCPDPointsParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, getTotalCPDPoints, arg.StaffID, arg.TrainingStartDate, arg.TrainingStartDate_2)
	var total_cpd_points interface{}
	err := row.Scan(&total_cpd_points)
	return total_cpd_points, err
}

const getTrainingRecord = `-- name: GetTrainingRecord :one
SELECT id, hospital_id, staff_id, training_name, training_category, training_provider, training_start_date, training_end_date, duration_hours, completed_at, score, pass_status, certificate_url, certificate_number, certificate_expiry_date, cpd_points, notes, created_at, updated_at, deleted_at FROM training_records WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTrainingRecord(ctx context.Context, id uuid.UUID) (TrainingRecord, error) {
	row := q.db.QueryRow(ctx, getTrainingRecord, id)
	var i TrainingRecord
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.StaffID,
		&i.TrainingName,
		&i.TrainingCategory,
		&i.TrainingProvider,
		&i.TrainingStartDate,
		&i.TrainingEndDate,
		&i.DurationHours,
		&i.CompletedAt,
		&i.Score,
		&i.PassStatus,
		&i.CertificateUrl,
		&i.CertificateNumber,
		&i.CertificateExpiryDate,
		&i.CpdPoints,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listExpiringCertificates = `-- name: ListExpiringCertificates :many
SELECT id, hospital_id, staff_id, training_name, training_category, training_provider, training_start_date, training_end_date, duration_hours, completed_at, score, pass_status, certificate_url, certificate_number, certificate_expiry_date, cpd_points, notes, created_at, updated_at, deleted_at FROM training_records
WHERE hospital_id = $1
  AND certificate_expiry_date <= $2
  AND deleted_at IS NULL
ORDER BY certificate_expiry_date ASC
`

type ListExpiringCertificatesParams struct {
	HospitalID            uuid.UUID   `json:"hospital_id"`
	CertificateExpiryDate pgtype.Date `json:"certificate_expiry_date"`
}

func (q *Queries) ListExpiringCertificates(ctx context.Context, arg ListExpiringCertificatesParams) ([]TrainingRecord, error) {
	rows, err := q.db.Query(ctx, listExpiringCertificates, arg.HospitalID, arg.CertificateExpiryDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrainingRecord
	for rows.Next() {
		var i TrainingRecord
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.StaffID,
			&i.TrainingName,
			&i.TrainingCategory,
			&i.TrainingProvider,
			&i.TrainingStartDate,
			&i.TrainingEndDate,
			&i.DurationHours,
			&i.CompletedAt,
			&i.Score,
			&i.PassStatus,
			&i.CertificateUrl,
			&i.CertificateNumber,
			&i.CertificateExpiryDate,
			&i.CpdPoints,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrainingByCategory = `-- name: ListTrainingByCategory :many
SELECT id, hospital_id, staff_id, training_name, training_category, training_provider, training_start_date, training_end_date, duration_hours, completed_at, score, pass_status, certificate_url, certificate_number, certificate_expiry_date, cpd_points, notes, created_at, updated_at, deleted_at FROM training_records
WHERE hospital_id = $1 AND training_category = $2 AND deleted_at IS NULL
ORDER BY training_start_date DESC
`

type ListTrainingByCategoryParams struct {
	HospitalID       uuid.UUID   `json:"hospital_id"`
	TrainingCategory pgtype.Text `json:"training_category"`
}

func (q *Queries) ListTrainingByCategory(ctx context.Context, arg ListTrainingByCategoryParams) ([]TrainingRecord, error) {
	rows, err := q.db.Query(ctx, listTrainingByCategory, arg.HospitalID, arg.TrainingCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrainingRecord
	for rows.Next() {
		var i TrainingRecord
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.StaffID,
			&i.TrainingName,
			&i.TrainingCategory,
			&i.TrainingProvider,
			&i.TrainingStartDate,
			&i.TrainingEndDate,
			&i.DurationHours,
			&i.CompletedAt,
			&i.Score,
			&i.PassStatus,
			&i.CertificateUrl,
			&i.CertificateNumber,
			&i.CertificateExpiryDate,
			&i.CpdPoints,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrainingByStaff = `-- name: ListTrainingByStaff :many
SELECT id, hospital_id, staff_id, training_name, training_category, training_provider, training_start_date, training_end_date, duration_hours, completed_at, score, pass_status, certificate_url, certificate_number, certificate_expiry_date, cpd_points, notes, created_at, updated_at, deleted_at FROM training_records
WHERE staff_id = $1 AND deleted_at IS NULL
ORDER BY training_start_date DESC
`

func (q *Queries) ListTrainingByStaff(ctx context.Context, staffID uuid.UUID) ([]TrainingRecord, error) {
	rows, err := q.db.Query(ctx, listTrainingByStaff, staffID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrainingRecord
	for rows.Next() {
		var i TrainingRecord
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.StaffID,
			&i.TrainingName,
			&i.TrainingCategory,
			&i.TrainingProvider,
			&i.TrainingStartDate,
			&i.TrainingEndDate,
			&i.DurationHours,
			&i.CompletedAt,
			&i.Score,
			&i.PassStatus,
			&i.CertificateUrl,
			&i.CertificateNumber,
			&i.CertificateExpiryDate,
			&i.CpdPoints,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
