// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transfers.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO transfers (
    hospital_id, patient_id, from_hospital_id, to_hospital_id, from_department,
    to_department, reason, reason_notes, requested_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, hospital_id, patient_id, from_hospital_id, to_hospital_id, from_department, to_department, reason, reason_notes, status, requested_by, requested_at, approved_by, approved_at, transferred_at, received_by, transfer_notes, created_at, updated_at, deleted_at
`

type CreateTransferParams struct {
	HospitalID     uuid.UUID      `json:"hospital_id"`
	PatientID      uuid.UUID      `json:"patient_id"`
	FromHospitalID pgtype.UUID    `json:"from_hospital_id"`
	ToHospitalID   pgtype.UUID    `json:"to_hospital_id"`
	FromDepartment pgtype.Text    `json:"from_department"`
	ToDepartment   pgtype.Text    `json:"to_department"`
	Reason         TransferReason `json:"reason"`
	ReasonNotes    pgtype.Text    `json:"reason_notes"`
	RequestedBy    uuid.UUID      `json:"requested_by"`
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error) {
	row := q.db.QueryRow(ctx, createTransfer,
		arg.HospitalID,
		arg.PatientID,
		arg.FromHospitalID,
		arg.ToHospitalID,
		arg.FromDepartment,
		arg.ToDepartment,
		arg.Reason,
		arg.ReasonNotes,
		arg.RequestedBy,
	)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.PatientID,
		&i.FromHospitalID,
		&i.ToHospitalID,
		&i.FromDepartment,
		&i.ToDepartment,
		&i.Reason,
		&i.ReasonNotes,
		&i.Status,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.TransferredAt,
		&i.ReceivedBy,
		&i.TransferNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listTransfersByPatient = `-- name: ListTransfersByPatient :many
SELECT id, hospital_id, patient_id, from_hospital_id, to_hospital_id, from_department, to_department, reason, reason_notes, status, requested_by, requested_at, approved_by, approved_at, transferred_at, received_by, transfer_notes, created_at, updated_at, deleted_at FROM transfers
WHERE patient_id = $1 AND deleted_at IS NULL
ORDER BY requested_at DESC
`

func (q *Queries) ListTransfersByPatient(ctx context.Context, patientID uuid.UUID) ([]Transfer, error) {
	rows, err := q.db.Query(ctx, listTransfersByPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transfer
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.PatientID,
			&i.FromHospitalID,
			&i.ToHospitalID,
			&i.FromDepartment,
			&i.ToDepartment,
			&i.Reason,
			&i.ReasonNotes,
			&i.Status,
			&i.RequestedBy,
			&i.RequestedAt,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.TransferredAt,
			&i.ReceivedBy,
			&i.TransferNotes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransferStatus = `-- name: UpdateTransferStatus :one
UPDATE transfers
SET status = $2, approved_by = $3, approved_at = $4
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, hospital_id, patient_id, from_hospital_id, to_hospital_id, from_department, to_department, reason, reason_notes, status, requested_by, requested_at, approved_by, approved_at, transferred_at, received_by, transfer_notes, created_at, updated_at, deleted_at
`

type UpdateTransferStatusParams struct {
	ID         uuid.UUID          `json:"id"`
	Status     TransferStatus     `json:"status"`
	ApprovedBy pgtype.UUID        `json:"approved_by"`
	ApprovedAt pgtype.Timestamptz `json:"approved_at"`
}

func (q *Queries) UpdateTransferStatus(ctx context.Context, arg UpdateTransferStatusParams) (Transfer, error) {
	row := q.db.QueryRow(ctx, updateTransferStatus,
		arg.ID,
		arg.Status,
		arg.ApprovedBy,
		arg.ApprovedAt,
	)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.PatientID,
		&i.FromHospitalID,
		&i.ToHospitalID,
		&i.FromDepartment,
		&i.ToDepartment,
		&i.Reason,
		&i.ReasonNotes,
		&i.Status,
		&i.RequestedBy,
		&i.RequestedAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.TransferredAt,
		&i.ReceivedBy,
		&i.TransferNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
