// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  hospital_id, email, phone, password_hash, full_name, is_active
) VALUES (
  $1, $2, $3, $4, $5, $6
) RETURNING id, hospital_id, email, phone, password_hash, full_name, is_active, is_verified, last_login_at, password_reset_at, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	HospitalID   uuid.UUID   `json:"hospital_id"`
	Email        string      `json:"email"`
	Phone        pgtype.Text `json:"phone"`
	PasswordHash string      `json:"password_hash"`
	FullName     string      `json:"full_name"`
	IsActive     bool        `json:"is_active"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.HospitalID,
		arg.Email,
		arg.Phone,
		arg.PasswordHash,
		arg.FullName,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.FullName,
		&i.IsActive,
		&i.IsVerified,
		&i.LastLoginAt,
		&i.PasswordResetAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, hospital_id, email, phone, password_hash, full_name, is_active, is_verified, last_login_at, password_reset_at, created_at, updated_at, deleted_at FROM users
WHERE id = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.FullName,
		&i.IsActive,
		&i.IsVerified,
		&i.LastLoginAt,
		&i.PasswordResetAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, hospital_id, email, phone, password_hash, full_name, is_active, is_verified, last_login_at, password_reset_at, created_at, updated_at, deleted_at FROM users
WHERE hospital_id = $1 AND email = $2 AND deleted_at IS NULL
LIMIT 1
`

type GetUserByEmailParams struct {
	HospitalID uuid.UUID `json:"hospital_id"`
	Email      string    `json:"email"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.HospitalID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.FullName,
		&i.IsActive,
		&i.IsVerified,
		&i.LastLoginAt,
		&i.PasswordResetAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserForLogin = `-- name: GetUserForLogin :one
SELECT id, hospital_id, email, phone, password_hash, full_name, is_active, is_verified, last_login_at, password_reset_at, created_at, updated_at, deleted_at FROM users
WHERE email = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetUserForLogin(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserForLogin, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.FullName,
		&i.IsActive,
		&i.IsVerified,
		&i.LastLoginAt,
		&i.PasswordResetAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listActiveUsers = `-- name: ListActiveUsers :many
SELECT id, hospital_id, email, phone, password_hash, full_name, is_active, is_verified, last_login_at, password_reset_at, created_at, updated_at, deleted_at FROM users
WHERE hospital_id = $1 AND is_active = true AND deleted_at IS NULL
ORDER BY full_name
`

func (q *Queries) ListActiveUsers(ctx context.Context, hospitalID uuid.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listActiveUsers, hospitalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.Email,
			&i.Phone,
			&i.PasswordHash,
			&i.FullName,
			&i.IsActive,
			&i.IsVerified,
			&i.LastLoginAt,
			&i.PasswordResetAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET deleted_at = now()
WHERE id = $1
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET email = $2, phone = $3, full_name = $4, is_active = $5
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, hospital_id, email, phone, password_hash, full_name, is_active, is_verified, last_login_at, password_reset_at, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	ID       uuid.UUID   `json:"id"`
	Email    string      `json:"email"`
	Phone    pgtype.Text `json:"phone"`
	FullName string      `json:"full_name"`
	IsActive bool        `json:"is_active"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.Phone,
		arg.FullName,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.FullName,
		&i.IsActive,
		&i.IsVerified,
		&i.LastLoginAt,
		&i.PasswordResetAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET last_login_at = now()
WHERE id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2, password_reset_at = now()
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}
