// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vascular_access_assessments.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createVascularAccessAssessment = `-- name: CreateVascularAccessAssessment :one
INSERT INTO vascular_access_assessments (
    hospital_id, access_id, patient_id, session_id, assessed_by, assessed_at,
    has_thrill, has_bruit, has_redness, has_swelling, has_discharge,
    has_bleeding, has_pain, appearance_normal, flow_rate_ml_min,
    venous_pressure_mmhg, arterial_pressure_mmhg, recirculation_percent,
    requires_intervention, intervention_type, intervention_urgency, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22)
RETURNING id, hospital_id, access_id, patient_id, session_id, assessed_by, assessed_at, has_thrill, has_bruit, has_redness, has_swelling, has_discharge, has_bleeding, has_pain, appearance_normal, flow_rate_ml_min, venous_pressure_mmhg, arterial_pressure_mmhg, recirculation_percent, requires_intervention, intervention_type, intervention_urgency, notes, created_at, updated_at, deleted_at
`

type CreateVascularAccessAssessmentParams struct {
	HospitalID           uuid.UUID          `json:"hospital_id"`
	AccessID             uuid.UUID          `json:"access_id"`
	PatientID            uuid.UUID          `json:"patient_id"`
	SessionID            pgtype.UUID        `json:"session_id"`
	AssessedBy           uuid.UUID          `json:"assessed_by"`
	AssessedAt           pgtype.Timestamptz `json:"assessed_at"`
	HasThrill            pgtype.Bool        `json:"has_thrill"`
	HasBruit             pgtype.Bool        `json:"has_bruit"`
	HasRedness           bool               `json:"has_redness"`
	HasSwelling          bool               `json:"has_swelling"`
	HasDischarge         bool               `json:"has_discharge"`
	HasBleeding          bool               `json:"has_bleeding"`
	HasPain              bool               `json:"has_pain"`
	AppearanceNormal     bool               `json:"appearance_normal"`
	FlowRateMlMin        pgtype.Int4        `json:"flow_rate_ml_min"`
	VenousPressureMmhg   pgtype.Int4        `json:"venous_pressure_mmhg"`
	ArterialPressureMmhg pgtype.Int4        `json:"arterial_pressure_mmhg"`
	RecirculationPercent pgtype.Numeric     `json:"recirculation_percent"`
	RequiresIntervention bool               `json:"requires_intervention"`
	InterventionType     pgtype.Text        `json:"intervention_type"`
	InterventionUrgency  pgtype.Text        `json:"intervention_urgency"`
	Notes                pgtype.Text        `json:"notes"`
}

func (q *Queries) CreateVascularAccessAssessment(ctx context.Context, arg CreateVascularAccessAssessmentParams) (VascularAccessAssessment, error) {
	row := q.db.QueryRow(ctx, createVascularAccessAssessment,
		arg.HospitalID,
		arg.AccessID,
		arg.PatientID,
		arg.SessionID,
		arg.AssessedBy,
		arg.AssessedAt,
		arg.HasThrill,
		arg.HasBruit,
		arg.HasRedness,
		arg.HasSwelling,
		arg.HasDischarge,
		arg.HasBleeding,
		arg.HasPain,
		arg.AppearanceNormal,
		arg.FlowRateMlMin,
		arg.VenousPressureMmhg,
		arg.ArterialPressureMmhg,
		arg.RecirculationPercent,
		arg.RequiresIntervention,
		arg.InterventionType,
		arg.InterventionUrgency,
		arg.Notes,
	)
	var i VascularAccessAssessment
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.AccessID,
		&i.PatientID,
		&i.SessionID,
		&i.AssessedBy,
		&i.AssessedAt,
		&i.HasThrill,
		&i.HasBruit,
		&i.HasRedness,
		&i.HasSwelling,
		&i.HasDischarge,
		&i.HasBleeding,
		&i.HasPain,
		&i.AppearanceNormal,
		&i.FlowRateMlMin,
		&i.VenousPressureMmhg,
		&i.ArterialPressureMmhg,
		&i.RecirculationPercent,
		&i.RequiresIntervention,
		&i.InterventionType,
		&i.InterventionUrgency,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteVascularAccessAssessment = `-- name: DeleteVascularAccessAssessment :exec
UPDATE vascular_access_assessments SET deleted_at = now() WHERE id = $1
`

func (q *Queries) DeleteVascularAccessAssessment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteVascularAccessAssessment, id)
	return err
}

const getVascularAccessAssessment = `-- name: GetVascularAccessAssessment :one
SELECT id, hospital_id, access_id, patient_id, session_id, assessed_by, assessed_at, has_thrill, has_bruit, has_redness, has_swelling, has_discharge, has_bleeding, has_pain, appearance_normal, flow_rate_ml_min, venous_pressure_mmhg, arterial_pressure_mmhg, recirculation_percent, requires_intervention, intervention_type, intervention_urgency, notes, created_at, updated_at, deleted_at FROM vascular_access_assessments WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetVascularAccessAssessment(ctx context.Context, id uuid.UUID) (VascularAccessAssessment, error) {
	row := q.db.QueryRow(ctx, getVascularAccessAssessment, id)
	var i VascularAccessAssessment
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.AccessID,
		&i.PatientID,
		&i.SessionID,
		&i.AssessedBy,
		&i.AssessedAt,
		&i.HasThrill,
		&i.HasBruit,
		&i.HasRedness,
		&i.HasSwelling,
		&i.HasDischarge,
		&i.HasBleeding,
		&i.HasPain,
		&i.AppearanceNormal,
		&i.FlowRateMlMin,
		&i.VenousPressureMmhg,
		&i.ArterialPressureMmhg,
		&i.RecirculationPercent,
		&i.RequiresIntervention,
		&i.InterventionType,
		&i.InterventionUrgency,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAssessmentsByAccess = `-- name: ListAssessmentsByAccess :many
SELECT id, hospital_id, access_id, patient_id, session_id, assessed_by, assessed_at, has_thrill, has_bruit, has_redness, has_swelling, has_discharge, has_bleeding, has_pain, appearance_normal, flow_rate_ml_min, venous_pressure_mmhg, arterial_pressure_mmhg, recirculation_percent, requires_intervention, intervention_type, intervention_urgency, notes, created_at, updated_at, deleted_at FROM vascular_access_assessments
WHERE access_id = $1 AND deleted_at IS NULL
ORDER BY assessed_at DESC
`

func (q *Queries) ListAssessmentsByAccess(ctx context.Context, accessID uuid.UUID) ([]VascularAccessAssessment, error) {
	rows, err := q.db.Query(ctx, listAssessmentsByAccess, accessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VascularAccessAssessment
	for rows.Next() {
		var i VascularAccessAssessment
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.AccessID,
			&i.PatientID,
			&i.SessionID,
			&i.AssessedBy,
			&i.AssessedAt,
			&i.HasThrill,
			&i.HasBruit,
			&i.HasRedness,
			&i.HasSwelling,
			&i.HasDischarge,
			&i.HasBleeding,
			&i.HasPain,
			&i.AppearanceNormal,
			&i.FlowRateMlMin,
			&i.VenousPressureMmhg,
			&i.ArterialPressureMmhg,
			&i.RecirculationPercent,
			&i.RequiresIntervention,
			&i.InterventionType,
			&i.InterventionUrgency,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssessmentsBySession = `-- name: ListAssessmentsBySession :many
SELECT id, hospital_id, access_id, patient_id, session_id, assessed_by, assessed_at, has_thrill, has_bruit, has_redness, has_swelling, has_discharge, has_bleeding, has_pain, appearance_normal, flow_rate_ml_min, venous_pressure_mmhg, arterial_pressure_mmhg, recirculation_percent, requires_intervention, intervention_type, intervention_urgency, notes, created_at, updated_at, deleted_at FROM vascular_access_assessments
WHERE session_id = $1 AND deleted_at IS NULL
ORDER BY assessed_at
`

func (q *Queries) ListAssessmentsBySession(ctx context.Context, sessionID pgtype.UUID) ([]VascularAccessAssessment, error) {
	rows, err := q.db.Query(ctx, listAssessmentsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VascularAccessAssessment
	for rows.Next() {
		var i VascularAccessAssessment
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.AccessID,
			&i.PatientID,
			&i.SessionID,
			&i.AssessedBy,
			&i.AssessedAt,
			&i.HasThrill,
			&i.HasBruit,
			&i.HasRedness,
			&i.HasSwelling,
			&i.HasDischarge,
			&i.HasBleeding,
			&i.HasPain,
			&i.AppearanceNormal,
			&i.FlowRateMlMin,
			&i.VenousPressureMmhg,
			&i.ArterialPressureMmhg,
			&i.RecirculationPercent,
			&i.RequiresIntervention,
			&i.InterventionType,
			&i.InterventionUrgency,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssessmentsRequiringIntervention = `-- name: ListAssessmentsRequiringIntervention :many
SELECT id, hospital_id, access_id, patient_id, session_id, assessed_by, assessed_at, has_thrill, has_bruit, has_redness, has_swelling, has_discharge, has_bleeding, has_pain, appearance_normal, flow_rate_ml_min, venous_pressure_mmhg, arterial_pressure_mmhg, recirculation_percent, requires_intervention, intervention_type, intervention_urgency, notes, created_at, updated_at, deleted_at FROM vascular_access_assessments
WHERE hospital_id = $1
  AND requires_intervention = TRUE
  AND deleted_at IS NULL
ORDER BY assessed_at DESC
`

func (q *Queries) ListAssessmentsRequiringIntervention(ctx context.Context, hospitalID uuid.UUID) ([]VascularAccessAssessment, error) {
	rows, err := q.db.Query(ctx, listAssessmentsRequiringIntervention, hospitalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VascularAccessAssessment
	for rows.Next() {
		var i VascularAccessAssessment
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.AccessID,
			&i.PatientID,
			&i.SessionID,
			&i.AssessedBy,
			&i.AssessedAt,
			&i.HasThrill,
			&i.HasBruit,
			&i.HasRedness,
			&i.HasSwelling,
			&i.HasDischarge,
			&i.HasBleeding,
			&i.HasPain,
			&i.AppearanceNormal,
			&i.FlowRateMlMin,
			&i.VenousPressureMmhg,
			&i.ArterialPressureMmhg,
			&i.RecirculationPercent,
			&i.RequiresIntervention,
			&i.InterventionType,
			&i.InterventionUrgency,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
