// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: water_treatment_logs.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approveWaterTest = `-- name: ApproveWaterTest :one
UPDATE water_treatment_logs
SET approved_by = $2, approved_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, hospital_id, test_date, test_time, tested_by, sample_location, bacterial_count_cfu_ml, endotoxin_level_eu_ml, chlorine_level_ppm, chloramine_level_ppm, ph_level, conductivity_us_cm, hardness_mg_l, bacteria_result, endotoxin_result, chlorine_result, overall_result, out_of_spec_parameters, corrective_action_taken, corrective_action_by, retest_required, retest_date, systems_shut_down, shutdown_time, resumed_time, approved_by, approved_at, notes, created_at, updated_at, deleted_at
`

type ApproveWaterTestParams struct {
	ID         uuid.UUID   `json:"id"`
	ApprovedBy pgtype.UUID `json:"approved_by"`
}

func (q *Queries) ApproveWaterTest(ctx context.Context, arg ApproveWaterTestParams) (WaterTreatmentLog, error) {
	row := q.db.QueryRow(ctx, approveWaterTest, arg.ID, arg.ApprovedBy)
	var i WaterTreatmentLog
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.TestDate,
		&i.TestTime,
		&i.TestedBy,
		&i.SampleLocation,
		&i.BacterialCountCfuMl,
		&i.EndotoxinLevelEuMl,
		&i.ChlorineLevelPpm,
		&i.ChloramineLevelPpm,
		&i.PhLevel,
		&i.ConductivityUsCm,
		&i.HardnessMgL,
		&i.BacteriaResult,
		&i.EndotoxinResult,
		&i.ChlorineResult,
		&i.OverallResult,
		&i.OutOfSpecParameters,
		&i.CorrectiveActionTaken,
		&i.CorrectiveActionBy,
		&i.RetestRequired,
		&i.RetestDate,
		&i.SystemsShutDown,
		&i.ShutdownTime,
		&i.ResumedTime,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createWaterTreatmentLog = `-- name: CreateWaterTreatmentLog :one
INSERT INTO water_treatment_logs (
    hospital_id, test_date, test_time, tested_by, sample_location,
    bacterial_count_cfu_ml, endotoxin_level_eu_ml, chlorine_level_ppm,
    chloramine_level_ppm, ph_level, conductivity_us_cm, hardness_mg_l,
    bacteria_result, endotoxin_result, chlorine_result, overall_result,
    out_of_spec_parameters, corrective_action_taken, corrective_action_by,
    retest_required, retest_date, systems_shut_down, shutdown_time,
    resumed_time, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25)
RETURNING id, hospital_id, test_date, test_time, tested_by, sample_location, bacterial_count_cfu_ml, endotoxin_level_eu_ml, chlorine_level_ppm, chloramine_level_ppm, ph_level, conductivity_us_cm, hardness_mg_l, bacteria_result, endotoxin_result, chlorine_result, overall_result, out_of_spec_parameters, corrective_action_taken, corrective_action_by, retest_required, retest_date, systems_shut_down, shutdown_time, resumed_time, approved_by, approved_at, notes, created_at, updated_at, deleted_at
`

type CreateWaterTreatmentLogParams struct {
	HospitalID            uuid.UUID          `json:"hospital_id"`
	TestDate              pgtype.Date        `json:"test_date"`
	TestTime              pgtype.Time        `json:"test_time"`
	TestedBy              uuid.UUID          `json:"tested_by"`
	SampleLocation        string             `json:"sample_location"`
	BacterialCountCfuMl   pgtype.Numeric     `json:"bacterial_count_cfu_ml"`
	EndotoxinLevelEuMl    pgtype.Numeric     `json:"endotoxin_level_eu_ml"`
	ChlorineLevelPpm      pgtype.Numeric     `json:"chlorine_level_ppm"`
	ChloramineLevelPpm    pgtype.Numeric     `json:"chloramine_level_ppm"`
	PhLevel               pgtype.Numeric     `json:"ph_level"`
	ConductivityUsCm      pgtype.Numeric     `json:"conductivity_us_cm"`
	HardnessMgL           pgtype.Numeric     `json:"hardness_mg_l"`
	BacteriaResult        WaterTestResult    `json:"bacteria_result"`
	EndotoxinResult       WaterTestResult    `json:"endotoxin_result"`
	ChlorineResult        WaterTestResult    `json:"chlorine_result"`
	OverallResult         WaterTestResult    `json:"overall_result"`
	OutOfSpecParameters   pgtype.Text        `json:"out_of_spec_parameters"`
	CorrectiveActionTaken pgtype.Text        `json:"corrective_action_taken"`
	CorrectiveActionBy    pgtype.UUID        `json:"corrective_action_by"`
	RetestRequired        bool               `json:"retest_required"`
	RetestDate            pgtype.Date        `json:"retest_date"`
	SystemsShutDown       bool               `json:"systems_shut_down"`
	ShutdownTime          pgtype.Timestamptz `json:"shutdown_time"`
	ResumedTime           pgtype.Timestamptz `json:"resumed_time"`
	Notes                 pgtype.Text        `json:"notes"`
}

func (q *Queries) CreateWaterTreatmentLog(ctx context.Context, arg CreateWaterTreatmentLogParams) (WaterTreatmentLog, error) {
	row := q.db.QueryRow(ctx, createWaterTreatmentLog,
		arg.HospitalID,
		arg.TestDate,
		arg.TestTime,
		arg.TestedBy,
		arg.SampleLocation,
		arg.BacterialCountCfuMl,
		arg.EndotoxinLevelEuMl,
		arg.ChlorineLevelPpm,
		arg.ChloramineLevelPpm,
		arg.PhLevel,
		arg.ConductivityUsCm,
		arg.HardnessMgL,
		arg.BacteriaResult,
		arg.EndotoxinResult,
		arg.ChlorineResult,
		arg.OverallResult,
		arg.OutOfSpecParameters,
		arg.CorrectiveActionTaken,
		arg.CorrectiveActionBy,
		arg.RetestRequired,
		arg.RetestDate,
		arg.SystemsShutDown,
		arg.ShutdownTime,
		arg.ResumedTime,
		arg.Notes,
	)
	var i WaterTreatmentLog
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.TestDate,
		&i.TestTime,
		&i.TestedBy,
		&i.SampleLocation,
		&i.BacterialCountCfuMl,
		&i.EndotoxinLevelEuMl,
		&i.ChlorineLevelPpm,
		&i.ChloramineLevelPpm,
		&i.PhLevel,
		&i.ConductivityUsCm,
		&i.HardnessMgL,
		&i.BacteriaResult,
		&i.EndotoxinResult,
		&i.ChlorineResult,
		&i.OverallResult,
		&i.OutOfSpecParameters,
		&i.CorrectiveActionTaken,
		&i.CorrectiveActionBy,
		&i.RetestRequired,
		&i.RetestDate,
		&i.SystemsShutDown,
		&i.ShutdownTime,
		&i.ResumedTime,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteWaterTreatmentLog = `-- name: DeleteWaterTreatmentLog :exec
UPDATE water_treatment_logs SET deleted_at = now() WHERE id = $1
`

func (q *Queries) DeleteWaterTreatmentLog(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWaterTreatmentLog, id)
	return err
}

const getWaterTreatmentLog = `-- name: GetWaterTreatmentLog :one
SELECT id, hospital_id, test_date, test_time, tested_by, sample_location, bacterial_count_cfu_ml, endotoxin_level_eu_ml, chlorine_level_ppm, chloramine_level_ppm, ph_level, conductivity_us_cm, hardness_mg_l, bacteria_result, endotoxin_result, chlorine_result, overall_result, out_of_spec_parameters, corrective_action_taken, corrective_action_by, retest_required, retest_date, systems_shut_down, shutdown_time, resumed_time, approved_by, approved_at, notes, created_at, updated_at, deleted_at FROM water_treatment_logs WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetWaterTreatmentLog(ctx context.Context, id uuid.UUID) (WaterTreatmentLog, error) {
	row := q.db.QueryRow(ctx, getWaterTreatmentLog, id)
	var i WaterTreatmentLog
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.TestDate,
		&i.TestTime,
		&i.TestedBy,
		&i.SampleLocation,
		&i.BacterialCountCfuMl,
		&i.EndotoxinLevelEuMl,
		&i.ChlorineLevelPpm,
		&i.ChloramineLevelPpm,
		&i.PhLevel,
		&i.ConductivityUsCm,
		&i.HardnessMgL,
		&i.BacteriaResult,
		&i.EndotoxinResult,
		&i.ChlorineResult,
		&i.OverallResult,
		&i.OutOfSpecParameters,
		&i.CorrectiveActionTaken,
		&i.CorrectiveActionBy,
		&i.RetestRequired,
		&i.RetestDate,
		&i.SystemsShutDown,
		&i.ShutdownTime,
		&i.ResumedTime,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listFailedWaterTests = `-- name: ListFailedWaterTests :many
SELECT id, hospital_id, test_date, test_time, tested_by, sample_location, bacterial_count_cfu_ml, endotoxin_level_eu_ml, chlorine_level_ppm, chloramine_level_ppm, ph_level, conductivity_us_cm, hardness_mg_l, bacteria_result, endotoxin_result, chlorine_result, overall_result, out_of_spec_parameters, corrective_action_taken, corrective_action_by, retest_required, retest_date, systems_shut_down, shutdown_time, resumed_time, approved_by, approved_at, notes, created_at, updated_at, deleted_at FROM water_treatment_logs
WHERE hospital_id = $1
  AND overall_result = 'fail'
  AND deleted_at IS NULL
ORDER BY test_date DESC, test_time DESC
`

func (q *Queries) ListFailedWaterTests(ctx context.Context, hospitalID uuid.UUID) ([]WaterTreatmentLog, error) {
	rows, err := q.db.Query(ctx, listFailedWaterTests, hospitalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WaterTreatmentLog
	for rows.Next() {
		var i WaterTreatmentLog
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.TestDate,
			&i.TestTime,
			&i.TestedBy,
			&i.SampleLocation,
			&i.BacterialCountCfuMl,
			&i.EndotoxinLevelEuMl,
			&i.ChlorineLevelPpm,
			&i.ChloramineLevelPpm,
			&i.PhLevel,
			&i.ConductivityUsCm,
			&i.HardnessMgL,
			&i.BacteriaResult,
			&i.EndotoxinResult,
			&i.ChlorineResult,
			&i.OverallResult,
			&i.OutOfSpecParameters,
			&i.CorrectiveActionTaken,
			&i.CorrectiveActionBy,
			&i.RetestRequired,
			&i.RetestDate,
			&i.SystemsShutDown,
			&i.ShutdownTime,
			&i.ResumedTime,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingWaterTests = `-- name: ListPendingWaterTests :many
SELECT id, hospital_id, test_date, test_time, tested_by, sample_location, bacterial_count_cfu_ml, endotoxin_level_eu_ml, chlorine_level_ppm, chloramine_level_ppm, ph_level, conductivity_us_cm, hardness_mg_l, bacteria_result, endotoxin_result, chlorine_result, overall_result, out_of_spec_parameters, corrective_action_taken, corrective_action_by, retest_required, retest_date, systems_shut_down, shutdown_time, resumed_time, approved_by, approved_at, notes, created_at, updated_at, deleted_at FROM water_treatment_logs
WHERE hospital_id = $1
  AND overall_result = 'pending'
  AND deleted_at IS NULL
ORDER BY test_date DESC, test_time DESC
`

func (q *Queries) ListPendingWaterTests(ctx context.Context, hospitalID uuid.UUID) ([]WaterTreatmentLog, error) {
	rows, err := q.db.Query(ctx, listPendingWaterTests, hospitalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WaterTreatmentLog
	for rows.Next() {
		var i WaterTreatmentLog
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.TestDate,
			&i.TestTime,
			&i.TestedBy,
			&i.SampleLocation,
			&i.BacterialCountCfuMl,
			&i.EndotoxinLevelEuMl,
			&i.ChlorineLevelPpm,
			&i.ChloramineLevelPpm,
			&i.PhLevel,
			&i.ConductivityUsCm,
			&i.HardnessMgL,
			&i.BacteriaResult,
			&i.EndotoxinResult,
			&i.ChlorineResult,
			&i.OverallResult,
			&i.OutOfSpecParameters,
			&i.CorrectiveActionTaken,
			&i.CorrectiveActionBy,
			&i.RetestRequired,
			&i.RetestDate,
			&i.SystemsShutDown,
			&i.ShutdownTime,
			&i.ResumedTime,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWaterTestsByDate = `-- name: ListWaterTestsByDate :many
SELECT id, hospital_id, test_date, test_time, tested_by, sample_location, bacterial_count_cfu_ml, endotoxin_level_eu_ml, chlorine_level_ppm, chloramine_level_ppm, ph_level, conductivity_us_cm, hardness_mg_l, bacteria_result, endotoxin_result, chlorine_result, overall_result, out_of_spec_parameters, corrective_action_taken, corrective_action_by, retest_required, retest_date, systems_shut_down, shutdown_time, resumed_time, approved_by, approved_at, notes, created_at, updated_at, deleted_at FROM water_treatment_logs
WHERE hospital_id = $1 AND test_date = $2 AND deleted_at IS NULL
ORDER BY test_time
`

type ListWaterTestsByDateParams struct {
	HospitalID uuid.UUID   `json:"hospital_id"`
	TestDate   pgtype.Date `json:"test_date"`
}

func (q *Queries) ListWaterTestsByDate(ctx context.Context, arg ListWaterTestsByDateParams) ([]WaterTreatmentLog, error) {
	rows, err := q.db.Query(ctx, listWaterTestsByDate, arg.HospitalID, arg.TestDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WaterTreatmentLog
	for rows.Next() {
		var i WaterTreatmentLog
		if err := rows.Scan(
			&i.ID,
			&i.HospitalID,
			&i.TestDate,
			&i.TestTime,
			&i.TestedBy,
			&i.SampleLocation,
			&i.BacterialCountCfuMl,
			&i.EndotoxinLevelEuMl,
			&i.ChlorineLevelPpm,
			&i.ChloramineLevelPpm,
			&i.PhLevel,
			&i.ConductivityUsCm,
			&i.HardnessMgL,
			&i.BacteriaResult,
			&i.EndotoxinResult,
			&i.ChlorineResult,
			&i.OverallResult,
			&i.OutOfSpecParameters,
			&i.CorrectiveActionTaken,
			&i.CorrectiveActionBy,
			&i.RetestRequired,
			&i.RetestDate,
			&i.SystemsShutDown,
			&i.ShutdownTime,
			&i.ResumedTime,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWaterTestResults = `-- name: UpdateWaterTestResults :one
UPDATE water_treatment_logs
SET bacteria_result = $2, endotoxin_result = $3, chlorine_result = $4,
    overall_result = $5, out_of_spec_parameters = $6,
    corrective_action_taken = $7, corrective_action_by = $8,
    retest_required = $9, retest_date = $10
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, hospital_id, test_date, test_time, tested_by, sample_location, bacterial_count_cfu_ml, endotoxin_level_eu_ml, chlorine_level_ppm, chloramine_level_ppm, ph_level, conductivity_us_cm, hardness_mg_l, bacteria_result, endotoxin_result, chlorine_result, overall_result, out_of_spec_parameters, corrective_action_taken, corrective_action_by, retest_required, retest_date, systems_shut_down, shutdown_time, resumed_time, approved_by, approved_at, notes, created_at, updated_at, deleted_at
`

type UpdateWaterTestResultsParams struct {
	ID                    uuid.UUID       `json:"id"`
	BacteriaResult        WaterTestResult `json:"bacteria_result"`
	EndotoxinResult       WaterTestResult `json:"endotoxin_result"`
	ChlorineResult        WaterTestResult `json:"chlorine_result"`
	OverallResult         WaterTestResult `json:"overall_result"`
	OutOfSpecParameters   pgtype.Text     `json:"out_of_spec_parameters"`
	CorrectiveActionTaken pgtype.Text     `json:"corrective_action_taken"`
	CorrectiveActionBy    pgtype.UUID     `json:"corrective_action_by"`
	RetestRequired        bool            `json:"retest_required"`
	RetestDate            pgtype.Date     `json:"retest_date"`
}

func (q *Queries) UpdateWaterTestResults(ctx context.Context, arg UpdateWaterTestResultsParams) (WaterTreatmentLog, error) {
	row := q.db.QueryRow(ctx, updateWaterTestResults,
		arg.ID,
		arg.BacteriaResult,
		arg.EndotoxinResult,
		arg.ChlorineResult,
		arg.OverallResult,
		arg.OutOfSpecParameters,
		arg.CorrectiveActionTaken,
		arg.CorrectiveActionBy,
		arg.RetestRequired,
		arg.RetestDate,
	)
	var i WaterTreatmentLog
	err := row.Scan(
		&i.ID,
		&i.HospitalID,
		&i.TestDate,
		&i.TestTime,
		&i.TestedBy,
		&i.SampleLocation,
		&i.BacterialCountCfuMl,
		&i.EndotoxinLevelEuMl,
		&i.ChlorineLevelPpm,
		&i.ChloramineLevelPpm,
		&i.PhLevel,
		&i.ConductivityUsCm,
		&i.HardnessMgL,
		&i.BacteriaResult,
		&i.EndotoxinResult,
		&i.ChlorineResult,
		&i.OverallResult,
		&i.OutOfSpecParameters,
		&i.CorrectiveActionTaken,
		&i.CorrectiveActionBy,
		&i.RetestRequired,
		&i.RetestDate,
		&i.SystemsShutDown,
		&i.ShutdownTime,
		&i.ResumedTime,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
